# graphics/gmapunit -- graphics blobs carved out of the dat_worldmap_gmapunit_p*
# address-page files (which are mostly NON-graphics data tables left as incbin).
# LZ77 tiles/tilemaps commit the DECOMPRESSED .bin (Makefile %.lz: % recompresses
# byte-identical); uncompressed palettes commit a JASC .pal (-> .gbapal).
# Verbatim uncompressed .bin blobs are committed source themselves (no rule, no
# dep line). Auto-generated by graphics/gmapunit/extract_gmapunit_gfx.py.

asm/dat_worldmap_gmapunit_p1519.o: \
  graphics/gmapunit/Img_TalkBubble.bin.lz \
  graphics/gmapunit/Img_TalkBubbleOpening_A.bin.lz \
  graphics/gmapunit/Img_TalkBubbleOpening_B.bin.lz \
  graphics/gmapunit/Img_TalkBubbleOpening_C.bin.lz \
  graphics/gmapunit/Img_TalkBubbleOpening_D.bin.lz \
  graphics/gmapunit/Img_TalkBubbleOpening_E.bin.lz \
  graphics/gmapunit/Pal_TalkBubble.gbapal

asm/dat_worldmap_gmapunit_p1572.o: \
  graphics/gmapunit/Img_StatscreenEquipmentText.bin.lz \
  graphics/gmapunit/Img_StatscreenObjs.bin.lz \
  graphics/gmapunit/Pal_StatscreenEquipmentText.gbapal \
  graphics/gmapunit/Tsa_StatscreenEquipmentBG.bin.lz \
  graphics/gmapunit/gGfx_HelpTextBox.bin.lz \
  graphics/gmapunit/gGfx_HelpTextBox2.bin.lz \
  graphics/gmapunit/gGfx_HelpTextBox3.bin.lz \
  graphics/gmapunit/gGfx_HelpTextBox4.bin.lz \
  graphics/gmapunit/gGfx_HelpTextBox5.bin.lz \
  graphics/gmapunit/gGfx_YellowTextBox.bin.lz \
  graphics/gmapunit/gGfx_YellowTextBox2.bin.lz \
  graphics/gmapunit/gGfx_YellowTextBox3.bin.lz \
  graphics/gmapunit/gGfx_YellowTextBox4.bin.lz \
  graphics/gmapunit/gGfx_YellowTextBox5.bin.lz

asm/dat_worldmap_gmapunit_p1573.o: \
  graphics/gmapunit/Img_ConfigUiIcons.bin.lz \
  graphics/gmapunit/Img_ConfigUiSprites.bin.lz \
  graphics/gmapunit/Img_StatscreenBG.bin.lz \
  graphics/gmapunit/Img_StatscreenHalo.bin.lz \
  graphics/gmapunit/Pal_ConfigUiSprites.gbapal \
  graphics/gmapunit/Pal_StatscreenBG.gbapal \
  graphics/gmapunit/Pal_StatscreenHalo.gbapal \
  graphics/gmapunit/Tsa_ConfigUiFrame.bin.lz \
  graphics/gmapunit/Tsa_StatscreenBG.bin.lz \
  graphics/gmapunit/Tsa_StatscreenHalo.bin.lz \
  graphics/gmapunit/gPal_UnkData_0.gbapal \
  graphics/gmapunit/gPal_UnkData_1.gbapal

asm/dat_worldmap_gmapunit_p1579.o: \
  graphics/gmapunit/gGfx_PlayerInterfaceFontTiles.bin.lz \
  graphics/gmapunit/gGfx_PlayerInterfaceNumbers.bin.lz

asm/dat_worldmap_gmapunit_p1580.o: \
  graphics/gmapunit/gPal_PlayerInterface_Blue.gbapal \
  graphics/gmapunit/gPal_PlayerInterface_Green.gbapal \
  graphics/gmapunit/gPal_PlayerInterface_Red.gbapal

asm/dat_worldmap_gmapunit_p1599.o: \
  graphics/gmapunit/Pal_SpinningArrow.gbapal

asm/dat_worldmap_gmapunit_p1600.o: \
  graphics/gmapunit/Img_SysBrownBox.bin.lz

asm/dat_worldmap_gmapunit_p1601.o: \
  graphics/gmapunit/Img_PrepFunds.bin.lz

asm/dat_worldmap_gmapunit_p1602.o: \
  graphics/gmapunit/Img_PrepItemUseScreen.bin.lz \
  graphics/gmapunit/Img_PrepTextShadow.bin.lz \
  graphics/gmapunit/Img_SpinningArrow.bin.lz \
  graphics/gmapunit/Img_UnitListBanner_Animation.bin.lz \
  graphics/gmapunit/Img_UnitListBanners.bin.lz \
  graphics/gmapunit/Img_UnkData_1.bin.lz \
  graphics/gmapunit/Pal_UnkData_1.gbapal \
  graphics/gmapunit/Tsa_PrepItemScreen.bin.lz \
  graphics/gmapunit/Tsa_PrepItemUseScreen.bin.lz \
  graphics/gmapunit/Tsa_UnkData_4.bin.lz \
  graphics/gmapunit/gImg_UiSpinningArrow_Horizontal.bin.lz

asm/dat_worldmap_gmapunit_p1605.o: \
  graphics/gmapunit/Img_PrepWindow.bin.lz

asm/dat_worldmap_gmapunit_p1621.o: \
  graphics/gmapunit/gGfx_MinimapTiles.bin.lz \
  graphics/gmapunit/gPal_MinimapTiles.gbapal \
  graphics/gmapunit/gPal_Minimap_0.gbapal

asm/dat_worldmap_gmapunit_p1634.o: \
  graphics/gmapunit/Pal_DifficultyMenuObjs.gbapal

asm/dat_worldmap_gmapunit_p1637.o: \
  graphics/gmapunit/Img_SoundRoomVolumeGraph.bin.lz \
  graphics/gmapunit/Pal_SoundRoomVolumeGraph.gbapal

asm/dat_worldmap_gmapunit_p1638.o: \
  graphics/gmapunit/Img_ChapterStatusSelectorSprite.bin.lz \
  graphics/gmapunit/Img_PlayStatusSprites.bin.lz \
  graphics/gmapunit/Pal_PlayStatusSprites.gbapal

asm/dat_worldmap_gmapunit_p1639.o: \
  graphics/gmapunit/Img_MenuStatus_0.bin.lz \
  graphics/gmapunit/Img_SysBlackBox.bin.lz \
  graphics/gmapunit/Pal_MenuStatus_0.gbapal

asm/dat_worldmap_gmapunit_p723.o: \
  graphics/gmapunit/Img_DanceringFx.bin.lz \
  graphics/gmapunit/Img_EventWarp.bin.lz \
  graphics/gmapunit/Pal_DanceringFx.gbapal \
  graphics/gmapunit/Pal_EventWarp.gbapal \
  graphics/gmapunit/Tsa_DanceringFx.bin.lz \
  graphics/gmapunit/Tsa_EventWarp.bin.lz

asm/dat_worldmap_gmapunit_p724.o: \
  graphics/gmapunit/Img_MineFx.bin.lz

asm/dat_worldmap_gmapunit_p751.o: \
  graphics/gmapunit/Img_SysGrayBox.bin.lz

asm/dat_worldmap_gmapunit_p756.o: \
  graphics/gmapunit/Img_NODAMGEMIS.bin.lz \
  graphics/gmapunit/Pal_Efxbattle_0.gbapal \
  graphics/gmapunit/Pal_Efxbattle_1.gbapal \
  graphics/gmapunit/Pal_Efxbattle_2.gbapal

asm/dat_worldmap_gmapunit_p757.o: \
  graphics/gmapunit/Img_BanimArcherMBallistaIntro.bin.lz

asm/dat_worldmap_gmapunit_p758.o: \
  graphics/gmapunit/Img_LvupApfx.bin.lz \
  graphics/gmapunit/Pal_LvupApfx.gbapal

asm/dat_worldmap_gmapunit_p759.o: \
  graphics/gmapunit/Img_ArenaBattleBg.bin.lz \
  graphics/gmapunit/Pal_ArenaBattleBg_A.gbapal \
  graphics/gmapunit/Pal_ArenaBattleBg_B.gbapal \
  graphics/gmapunit/Pal_ArenaBattleBg_C.gbapal \
  graphics/gmapunit/Tsa_ArenaBattleBg.bin.lz

asm/dat_worldmap_gmapunit_p761.o: \
  graphics/gmapunit/Img_EfxLvupBG2.bin.lz \
  graphics/gmapunit/Img_EfxLvupOBJ2.bin.lz \
  graphics/gmapunit/Pal_EfxLvupBG.gbapal \
  graphics/gmapunit/Pal_EfxLvupBG2.gbapal \
  graphics/gmapunit/Pal_EfxLvupBGCOL.gbapal

asm/dat_worldmap_gmapunit_p798.o: \
  graphics/gmapunit/Img_EfxArrowOBJ.bin.lz

asm/dat_worldmap_gmapunit_p938.o: \
  graphics/gmapunit/Tsa_SilenceBg_2.bin.lz

