#!/bin/sh
# Single source of truth for the production link command, parameterized so the
# shiftability harness can produce variant ELFs without duplicating the link line
# (which lives in the Makefile $(ELF) rule). Two uses:
#   - Layer 1: relink with `-q` (--emit-relocs) so the ELF retains R_ARM_ABS32
#     relocations; scan_relocs.py uses them to separate symbol-derived pointers
#     (safe) from raw hardcoded address literals (unsafe).
#   - Layer 2: relink against a *shifted* ldscript to produce a moved image
#     (not applicable to fe8j's packed/no-slack ldscript -- see README / D313).
#
# It NEVER touches the matching build: it writes to a separate output ELF/map.
#
# fe8j vs fe8u link line: fe8j links every object directly (no `@objects.lst`
# response file in the Makefile $(ELF) rule, no separate banim sub-link object),
# and passes `--no-check-sections` because the JP layout has overlapping NOLOAD
# overlay declarations. The harness still drives the link through an OBJECTS_LST
# response file (generated by the Makefile $(OBJECTS_LST) rule via GNU make's
# $(file >...) function) so the command line cannot overflow the shell arg limit.
#
# Usage: emit_relocs_link.sh <out.elf> <ldscript> [extra ld flags...]
# Env (default to the project's values): LD, OBJECTS_LST.
set -e

OUT="$1"
LDSCRIPT="$2"
shift 2

LD="${LD:-arm-none-eabi-ld}"
OBJECTS_LST="${OBJECTS_LST:-objects.lst}"

exec "$LD" --no-check-sections -T "$LDSCRIPT" -Map "${OUT%.elf}.map" \
    @"$OBJECTS_LST" -L tools/agbcc/lib -o "$OUT" -lc -lgcc "$@"
