@ Raw-ROM decompilation baseline (GENERATED by scripts/gen_layout.py).
@ The original ROM is incbinned in the gaps between carved sections so the
@ build stays byte-perfect. Edit layout/carved_rom.tsv, not this file.

	.section .gap_0, "ax", %progbits
	.incbin "baserom.gba", 0xC0, 0xA4C	@ 0x0000C0..0x000B0C

	.section .gap_1, "ax", %progbits
	.incbin "baserom.gba", 0xCD8, 0xDB45C	@ 0x000CD8..0x0DC134

	.section .gap_2, "ax", %progbits
	.incbin "baserom.gba", 0xDC144	@ 0x0DC144..0x1000000

