@ data_08A5AE80: 104 bytes of raw JP ROM data at 0x08A5AE80..0x08A5AEE8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5AE80, "a", %progbits
	.global data_08A5AE80
data_08A5AE80:
	@ de-pointered (scripts/repoint_table.py): ptr=4 data=21 skip=1
	.4byte 0x00000002
	.4byte 0x08A64CA8
	.4byte 0x00000004
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000006
	.4byte EventScr_Ch6_1
	.4byte 0x0010120B
	.4byte 0x00000005
	.4byte 0x00000001
	.4byte 0x0020110B
	.4byte 0x00000000
	.4byte 0x00030001
	.4byte EventScr_Ch6_EndingScene
	.4byte 0x00000002
	.4byte 0x0007000B
	.4byte EventScr_Ch6_0
	.4byte 0x0E1B0918
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
