@ data_0855F708: 32 bytes of raw JP ROM data at 0x0855F708..0x0855F728,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0855F708, "a", %progbits
	.global data_0855F708
data_0855F708:
	@ de-pointered (scripts/repoint_table.py): ptr=6 data=1 skip=1
	.4byte 0x940A0006
	.4byte 0x0820F2E8
	.4byte song060_bgm_sys_fase_pl_1
	.4byte song060_bgm_sys_fase_pl_2
	.4byte song060_bgm_sys_fase_pl_3
	.4byte song060_bgm_sys_fase_pl_4
	.4byte song060_bgm_sys_fase_pl_5
	.4byte song060_bgm_sys_fase_pl_6
