@ AnimScr_EfxFireOBJ_L_Front: 88 bytes of raw JP ROM data at 0x08624C8C..0x08624CE4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08624C8C, "a", %progbits
	.global AnimScr_EfxFireOBJ_L_Front
AnimScr_EfxFireOBJ_L_Front:
	.incbin "data/residual/AnimScr_EfxFireOBJ_L_Front.bin"
