@ data_08909814: 180 bytes of raw JP ROM data at 0x08909814..0x089098C8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08909814, "a", %progbits
	.global data_08909814
data_08909814:
	.incbin "data/residual/data_08909814.bin"
