@ data_0857AE4C: 216 bytes of raw JP ROM data at 0x0857AE4C..0x0857AF24,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0857AE4C, "a", %progbits
	.global data_0857AE4C
data_0857AE4C:
	.incbin "data/residual/data_0857AE4C.bin"
