@ data_080DC684: 396 bytes of raw JP ROM data at 0x080DC684..0x080DC810,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.080DC684, "a", %progbits
	.global data_080DC684
data_080DC684:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=85 skip=13
	.4byte 0xFF0000FF
	.4byte 0x01000001
	.4byte 0x75836683
	.4byte 0xF195EE8F
	.4byte 0x00000000
	.4byte 0xEA82B090
	.4byte 0x00000000
	.4byte 0x9297BB8D
	.4byte 0x00000000
	.4byte 0x0000E190
	.4byte 0xE1908190
	.4byte 0x00000000
	.4byte 0x00004A89
	.4byte 0x0000E996
	.4byte 0xE28A6E97
	.4byte 0x00000000
	.4byte 0x080DC698
	.4byte 0x080DC6A0
	.4byte 0x080DC6A8
	.4byte 0x080DC6AC
	.4byte 0x080DC6B4
	.4byte 0x080DC6B8
	.4byte 0x080DC6BC
	.4byte 0x438B5693
	.4byte 0x00000000
	.4byte 0xF189FC8E
	.4byte 0x00009490
	.4byte 0xDA96FC8E
	.4byte 0x00000000
	.4byte 0xA482E082
	.4byte 0xDF82BE82
	.4byte 0x0000DB82
	.4byte 0xAD82B382
	.4byte 0x00004793
	.4byte 0x6F826282
	.4byte 0x00000000
	.4byte 0xD48A6C90
	.4byte 0x00000000
	.4byte 0x518E7395
	.4byte 0x0000C189
	.4byte data_080DC70C
	.4byte 0x080DC714
	.4byte 0x080DC71C
	.4byte 0x528CCE97
	.4byte 0x00000000
	.4byte 0x528CD490
	.4byte 0x00000000
	.4byte 0x2D2D2D2D
	.4byte 0x00002D2D
	.4byte 0x6F747554
	.4byte 0x00000000
	.4byte 0x69726945
	.4byte 0x0000726B
	.4byte 0x616C6645
	.4byte 0x0000006D
	.4byte 0x080DC740
	.4byte 0x080DC748
	.4byte 0x080DC750
	.4byte 0x080DC758
	.4byte 0x20202020
	.4byte 0x20202020
	.4byte 0x20202020
	.4byte 0x20202020
	.4byte 0x20202020
	.4byte 0x00000000
	.4byte 0x4C505F45
	.4byte 0x52455941
	.4byte 0x53414850
	.4byte 0x00000045
	.4byte 0x43564C4D
	.4byte 0x00004348
	.4byte 0x4F4D5F45
	.4byte 0x494C4556
	.4byte 0x5654494D
	.4byte 0x00574549
	.4byte 0x44494F4B
	.4byte 0x0000004F
	.4byte 0x44494F4B
	.4byte 0x4D4D414F
	.4byte 0x00000000
	.4byte 0x46584D42
	.4byte 0x00454441
	.4byte 0x554A4441
	.4byte 0x46535453
	.4byte 0x584D4F52
	.4byte 0x00000049
	.4byte 0x00000000
	.4byte 0x00000008
	.4byte 0x00000010
	.4byte 0x00000018
	.4byte 0x00000900
	.4byte 0x00000908
	.4byte 0x00000910
	.4byte 0x00000918
	.4byte 0x00001200
	.4byte 0x00001208
	.4byte 0x00001210
	.4byte 0x00001218
	.4byte 0x0000FFFF
