@ data_085E0698: 212 bytes of raw JP ROM data at 0x085E0698..0x085E076C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.085E0698, "a", %progbits
	.global data_085E0698
data_085E0698:
	.incbin "baserom.gba", 0x5E0698, 0xD4
