@ data_0856DBC0: 16 bytes of raw JP ROM data at 0x0856DBC0..0x0856DBD0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0856DBC0, "a", %progbits
	.global data_0856DBC0
data_0856DBC0:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=1 skip=1
	.4byte 0x00140002
	.4byte 0x082014A0
	.4byte song144_se_sys_chapter_start1_1_1
	.4byte song144_se_sys_chapter_start1_1_2
