@ data_08908704: 60 bytes of raw JP ROM data at 0x08908704..0x08908740,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08908704, "a", %progbits
	.global UnitDef_Event_Ch1AllyReinforce
UnitDef_Event_Ch1AllyReinforce:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=12 skip=1
	.4byte 0x08010504
	.4byte 0x01000005
	.4byte REDA_Ch1_Franz
	.4byte 0x6C6C1401
	.4byte 0x00000000
	.4byte 0x20000903
	.4byte 0x01000006
	.4byte REDA_Ch1_Gilliam
	.4byte 0x00000014
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
