@ data_08A710FC: 152 bytes of raw JP ROM data at 0x08A710FC..0x08A71194,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A710FC, "a", %progbits
	.global data_08A710FC
data_08A710FC:
	.incbin "baserom.gba", 0xA710FC, 0x98
