@ AnimSprite_EfxTeyariObjType1Left_9: 284 bytes of raw JP ROM data at 0x08606FE4..0x08607100,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08606FE4, "a", %progbits
	.global AnimSprite_EfxTeyariObjType1Left_9
AnimSprite_EfxTeyariObjType1Left_9:
	.incbin "data/residual/data_08606FE4.bin"
