@ data_08A60354: 352 bytes of raw JP ROM data at 0x08A60354..0x08A604B4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A60354, "a", %progbits
	.global data_08A60354
data_08A60354:
	@ de-pointered (scripts/repoint_table.py): ptr=3 data=79 skip=6
	.4byte 0x00000C41
	.4byte 0x0000000C
	.4byte 0x00001922
	.4byte 0x00000C40
	.4byte 0x0000000C
	.4byte 0x00320620
	.4byte 0x00000820
	.4byte 0x004C0620
	.4byte 0x00000A40
	.4byte 0x08A60320
	.4byte 0x00000120
	.4byte 0x00001927
	.4byte 0x00000C41
	.4byte 0x0000000C
	.4byte 0x00001922
	.4byte 0x00000C40
	.4byte 0x0000000C
	.4byte 0x003C0620
	.4byte 0x00000A40
	.4byte 0x08A60320
	.4byte 0x00000820
	.4byte 0x00000120
	.4byte 0x00041020
	.4byte 0x00000A40
	.4byte 0x085B9D24
	.4byte 0x00090228
	.4byte 0x00012C40
	.4byte 0xFFFFFFFF
	.4byte 0x00003020
	.4byte 0x00090220
	.4byte 0x00001020
	.4byte 0x00000120
	.4byte 0x00001927
	.4byte 0x00000C41
	.4byte 0x0000000C
	.4byte 0x00001922
	.4byte 0x00000C40
	.4byte 0x0000000C
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00000820
	.4byte 0x00000120
	.4byte 0x00080320
	.4byte 0x80BD0C41
	.4byte 0x0000000C
	.4byte 0x00101721
	.4byte 0x80BD0820
	.4byte 0x00001A20
	.4byte 0x00002220
	.4byte 0x00101720
	.4byte 0x00000120
	.4byte 0x00080320
	.4byte 0x80D20C41
	.4byte 0x0000000C
	.4byte 0x00101721
	.4byte 0x80D20820
	.4byte 0x00001A21
	.4byte 0xFFFF2140
	.4byte 0x00000000
	.4byte 0x00101720
	.4byte 0x00000120
	.4byte 0x00000A40
	.4byte 0x08A60420
	.4byte 0x00320620
	.4byte 0xFFFF1B20
	.4byte 0x00001D20
	.4byte 0x00000A40
	.4byte 0x08A603FC
	.4byte 0x00000120
	.4byte 0x00011020
	.4byte 0xFFFE2720
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte 0x00000000
	.4byte 0x00000A40
	.4byte EventScr_ApplyTileChangeForFaction
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte 0x00000002
	.4byte 0x00000A40
	.4byte EventScr_ApplyTileChangeForFaction
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte 0x00000001
	.4byte 0x00000A40
	.4byte EventScr_ApplyTileChangeForFaction
	.4byte 0x00000120
