@ data_081CB584: 344 bytes of raw JP ROM data at 0x081CB584..0x081CB6DC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.081CB584, "a", %progbits
	.global data_081CB584
data_081CB584:
	.incbin "baserom.gba", 0x1CB584, 0x158
