@ WmMonsterGenerateRatesIdx_EirikaMode: 121 bytes of raw JP ROM data at 0x081F66A4..0x081F671D,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.081F66A4, "a", %progbits
	.global WmMonsterGenerateRatesIdx_EirikaMode
WmMonsterGenerateRatesIdx_EirikaMode:
	.incbin "data/residual/WmMonsterGenerateRatesIdx_EirikaMode.bin"
