@ data_085C3950: 128 bytes of raw JP ROM data at 0x085C3950..0x085C39D0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.085C3950, "a", %progbits
	.global data_085C3950
data_085C3950:
	.incbin "data/residual/data_085C3950.bin"
