@ data_0860DEB4: 108 bytes of raw JP ROM data at 0x0860DEB4..0x0860DF20,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0860DEB4, "a", %progbits
	.global data_0860DEB4
data_0860DEB4:
	.incbin "data/residual/data_0860DEB4.bin"
