@ data_08908DBC: 208 bytes of raw JP ROM data at 0x08908DBC..0x08908E8C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08908DBC, "a", %progbits
	.global data_08908DBC
data_08908DBC:
	.incbin "data/residual/data_08908DBC.bin"
