@ sGmapFadeRampAndStrings_081F5BF4: 124 bytes of raw JP ROM data at 0x081F5BF0..0x081F5C6C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.081F5BF0, "a", %progbits
	.global sGmapFadeRampAndStrings_081F5BF4
sGmapFadeRampAndStrings_081F5BF4:
	.incbin "data/residual/data_081F5BF0.bin"
