@ dat_REDA_08926134_ref: 228 bytes of raw JP ROM data at 0x08926134..0x08926218,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08926134, "a", %progbits
	.global dat_REDA_08926134_ref
dat_REDA_08926134_ref:
	.incbin "data/residual/data_08926134.bin"
