@ SpriteArray_SavemenuData_0: 416 bytes of raw JP ROM data at 0x08A9D904..0x08A9DAA4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A9D904, "a", %progbits
	.global SpriteArray_SavemenuData_0
SpriteArray_SavemenuData_0:
	.incbin "data/residual/SpriteArray_SavemenuData_0.bin"
