@ data_0890C9BC: 268 bytes of raw JP ROM data at 0x0890C9BC..0x0890CAC8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0890C9BC, "a", %progbits
	.global data_0890C9BC
data_0890C9BC:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=65 skip=1
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x08004822
	.4byte 0x01000080
	.4byte REDA_Ch9AAlly_3_TANA
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x000006C0
	.4byte 0x0000FFFF
	.4byte 0x000006C1
	.4byte 0x0000FFFF
	.4byte 0x00000701
	.4byte 0x0000FFFF
	.4byte 0x00000702
	.4byte 0x0000FFFF
	.4byte 0x00000742
	.4byte 0x0000FFFF
	.4byte 0x00000610
	.4byte 0x0000FFFF
	.4byte 0x0000064F
	.4byte 0x0000FFFF
	.4byte 0x00000651
	.4byte 0x0000FFFF
	.4byte 0x00000690
	.4byte 0x0000FFFF
	.4byte 0x000001C1
	.4byte 0x0000FFFF
	.4byte 0x00000182
	.4byte 0x0000FFFF
	.4byte 0x00010143
	.4byte 0x0000FFFF
	.4byte 0x00010144
	.4byte 0x0010FFFF
	.4byte 0x00010106
	.4byte 0x0000FFFF
	.4byte 0x00010104
	.4byte 0x0000FFFF
	.4byte 0x00010103
	.4byte 0x0000FFFF
	.4byte 0x000100C5
	.4byte 0x0000FFFF
	.4byte 0x000100C4
	.4byte 0x0000FFFF
	.4byte 0x000000C3
	.4byte 0x0000FFFF
	.4byte 0x00010084
	.4byte 0x0000FFFF
	.4byte 0x00010082
	.4byte 0x0000FFFF
	.4byte 0x00010043
	.4byte 0x0000FFFF
	.4byte 0x00010041
	.4byte 0x0000FFFF
	.4byte 0x00010683
	.4byte 0x0000FFFF
	.4byte 0x000106C4
	.4byte 0x0010FFFF
	.4byte 0x000106C2
	.4byte 0x0010FFFF
