@ data_086AEA74: 156 bytes of raw JP ROM data at 0x086AEA74..0x086AEB10,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086AEA74, "a", %progbits
	.global data_086AEA74
data_086AEA74:
	.incbin "baserom.gba", 0x6AEA74, 0x9C
