@ data_08A614C0: 80 bytes of raw JP ROM data at 0x08A614C0..0x08A61510,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A614C0, "a", %progbits
	.global data_08A614C0
data_08A614C0:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=17 skip=2
	.4byte 0x00070228
	.4byte 0x00010B41
	.4byte 0x08A614D0
	.4byte 0x00000120
	.4byte 0x00070228
	.4byte 0x00001120
	.4byte 0x00000A40
	.4byte EventScr_Prologue_GiveRapier
	.4byte 0x00023426
	.4byte 0x00B70229
	.4byte 0x00000120
	.4byte 0x00001A23
	.4byte 0x000B0540
	.4byte 0xFFFFFFFF
	.4byte 0x08DD1B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00B40229
	.4byte 0x00B50229
	.4byte 0x00000120
