@ data_08A68574: 20 bytes of raw JP ROM data at 0x08A68574..0x08A68588,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A68574, "a", %progbits
	.global EventScr_Ch15A_1
EventScr_Ch15A_1:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=4 skip=0
	.4byte 0x00000A40
	.4byte EventScr_Ch15A_26
	.4byte 0x00770229
	.4byte 0x00102A21
	.4byte 0x00000120
