@ dat_Ch17EphraimEventData_ref: 72 bytes of raw JP ROM data at 0x08A5D1E8..0x08A5D230,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5D1E8, "a", %progbits
	.global dat_Ch17EphraimEventData_ref
dat_Ch17EphraimEventData_ref:
	.incbin "data/residual/data_08A5D1E8.bin"
