@ data_08612134: 444 bytes of raw JP ROM data at 0x08612134..0x086122F0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08612134, "a", %progbits
	.global data_08612134
data_08612134:
	.incbin "baserom.gba", 0x612134, 0x1BC
