@ data_08A652C0: 244 bytes of raw JP ROM data at 0x08A652C0..0x08A653B4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A652C0, "a", %progbits
	.global data_08A652C0
data_08A652C0:
	@ de-pointered (scripts/repoint_table.py): ptr=3 data=55 skip=3
	.4byte 0x00311220
	.4byte 0x00020540
	.4byte 0x00000015
	.4byte 0x00000A40
	.4byte 0x08A60420
	.4byte 0x09D11B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00DF0229
	.4byte 0x00062A21
	.4byte 0x00000120
	.4byte 0x00271220
	.4byte 0x00001A20
	.4byte 0x09D21B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00001520
	.4byte 0x00001A20
	.4byte 0x09D31B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00001521
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00001520
	.4byte 0x00001A20
	.4byte 0x09D41B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00001521
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00001520
	.4byte 0x00001A20
	.4byte 0x09D51B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00001521
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte 0x00000000
	.4byte 0x00000A40
	.4byte UnitDef_Ch14BAlly_7
	.4byte 0x000C0221
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch8Enemy_1
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch8Enemy_2
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
