@ data_08A63088: 80 bytes of raw JP ROM data at 0x08A63088..0x08A630D8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A63088, "a", %progbits
	.global data_08A63088
data_08A63088:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=17 skip=2
	.4byte 0x00070228
	.4byte 0x00000D40
	.4byte 0x0801D44D
	.4byte 0xFFFD3D20
	.4byte 0x00001120
	.4byte 0x00040B41
	.4byte 0x08A630A8
	.4byte 0x00000120
	.4byte 0x00070228
	.4byte 0x00001120
	.4byte 0x00001A23
	.4byte 0x000B0540
	.4byte 0x00380010
	.4byte 0x093A1B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x010A1120
	.4byte 0x00010B41
	.4byte EventScr_Ch2Tutorial21
	.4byte 0x00000120
