@ data_08570120: 32 bytes of raw JP ROM data at 0x08570120..0x08570140,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08570120, "a", %progbits
	.global data_08570120
data_08570120:
	@ de-pointered (scripts/repoint_table.py): ptr=7 data=1 skip=0
	.4byte 0x00140006
	.4byte voicegroup038
	.4byte song320_bmp_evt_20b_1_1
	.4byte song320_bmp_evt_20b_1_2
	.4byte song320_bmp_evt_20b_1_3
	.4byte song320_bmp_evt_20b_1_4
	.4byte song320_bmp_evt_20b_1_5
	.4byte song320_bmp_evt_20b_1_6
