@ data_085757CC: 24 bytes of raw JP ROM data at 0x085757CC..0x085757E4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.085757CC, "a", %progbits
	.global data_085757CC
data_085757CC:
	@ de-pointered (scripts/repoint_table.py): ptr=5 data=1 skip=0
	.4byte 0x00140004
	.4byte voicegroup038
	.4byte song946_mon_mao_magic1_1_1
	.4byte song946_mon_mao_magic1_1_2
	.4byte song946_mon_mao_magic1_1_3
	.4byte song946_mon_mao_magic1_1_4
