@ data_081C5810: 360 bytes of raw JP ROM data at 0x081C5810..0x081C5978,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.081C5810, "a", %progbits
	.global data_081C5810
data_081C5810:
	.incbin "data/residual/data_081C5810.bin"
