@ data_086215FC: 232 bytes of raw JP ROM data at 0x086215FC..0x086216E4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086215FC, "a", %progbits
	.global data_086215FC
data_086215FC:
	.incbin "baserom.gba", 0x6215FC, 0xE8
