@ data_085775A4: 164 bytes of raw JP ROM data at 0x085775A4..0x08577648,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.085775A4, "a", %progbits
	.global data_085775A4
data_085775A4:
	.incbin "baserom.gba", 0x5775A4, 0xA4
