@ data_0857C6C4: 360 bytes of raw JP ROM data at 0x0857C6C4..0x0857C82C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0857C6C4, "a", %progbits
	.global data_0857C6C4
data_0857C6C4:
	@ de-pointered (scripts/repoint_table.py): ptr=5 data=85 skip=0
	.4byte gFontgrp_334
	.4byte 0x00000683
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000FFC
	.4byte 0x00003AAB
	.4byte 0x00003BFC
	.4byte 0x00003BB0
	.4byte 0x00000EB0
	.4byte 0x000003B0
	.4byte 0x000000EC
	.4byte 0x00000030
	.4byte 0x00000000
	.4byte gFontgrp_336
	.4byte 0x00000683
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000C00
	.4byte 0x00003B00
	.4byte 0x00000EF0
	.4byte 0x000003AC
	.4byte 0x000003BB
	.4byte 0x000003BC
	.4byte 0x000003B0
	.4byte 0x000000C0
	.4byte 0x00000000
	.4byte gFontgrp_338
	.4byte 0x00000683
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x000000C0
	.4byte 0x00000FBC
	.4byte 0x00003AAB
	.4byte 0x00003BFB
	.4byte 0x00003B3B
	.4byte 0x00000EFC
	.4byte 0x000003AC
	.4byte 0x000000F0
	.4byte 0x00000000
	.4byte gFontgrp_340
	.4byte 0x00000683
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000FFC
	.4byte 0x00003AAB
	.4byte 0x00000FBC
	.4byte 0x000003B0
	.4byte 0x000003B0
	.4byte 0x00000FBC
	.4byte 0x00003AAB
	.4byte 0x00000FFC
	.4byte 0x00000000
	.4byte gFontgrp_342
	.4byte 0x00000783
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000300
	.4byte 0x00003EFC
	.4byte 0x0000EAAB
	.4byte 0x00003EBC
	.4byte 0x00000EEC
	.4byte 0x00000EFB
	.4byte 0x00000ECC
	.4byte 0x00000300
	.4byte 0x00000000
