@ data_0885FF27: 195 bytes of raw JP ROM data at 0x0885FF27..0x0885FFEA,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0885FF27, "a", %progbits
	.global data_0885FF27
data_0885FF27:
	.incbin "data/residual/data_0885FF27.bin"
