@ data_087FB938: 20 bytes of raw JP ROM data at 0x087FB938..0x087FB94C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.087FB938, "a", %progbits
	.global data_087FB938
data_087FB938:
	@ de-pointered (scripts/repoint_table.py): ptr=4 data=1 skip=0
	.4byte AnimSprite_EfxMaohFlashEyeFire2Obj1_9 + 0x1
	.4byte AnimSprite_EfxMaohFlashEyeFire2Obj1_10 + 0x1
	.4byte AnimSprite_EfxMaohFlashEyeFire2Obj1_11 + 0x1
	.4byte AnimSprite_EfxMaohFlashEyeFire2Obj1_12 + 0x2
	.4byte 0x81000000
