@ data_08C01928: 1752 bytes of raw JP ROM data at 0x08C01928..0x08C02000,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08C01928, "a", %progbits
	.global data_08C01928
data_08C01928:
	.incbin "baserom.gba", 0xC01928, 0x6D8
