@ data_08A71BF0: 16 bytes of raw JP ROM data at 0x08A71BF0..0x08A71C00,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A71BF0, "a", %progbits
	.global EventScr_Ruin_55
EventScr_Ruin_55:
	.incbin "data/residual/data_08A71BF0.bin"
