@ data_08A5D40C: 88 bytes of raw JP ROM data at 0x08A5D40C..0x08A5D464,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5D40C, "a", %progbits
	.global data_08A5D40C
data_08A5D40C:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=17 skip=4
	.4byte 0x00110B0B
	.4byte 0x00000000
	.4byte 0x0009000B
	.4byte 0x08A6F774
	.4byte 0x0D190011
	.4byte 0x000B000B
	.4byte 0x08A6F7C8
	.4byte 0x06100007
	.4byte 0x000D000B
	.4byte 0x08A6F850
	.4byte 0x14100F07
	.4byte 0x000F000B
	.4byte 0x08A6F8D8
	.4byte 0x0E100707
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
