@ data_0890A6A8: 136 bytes of raw JP ROM data at 0x0890A6A8..0x0890A730,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0890A6A8, "a", %progbits
	.global data_0890A6A8
data_0890A6A8:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=33 skip=0
	.4byte 0x0D002343
	.4byte 0x01000341
	.4byte data_0890A480 + 0x7C
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x01000003
	.4byte 0x00000000
	.4byte 0x00000083
	.4byte 0x0000FFFF
	.4byte 0x00000084
	.4byte 0x0000FFFF
	.4byte 0x000001C4
	.4byte 0x0000FFFF
	.4byte 0x000001C5
	.4byte 0x0000FFFF
	.4byte 0x00000003
	.4byte 0x0000FFFF
	.4byte 0x00000083
	.4byte 0x0000FFFF
	.4byte 0x00000084
	.4byte 0x0000FFFF
	.4byte 0x00000204
	.4byte 0x0000FFFF
	.4byte 0x000002C3
	.4byte 0x0000FFFF
	.4byte 0x00000242
	.4byte 0x0000FFFF
	.4byte 0x00000342
	.4byte 0x0000FFFF
