@ data_08540B63: 360 bytes of raw JP ROM data at 0x08540B63..0x08540CCB,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08540B63, "a", %progbits
	.global data_08540B63
data_08540B63:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=88 skip=0
	.4byte 0x866843D5
	.4byte 0x42862043
	.4byte 0x20428668
	.4byte 0x86684386
	.4byte 0xE9862043
	.4byte 0xD59A6845
	.4byte 0xE7862045
	.4byte 0xB4986843
	.4byte 0x478647D5
	.4byte 0x68458620
	.4byte 0x86204586
	.4byte 0x43866843
	.4byte 0x42E98620
	.4byte 0x42D59A68
	.4byte 0x3EDB8620
	.4byte 0x3BD58C68
	.4byte 0xB3863E86
	.4byte song012_agbfe3_bgm_map_pl11_5_024
	.4byte 0x540B42B3
	.4byte 0x0B63B308
	.4byte 0x47D50854
	.4byte 0x20478668
	.4byte 0x86684586
	.4byte 0x43862045
	.4byte 0x20438668
	.4byte 0x6842E986
	.4byte 0x2042D59A
	.4byte 0x683EDB86
	.4byte 0x8639D58C
	.4byte 0x863E863C
	.4byte 0x3C86203E
	.4byte 0x203C8668
	.4byte 0x86683E86
	.4byte 0xE986203E
	.4byte 0xD59A6840
	.4byte 0xE7862040
	.4byte 0xD598683C
	.4byte 0x203E863E
	.4byte 0x86683C86
	.4byte 0x3E86203C
	.4byte 0x203E8668
	.4byte 0x6840E986
	.4byte 0x2040D59A
	.4byte 0x6841E786
	.4byte 0x4186D598
	.4byte 0x68408620
	.4byte 0x86204086
	.4byte 0x41866841
	.4byte 0x43E98620
	.4byte 0x43D59A68
	.4byte 0x41E78620
	.4byte 0x45D59868
	.4byte 0x86204586
	.4byte 0x43866843
	.4byte 0x68418620
	.4byte 0x86204186
	.4byte 0x9A6840E9
	.4byte 0x862040D5
	.4byte 0x8C683CDB
	.4byte 0x40863ED5
	.4byte 0x41864186
	.4byte 0x683F8620
	.4byte 0x86203F86
	.4byte 0x41866841
	.4byte 0x43E98620
	.4byte 0x43D59A68
	.4byte 0x3FE78620
	.4byte 0x41D59868
	.4byte 0x86204186
	.4byte 0x3F86683F
	.4byte 0x68418620
	.4byte 0x86204186
	.4byte 0x9A6843E9
	.4byte 0x862043D5
	.4byte 0x986844E7
	.4byte 0x204486D5
	.4byte 0x86684386
	.4byte 0x44862043
	.4byte 0x20448668
	.4byte 0x6846E986
	.4byte 0x2046D59A
	.4byte 0x6844E786
	.4byte 0x8648D598
	.4byte 0x46862048
	.4byte 0x20468668
	.4byte 0x86684486
	.4byte 0xEF862044
	.4byte 0xD5A06843
	.4byte 0xB28C2043
	.4byte song012_agbfe3_bgm_map_pl11_5_B1
