@ data_08A5AFE4: 40 bytes of raw JP ROM data at 0x08A5AFE4..0x08A5B00C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5AFE4, "a", %progbits
	.global data_08A5AFE4
data_08A5AFE4:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=7 skip=2
	.4byte 0x00000002
	.4byte EventScr_Ch8_0
	.4byte 0x00000202
	.4byte 0x000C0002
	.4byte 0x08A65384
	.4byte 0x0000FF01
	.4byte 0x00000002
	.4byte 0x08A6539C
	.4byte 0x00000005
	.4byte 0x00000000
