@ EventScr_GameOver: 60 bytes of raw JP ROM data at 0x085B9EE8..0x085B9F24,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.085B9EE8, "a", %progbits
	.global EventScr_GameOver
EventScr_GameOver:
	.incbin "data/residual/EventScr_GameOver.bin"
