@ data_0857DCB4: 504 bytes of raw JP ROM data at 0x0857DCB4..0x0857DEAC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0857DCB4, "a", %progbits
	.global data_0857DCB4
data_0857DCB4:
	.incbin "baserom.gba", 0x57DCB4, 0x1F8
