@ data_0890915C: 80 bytes of raw JP ROM data at 0x0890915C..0x089091AC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0890915C, "a", %progbits
	.global data_0890915C
data_0890915C:
	@ de-pointered (scripts/repoint_table.py): ptr=3 data=17 skip=0
	.4byte 0x10004413
	.4byte 0x03000289
	.4byte REDA_Ch4Ally_1_ARTUR
	.4byte 0x00006C3F
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte _RestoreBgm
	.4byte 0x010002C1
	.4byte REDA_Ch4Ally_2_LUTE
	.4byte 0x00006C38
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
