@ data_08A5A910: 76 bytes of raw JP ROM data at 0x08A5A910..0x08A5A95C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5A910, "a", %progbits
	.global data_08A5A910
data_08A5A910:
	@ de-pointered (scripts/repoint_table.py): ptr=4 data=14 skip=1
	.4byte 0x00000002
	.4byte EventScr_Ch2_Turn1Player
	.4byte 0x00000001
	.4byte 0x00000002
	.4byte EventScr_Ch2_Turn2Player
	.4byte 0x00000002
	.4byte 0x00000002
	.4byte 0x08A62880
	.4byte 0x00000003
	.4byte 0x00000000
	.4byte 0x00070003
	.4byte EventScr_Ch2_Talk_EirikaRoss
	.4byte 0x00000701
	.4byte 0x00000000
	.4byte 0x00080003
	.4byte EventScr_Ch2_Talk_RossGarcia
	.4byte 0x00000A07
	.4byte 0x00000000
	.4byte 0x00000000
