@ data_0890D0CC: 60 bytes of raw JP ROM data at 0x0890D0CC..0x0890D108,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0890D0CC, "a", %progbits
	.global data_0890D0CC
data_0890D0CC:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=13 skip=0
	.4byte 0x50000201
	.4byte 0x01000003
	.4byte data_0890C9BC + 0x94
	.4byte 0x006C6C17
	.4byte 0x00000000
	.4byte 0x50000702
	.4byte 0x01000003
	.4byte data_0890C9BC + 0x9C
	.4byte 0x006C6C17
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
