@ data_085E62D0: 232 bytes of raw JP ROM data at 0x085E62D0..0x085E63B8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.085E62D0, "a", %progbits
	.global data_085E62D0
data_085E62D0:
	@ de-pointered (scripts/repoint_table.py): ptr=48 data=10 skip=0
	.4byte gEfxlvupfx_0 + 0x1
	.4byte gEfxlvupfx_0 + 0x25
	.4byte gEfxlvupfx_0 + 0x49
	.4byte gEfxlvupfx_0 + 0x85
	.4byte gEfxlvupfx_0 + 0xC1
	.4byte gEfxlvupfx_0 + 0x115
	.4byte gEfxlvupfx_0 + 0x169
	.4byte gEfxlvupfx_0 + 0x1BD
	.4byte gEfxlvupfx_0 + 0x211
	.4byte gEfxlvupfx_0 + 0x259
	.4byte gEfxlvupfx_0 + 0x2AD
	.4byte gEfxlvupfx_0 + 0x2F5
	.4byte gEfxlvupfx_0 + 0x33D
	.4byte gEfxlvupfx_0 + 0x379
	.4byte gEfxlvupfx_0 + 0x3B5
	.4byte gEfxlvupfx_0 + 0x3E5
	.4byte gEfxlvupfx_0 + 0x42D
	.4byte gEfxlvupfx_0 + 0x475
	.4byte gEfxlvupfx_0 + 0x4BD
	.4byte gEfxlvupfx_0 + 0x505
	.4byte gEfxlvupfx_0 + 0x54D
	.4byte gEfxlvupfx_0 + 0x595
	.4byte gEfxlvupfx_0 + 0x5DD
	.4byte gEfxlvupfx_0 + 0x625
	.4byte 0x785E5B9B
	.4byte 0x84000013
	.4byte 0x80000000
	.4byte 0x285E5BD6
	.4byte gEfxlvupfx_0 + 0x6CF
	.4byte gEfxlvupfx_0 + 0x6F3
	.4byte 0x285E5C42
	.4byte gEfxlvupfx_0 + 0x6F3
	.4byte gEfxlvupfx_0 + 0x6CF
	.4byte 0x80000000
	.4byte gEfxlvupfx_0 + 0x73A
	.4byte gEfxlvupfx_0 + 0x7A6
	.4byte gEfxlvupfx_0 + 0x812
	.4byte gEfxlvupfx_0 + 0x87E
	.4byte gEfxlvupfx_0 + 0x8EA
	.4byte gEfxlvupfx_0 + 0x956
	.4byte gEfxlvupfx_0 + 0x9C2
	.4byte gEfxlvupfx_0 + 0xA2E
	.4byte gEfxlvupfx_0 + 0xA9A
	.4byte gEfxlvupfx_0 + 0xB06
	.4byte gEfxlvupfx_0 + 0xB72
	.4byte 0x80000000
	.4byte gEfxlvupfx_0 + 0xBDD
	.4byte gEfxlvupfx_0 + 0xC01
	.4byte gEfxlvupfx_0 + 0xC25
	.4byte gEfxlvupfx_0 + 0xC56
	.4byte gEfxlvupfx_0 + 0xC86
	.4byte gEfxlvupfx_0 + 0xCB7
	.4byte gEfxlvupfx_0 + 0xC86
	.4byte gEfxlvupfx_0 + 0xCE6
	.4byte gEfxlvupfx_0 + 0xD15
	.4byte 0x685E6270
	.4byte 0x285E62A0
	.4byte 0x80000000
