@ data_085CBFA4: 64 bytes of raw JP ROM data at 0x085CBFA4..0x085CBFE4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.085CBFA4, "a", %progbits
	.global data_085CBFA4
data_085CBFA4:
	.incbin "baserom.gba", 0x5CBFA4, 0x40
