@ data_087AA068: 28 bytes of raw JP ROM data at 0x087AA068..0x087AA084,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.087AA068, "a", %progbits
	.global data_087AA068
data_087AA068:
	@ de-pointered (scripts/repoint_table.py): ptr=5 data=2 skip=0
	.4byte AnimSprite_Tri_0 + 0x1
	.4byte AnimSprite_Tri_1 + 0x2
	.4byte AnimSprite_Tri_2 + 0x1
	.4byte AnimSprite_Tri_3 + 0x1
	.4byte AnimSprite_Tri_4 + 0x3
	.4byte 0x287A9F92
	.4byte 0x80000000
