@ data_08A9BD9C: 232 bytes of raw JP ROM data at 0x08A9BD9C..0x08A9BE84,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A9BD9C, "a", %progbits
	.global data_08A9BD9C
data_08A9BD9C:
	.incbin "baserom.gba", 0xA9BD9C, 0xE8
