@ data_0853D31C: 236 bytes of raw JP ROM data at 0x0853D31C..0x0853D408,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0853D31C, "a", %progbits
	.global data_0853D31C
data_0853D31C:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=50 skip=7
	.4byte 0x5426D3A4
	.4byte 0xD384D384
	.4byte 0x6C26DB84
	.4byte 0x1CB3B498
	.4byte 0xDB0853D3
	.4byte 0xDB986C26
	.4byte 0xDB8CDB98
	.4byte 0xD58CDB8C
	.4byte 0xDB86D586
	.4byte 0x382AD598
	.4byte 0xD598D598
	.4byte 0x382AD598
	.4byte 0xD598D598
	.4byte 0xD58CD598
	.4byte 0x2AD5B48C
	.4byte 0x98D59838
	.4byte 0x98D598D5
	.4byte 0xD598D5B4
	.4byte 0xD598D598
	.4byte 0x86182A86
	.4byte 0x8C342EDB
	.4byte 0x53D356B3
	.4byte 0xD349B308
	.4byte 0x56B30853
	.4byte 0xD50853D3
	.4byte 0xD598382A
	.4byte 0xD598D598
	.4byte 0x2A86D58C
	.4byte 0xDB8C8618
	.4byte 0xD58C202E
	.4byte 0xDB9C382A
	.4byte 0xD58C202E
	.4byte 0x2A8C382A
	.4byte 0x8CB48C1C
	.4byte 0x8C202EDB
	.4byte 0x9C382AD5
	.4byte 0x843036D3
	.4byte 0x36843836
	.4byte 0x36D58444
	.4byte 0x1C368C50
	.4byte 0x8EB3B48C
	.4byte 0xB30853D3
	.4byte 0x0853D3A3
	.4byte 0x4C32ED98
	.4byte 0xE78CDBA4
	.4byte 0xE7A0E798
	.4byte 0xDBACED98
	.4byte 0xEDA0ED8C
	.4byte 0xD14FB2A0
	.4byte 0x00B10853
	.4byte 0x940A0007
	.4byte frontier_df3_voicegroup_003_2038C4
	.4byte 0x0853BB64
	.4byte 0x0853C1EA
	.4byte 0x0853C39B
	.4byte 0x0853C86C
	.4byte 0x0853CBC6
	.4byte 0x0853CE8D
	.4byte song009_agbfe3_bgm_map_pl2_7
