@ data_08575580: 24 bytes of raw JP ROM data at 0x08575580..0x08575598,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08575580, "a", %progbits
	.global data_08575580
data_08575580:
	@ de-pointered (scripts/repoint_table.py): ptr=5 data=1 skip=0
	.4byte 0x00140004
	.4byte voicegroup038
	.4byte song944_btl_snr_magic2_2_1
	.4byte song944_btl_snr_magic2_2_2
	.4byte song944_btl_snr_magic2_2_3
	.4byte song944_btl_snr_magic2_2_4
