@ data_0856F374: 308 bytes of raw JP ROM data at 0x0856F374..0x0856F4A8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0856F374, "a", %progbits
	.global data_0856F374
data_0856F374:
	@ de-pointered (scripts/repoint_table.py): ptr=10 data=59 skip=8
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte song276_se_btl_reserve2_1_1
	.4byte 0x4BBB00BC
	.4byte 0x7FBE23BD
	.4byte 0x927F3CDD
	.4byte 0x86383AD4
	.4byte 0x3D86583C
	.4byte 0x3CD58638
	.4byte 0x3ED28768
	.4byte 0x3CDB8534
	.4byte 0x443E8C54
	.4byte 0x0000B18C
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F380
	.4byte 0x4BBB00BC
	.4byte 0x7FBE3DBD
	.4byte 0x987F3CF7
	.4byte 0x00B19898
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F3B4
	.4byte 0x4BBB00BC
	.4byte 0x78BE25BD
	.4byte 0x987F3CF3
	.4byte 0x00B19898
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F3D0
	.4byte 0x4BBB00BC
	.4byte 0x6EBE26BD
	.4byte 0x987F3CFF
	.4byte 0xB1989898
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F3EC
	.4byte 0x4BBB00BC
	.4byte 0x58BE07BD
	.4byte 0x987F3CEE
	.4byte 0x0000B198
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F408
	.4byte 0x4BBB00BC
	.4byte 0x60BE39BD
	.4byte 0x3CF408C1
	.4byte 0xBE92987F
	.4byte 0x82428250
	.4byte 0x822A8235
	.4byte 0x82178220
	.4byte 0x820A8210
	.4byte 0x82028206
	.4byte 0x00B18A00
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F424
	.4byte 0x4BBB00BC
	.4byte 0x3EBE30BD
	.4byte 0x817F3CFF
	.4byte 0x4E8146BE
	.4byte 0x5E815681
	.4byte 0x98936481
	.4byte 0xB1989898
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F458
	.4byte 0x4BBB00BC
	.4byte 0x38BE31BD
	.4byte 0x817F3CFF
	.4byte 0x46813FBE
	.4byte 0x55814D81
	.4byte 0x98935A81
	.4byte 0x00B19898
	.4byte 0x00140001
	.4byte voicegroup033
	.4byte 0x0856F480
