@ data_086A328C: 460 bytes of raw JP ROM data at 0x086A328C..0x086A3458,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086A328C, "a", %progbits
	.global data_086A328C
data_086A328C:
	.incbin "data/residual/data_086A328C.bin"
