@ ProcScr_efxDarkGradoOBJ01piece: 216 bytes of raw JP ROM data at 0x08602D54..0x08602E2C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08602D54, "a", %progbits
	.global ProcScr_efxDarkGradoOBJ01piece
ProcScr_efxDarkGradoOBJ01piece:
	.incbin "data/residual/ProcScr_efxDarkGradoOBJ01piece.bin"
