@ data_08A66110: 60 bytes of raw JP ROM data at 0x08A66110..0x08A6614C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A66110, "a", %progbits
	.global EventScr_Ch9A_3
EventScr_Ch9A_3:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=13 skip=0
	.4byte 0x00001520
	.4byte 0x00020540
	.4byte 0x00000000
	.4byte 0x00030540
	.4byte 0x000009EB
	.4byte 0x00000A40
	.4byte data_08A60354 + 0xF4
	.4byte 0x00001521
	.4byte 0x00000A40
	.4byte data_085B9BBC + 0x168
	.4byte 0x00030540
	.4byte 0x00000009
	.4byte 0xFFFF3720
	.4byte 0x00070228
	.4byte 0x00000120
