@ data_0855133E: 429 bytes of raw JP ROM data at 0x0855133E..0x085514EB,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0855133E, "a", %progbits
	.global data_0855133E
data_0855133E:
	.incbin "baserom.gba", 0x55133E, 0x1AD
