@ data_08A612F4: 244 bytes of raw JP ROM data at 0x08A612F4..0x08A613E8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A612F4, "a", %progbits
	.global data_08A612F4
data_08A612F4:
	@ de-pointered (scripts/repoint_table.py): ptr=9 data=49 skip=3
	.4byte 0x60003D20
	.4byte 0x00660229
	.4byte 0x00E00229
	.4byte 0x00E10229
	.4byte 0x00040229
	.4byte 0x000D0540
	.4byte 0x00000000
	.4byte 0x00010540
	.4byte 0x00020000
	.4byte 0x00000721
	.4byte 0x00010540
	.4byte 0x00000001
	.4byte 0x00000721
	.4byte 0x00010540
	.4byte 0x00000001
	.4byte 0x00000721
	.4byte 0x00010540
	.4byte 0xFFFFFFFF
	.4byte 0x00000721
	.4byte 0x00003F42
	.4byte 0x00000000
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte data_08A611DC
	.4byte 0x00000A40
	.4byte EventScr_CallOnTutorialMode
	.4byte 0x00020540
	.4byte 0x08A614EC
	.4byte 0x00000A40
	.4byte EventScr_CallOnTutorialMode
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte EventScr_Prologue_TutMessageTurn2
	.4byte 0x00000A40
	.4byte EventScr_CallOnTutorialMode
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte 0x08A61748
	.4byte 0x00000A40
	.4byte EventScr_CallOnTutorialMode
	.4byte 0x00020540
	.4byte EventScr_Prologue_TutEirikaAttack
	.4byte 0x00000A40
	.4byte EventScr_CallOnTutorialMode
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00001A23
	.4byte 0x000B0540
	.4byte 0xFFFFFFFF
	.4byte 0x08D91B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00013B25
	.4byte 0x003C0E20
	.4byte 0x00003B22
	.4byte 0x00020B41
	.4byte EventScr_Prologue_Tutorial0
	.4byte 0x00070228
	.4byte 0x00000121
