@ data_08908790: 196 bytes of raw JP ROM data at 0x08908790..0x08908854,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08908790, "a", %progbits
	.global data_08908790
data_08908790:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=47 skip=0
	.4byte 0x0A0005C1
	.4byte 0x03000082
	.4byte REDA_Ch1_NpcCavalier
	.4byte 0x00000014
	.4byte 0x00000000
	.4byte 0x0A000FC0
	.4byte 0x01000082
	.4byte REDA_Ch1_NpcMercenary
	.4byte 0x00000001
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000082
	.4byte 0x0000FFFF
	.4byte 0x00000040
	.4byte 0x0000FFFF
	.4byte 0x00000041
	.4byte 0x0000FFFF
	.4byte 0x000000C0
	.4byte 0x0000FFFF
	.4byte 0x000000C3
	.4byte 0x0000FFFF
	.4byte 0x0000030A
	.4byte 0x0000FFFF
	.4byte 0x0000024E
	.4byte 0x0000FFFF
	.4byte 0x000001CD
	.4byte 0x0000FFFF
	.4byte 0x000002C6
	.4byte 0x0000FFFF
	.4byte 0x00000387
	.4byte 0x0000FFFF
	.4byte 0x0000014C
	.4byte 0x0000FFFF
	.4byte 0x00000107
	.4byte 0x0000FFFF
	.4byte 0x0000014A
	.4byte 0x0000FFFF
	.4byte 0x0000010A
	.4byte 0x0000FFFF
	.4byte 0x00000241
	.4byte 0x0000FFFF
	.4byte 0x00000240
	.4byte 0x0000FFFF
	.4byte 0x000001CB
	.4byte 0x0000FFFF
