@ data_08A68F2C: 16 bytes of raw JP ROM data at 0x08A68F2C..0x08A68F3C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A68F2C, "a", %progbits
	.global data_08A68F2C
data_08A68F2C:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=3 skip=0
	.4byte 0x00000A40
	.4byte EventScr_Ch16A_12
	.4byte 0x00112A21
	.4byte 0x00000120
