@ data_081CC8FC: 352 bytes of raw JP ROM data at 0x081CC8FC..0x081CCA5C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.081CC8FC, "a", %progbits
	.global data_081CC8FC
data_081CC8FC:
	.incbin "baserom.gba", 0x1CC8FC, 0x160
