@ data_08A634E8: 24 bytes of raw JP ROM data at 0x08A634E8..0x08A63500,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A634E8, "a", %progbits
	.global EventScr_Ch3_Turn2Player
EventScr_Ch3_Turn2Player:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=4 skip=0
	.4byte 0x00020540
	.4byte EventScr_Ch3_7
	.4byte 0x00000A40
	.4byte EventScr_CallOnTutorialMode
	.4byte 0x00070228
	.4byte 0x00000120
