@ AnimScr_EfxSunakemuriOBJ3_L: 20 bytes of raw JP ROM data at 0x0861E61C..0x0861E630,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0861E61C, "a", %progbits
	.global AnimScr_EfxSunakemuriOBJ3_L
AnimScr_EfxSunakemuriOBJ3_L:
	.incbin "data/residual/AnimScr_EfxSunakemuriOBJ3_L.bin"
