@ data_086E24B4: 336 bytes of raw JP ROM data at 0x086E24B4..0x086E2604,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086E24B4, "a", %progbits
	.global data_086E24B4
data_086E24B4:
	.incbin "baserom.gba", 0x6E24B4, 0x150
