@ data_0856DAF4: 12 bytes of raw JP ROM data at 0x0856DAF4..0x0856DB00,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0856DAF4, "a", %progbits
	.global data_0856DAF4
data_0856DAF4:
	.incbin "baserom.gba", 0x56DAF4, 0xC
