@ data_08A5E3B8: 424 bytes of raw JP ROM data at 0x08A5E3B8..0x08A5E560,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5E3B8, "a", %progbits
	.global data_08A5E3B8
data_08A5E3B8:
	@ de-pointered (scripts/repoint_table.py): ptr=11 data=58 skip=37
	.4byte 0x00000000
	.4byte 0x08A5E354
	.4byte 0x08A5E364
	.4byte 0x08A5E368
	.4byte 0x08A5E36C
	.4byte 0x08A5E3AC
	.4byte 0x08A5E3B0
	.4byte 0x08A5E3B4
	.4byte data_08A5E3B8
	.4byte TrapData_Event_Ruin9_0
	.4byte 0x08A60029
	.4byte UnitDef_Ruin9Ally
	.4byte UnitDef_Ruin9Ally
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte frontier_df4_menu_011_A71268
	.4byte 0x08A712E0
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000005
	.4byte 0x08A5F8EA
	.4byte 0x00140209
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte 0x08A713E8
	.4byte 0x00000006
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x08A5E40C
	.4byte 0x08A5E410
	.4byte 0x08A5E414
	.4byte 0x08A5E424
	.4byte 0x08A5E440
	.4byte 0x08A5E444
	.4byte 0x08A5E448
	.4byte 0x08A5E44C
	.4byte frontier_df4_menu_005_A5FFAD
	.4byte 0x08A600A2
	.4byte UnitDef_Ruin10Ally
	.4byte UnitDef_Ruin10Ally
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x08A71374
	.4byte 0x08A713E8
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00030005
	.4byte 0x00000001
	.4byte 0x00110407
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x08A5E4A0
	.4byte 0x08A5E4A4
	.4byte 0x08A5E4A8
	.4byte 0x08A5E4B8
	.4byte 0x08A5E4C8
	.4byte 0x08A5E4CC
	.4byte 0x08A5E4D0
	.4byte 0x08A5E4D4
	.4byte 0x08A5FFAE
	.4byte 0x08A600A3
	.4byte 0x08924028
	.4byte 0x08924028
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x08A7140C
	.4byte 0x08A714E8
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte 0x08A71508
	.4byte 0x00000006
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
