@ UnitDef_Ch6Ally_2: 200 bytes of raw JP ROM data at 0x0890ADC0..0x0890AE88,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0890ADC0, "a", %progbits
	.global UnitDef_Ch6Ally_2
UnitDef_Ch6Ally_2:
	.incbin "data/residual/data_0890ADC0.bin"
