@ data_081F2D20: 344 bytes of raw JP ROM data at 0x081F2D20..0x081F2E78,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.081F2D20, "a", %progbits
	.global data_081F2D20
data_081F2D20:
	.incbin "baserom.gba", 0x1F2D20, 0x158
