@ AnimSprite_EfxReblowOBJ_L_27: 12 bytes of raw JP ROM data at 0x086A3BCC..0x086A3BD8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086A3BCC, "a", %progbits
	.global AnimSprite_EfxReblowOBJ_L_27
AnimSprite_EfxReblowOBJ_L_27:
	.incbin "data/residual/data_086A3BCC.bin"
