@ data_086371AC: 400 bytes of raw JP ROM data at 0x086371AC..0x0863733C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086371AC, "a", %progbits
	.global data_086371AC
data_086371AC:
	.incbin "data/residual/data_086371AC.bin"
