@ data_08A602D4: 28 bytes of raw JP ROM data at 0x08A602D4..0x08A602F0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A602D4, "a", %progbits
	.global EventScr_UnTriggerIfNotUnit
EventScr_UnTriggerIfNotUnit:
	.incbin "data/residual/data_08A602D4.bin"
