@ data_08BB8E94: 43884 bytes of raw JP ROM data at 0x08BB8E94..0x08BC3A00,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08BB8E94, "a", %progbits
	.global data_08BB8E94
data_08BB8E94:
	.incbin "baserom.gba", 0xBB8E94, 0xAB6C
