@ data_08A5A828: 152 bytes of raw JP ROM data at 0x08A5A828..0x08A5A8C0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5A828, "a", %progbits
	.global data_08A5A828
data_08A5A828:
	@ de-pointered (scripts/repoint_table.py): ptr=17 data=19 skip=2
	.4byte 0x00000005
	.4byte EventScr_Ch1_Loca_Visit1
	.4byte 0x0010060D
	.4byte 0x00000005
	.4byte EventScr_Ch1_Loca_Visit2
	.4byte 0x0010040A
	.4byte 0x00030005
	.4byte 0x00000001
	.4byte 0x00110202
	.4byte 0x00000000
	.4byte 0x00070001
	.4byte EventScr_Ch1_Misc_DefeatBoss
	.4byte 0x00000002
	.4byte 0x000A000B
	.4byte EventScr_Ch1_Misc_Area
	.4byte 0x09070000
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte EventScr_Ch1Tut_EirikaVisitHouseIdle1
	.4byte EventScr_Ch1Tut_EirikaVisitHouseIdle2
	.4byte EventScr_Ch1Tut_EirikaVisitHouseEnd
	.4byte EventScr_Ch1Tut_GuideTerrainHeal
	.4byte EventScr_Ch1Tut_TradeSelectGalliamIdle1
	.4byte EventScr_Ch1Tut_TradeSelectGalliamIdle2
	.4byte EventScr_Ch1Tut_TradeSelectGalliamEnd
	.4byte EventScr_Ch1Tut_AfterTrade
	.4byte EventScr_Ch1Tut_PostTradeAndItemUseAction
	.4byte EventScr_Ch1Tut_SethMoveToEnemy
	.4byte EventScr_Ch1Tut_BeforeSethMoveToEnemy
	.4byte data_08A62340
	.4byte 0x08A62374
	.4byte 0x08A623A8
	.4byte 0x00000000
