@ AnimScr_EfxSunakemuriOBJ3_R: 20 bytes of raw JP ROM data at 0x0861E578..0x0861E58C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0861E578, "a", %progbits
	.global AnimScr_EfxSunakemuriOBJ3_R
AnimScr_EfxSunakemuriOBJ3_R:
	.incbin "data/residual/AnimScr_EfxSunakemuriOBJ3_R.bin"
