@ data_0855F56E: 94 bytes of raw JP ROM data at 0x0855F56E..0x0855F5CC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0855F56E, "a", %progbits
	.global data_0855F56E
data_0855F56E:
	.incbin "data/residual/data_0855F56E.bin"
