@ AnimScr_efxSuperdruidOBJ: 36 bytes of raw JP ROM data at 0x087A2554..0x087A2578,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.087A2554, "a", %progbits
	.global AnimScr_efxSuperdruidOBJ
AnimScr_efxSuperdruidOBJ:
@ Live FORCE_SPRITE word at +0x8 is relocatable; surrounding bytes stay verbatim.
	.incbin "data/residual/AnimScr_efxSuperdruidOBJ.bin", 0, 0x8
	.4byte AnimSprite_efxSuperdruidOBJ_3 + 0x10000001
	.incbin "data/residual/AnimScr_efxSuperdruidOBJ.bin", 0xC, 0x18
