@ data_08A661E0: 240 bytes of raw JP ROM data at 0x08A661E0..0x08A662D0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A661E0, "a", %progbits
	.global data_08A661E0
data_08A661E0:
	@ de-pointered (scripts/repoint_table.py): ptr=8 data=44 skip=8
	.4byte 0x00000820
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch9AEnemy_2
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch9AEnemy_3
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch9AEnemy_4
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch9AEnemy_5
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch9AEnemy_6
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch9AEnemy_7
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte UnitDef_Ch9AEnemy_8
	.4byte 0x00000A40
	.4byte 0x08A603AC
	.4byte 0x00123B21
	.4byte 0x003C0E20
	.4byte 0x00003B22
	.4byte 0x00141420
	.4byte 0x00210E20
	.4byte 0x00001A20
	.4byte 0x09DF1B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00070228
	.4byte 0x00000120
	.4byte 0x00020540
	.4byte data_0890C6A8
	.4byte 0x00000A40
	.4byte 0x08A603D4
	.4byte 0x00070228
	.4byte 0x00000120
