@ data_087F9E98: 72 bytes of raw JP ROM data at 0x087F9E98..0x087F9EE0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.087F9E98, "a", %progbits
	.global data_087F9E98
data_087F9E98:
	.incbin "baserom.gba", 0x7F9E98, 0x48
