@ data_08A602D4: 28 bytes of raw JP ROM data at 0x08A602D4..0x08A602F0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A602D4, "a", %progbits
	.global EventScr_UnTriggerIfNotUnit
EventScr_UnTriggerIfNotUnit:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=6 skip=0
	.4byte 0x00002E21
	.4byte 0x00000C40
	.4byte 0x0002000C
	.4byte 0x00000A40
	.4byte UnitDef_Ch14BAlly_7 + 0x1C
	.4byte 0x00000820
	.4byte 0x00000120
