@ data_08A5AD4C: 44 bytes of raw JP ROM data at 0x08A5AD4C..0x08A5AD78,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5AD4C, "a", %progbits
	.global data_08A5AD4C
data_08A5AD4C:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=9 skip=0
	.4byte 0x00030001
	.4byte EventScr_Ch5_EndingScene
	.4byte 0x00000002
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
