@ data_086B7E10: 24 bytes of raw JP ROM data at 0x086B7E10..0x086B7E28,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086B7E10, "a", %progbits
	.global data_086B7E10
data_086B7E10:
	.incbin "data/residual/data_086B7E10.bin"
