@ data_08A625BC: 48 bytes of raw JP ROM data at 0x08A625BC..0x08A625EC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A625BC, "a", %progbits
	.global data_08A625BC
data_08A625BC:
	.incbin "baserom.gba", 0xA625BC, 0x30
