@ gWorldmapGmap_4: 32 bytes of raw JP ROM data at 0x08B1CCD4..0x08B1CCF4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08B1CCD4, "a", %progbits
	.global gWorldmapGmap_4
gWorldmapGmap_4:
	.incbin "data/residual/gWorldmapGmap_4.bin"
