@ data_08A60A28: 48 bytes of raw JP ROM data at 0x08A60A28..0x08A60A58,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A60A28, "a", %progbits
	.global EventScr_9EE8F0
EventScr_9EE8F0:
	@ de-pointered (scripts/repoint_table.py): ptr=2 data=10 skip=0
	.4byte 0xFFFF0321
	.4byte 0x00000C41
	.4byte 0x0000000C
	.4byte 0x00000D40
	.4byte DisplayMapClearMapAnim + 0x1
	.4byte 0x00320620
	.4byte 0xFFFF2A21
	.4byte 0x00000D40
	.4byte StartRetreatProcessing + 0x1
	.4byte 0x00000121
	.4byte 0x00000820
	.4byte 0x00000120
