@ data_0857656C: 236 bytes of raw JP ROM data at 0x0857656C..0x08576658,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0857656C, "a", %progbits
	.global data_0857656C
data_0857656C:
	@ de-pointered (scripts/repoint_table.py): ptr=7 data=45 skip=7
	.4byte 0x00140003
	.4byte voicegroup038
	.4byte song967_mon_bgl_attack7_1
	.4byte song967_mon_bgl_attack7_2
	.4byte song967_mon_bgl_attack7_3
	.4byte 0x4BBB00BC
	.4byte 0x1DBE65BD
	.4byte 0x34D10CC1
	.4byte 0x4034837F
	.4byte 0x837F4B83
	.4byte 0x3A83304B
	.4byte 0x383A837F
	.4byte 0x00BCB182
	.4byte 0x5FBE58BD
	.4byte 0x40D40CC1
	.4byte 0x7FC0867F
	.4byte 0xC0814FDD
	.4byte 0x816A8175
	.4byte 0x814B8155
	.4byte 0x812B8140
	.4byte 0x81168120
	.4byte 0xBCB18500
	.4byte 0xBE67BD00
	.4byte 0xD10CC11D
	.4byte 0x34837F34
	.4byte 0x7F4B8340
	.4byte 0x83304B83
	.4byte 0x3A837F3A
	.4byte 0x00B18238
	.4byte 0x00140003
	.4byte voicegroup038
	.4byte 0x08576580
	.4byte 0x0857659E
	.4byte 0x085765C3
	.4byte 0x4BBB00BC
	.4byte 0x55BE64BD
	.4byte 0x31D10CC1
	.4byte 0x8233827F
	.4byte 0x82328237
	.4byte 0x822D8130
	.4byte 0xBD00BCB1
	.4byte 0xC155BE71
	.4byte 0x7F3CEB0C
	.4byte 0xBCB1829C
	.4byte 0xBE30BD00
	.4byte 0xEE0CC155
	.4byte 0xB19F7F48
	.4byte 0x00140003
	.4byte voicegroup038
	.4byte 0x085765F4
	.4byte 0x0857660D
	.4byte 0x0857661B
	.4byte 0x6EBE4BBB
	.4byte 0x00BC6BBD
	.4byte 0xB07F3CFF
	.4byte 0x000000B1
	.4byte 0x00140001
	.4byte voicegroup038
	.4byte 0x0857663C
