@ data_0857AC54: 360 bytes of raw JP ROM data at 0x0857AC54..0x0857ADBC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0857AC54, "a", %progbits
	.global data_0857AC54
data_0857AC54:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=85 skip=4
	.4byte 0x08585094
	.4byte 0x00000882
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x0000CC00
	.4byte 0x0003BB00
	.4byte 0x0003BAC0
	.4byte 0x0000EEFC
	.4byte 0x00003AAB
	.4byte 0x00003FBC
	.4byte 0x0000EAB0
	.4byte 0x0003BFAC
	.4byte 0x0003B0EC
	.4byte 0x0003B030
	.4byte 0x0000EF00
	.4byte 0x00003AC0
	.4byte 0x00000F00
	.4byte 0x00000000
	.4byte gFontgrp_354
	.4byte 0x00000882
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x0000CC00
	.4byte 0x0003BB00
	.4byte 0x0003BB00
	.4byte 0x0000CFC0
	.4byte 0x00000EBC
	.4byte 0x00003BEB
	.4byte 0x0000EC3C
	.4byte 0x0000EC00
	.4byte 0x0000EC00
	.4byte 0x0000EC00
	.4byte 0x00003BC0
	.4byte 0x00000EB0
	.4byte 0x000003C0
	.4byte 0x00000000
	.4byte 0x08580E34
	.4byte 0x00000782
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00003300
	.4byte 0x0000EEC0
	.4byte 0x0000EEFC
	.4byte 0x0000EAAB
	.4byte 0x00003EFC
	.4byte 0x000003B0
	.4byte 0x000000EC
	.4byte 0x000000EC
	.4byte 0x000000EC
	.4byte 0x000000EC
	.4byte 0x00000FB0
	.4byte 0x00003AC0
	.4byte 0x00000F00
	.4byte 0x00000000
	.4byte 0x085815CC
	.4byte 0x00000782
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00003300
	.4byte 0x0000EEF0
	.4byte 0x0000EEEC
	.4byte 0x000033EC
	.4byte 0x00003CEC
	.4byte 0x0000EBB0
	.4byte 0x00003EB0
	.4byte 0x0000036C
	.4byte 0x000000DB
	.4byte 0x0000003B
	.4byte 0x00003FFB
	.4byte 0x0000EAAC
	.4byte 0x00003FF0
	.4byte 0x00000000
	.4byte 0x0857EC2C
	.4byte 0x00000882
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x0000CC00
	.4byte 0x0003BB00
	.4byte 0x0003BB0C
	.4byte 0x0000EFFB
	.4byte 0x0003AABB
	.4byte 0x0000EFFB
	.4byte 0x0000EC3B
	.4byte 0x0000EF3B
	.4byte 0x0000EAFB
	.4byte 0x0000EFBB
	.4byte 0x0003AFBB
	.4byte 0x0000FAFB
	.4byte 0x00000F0C
	.4byte 0x00000000
