@ data_08A5D1E8: 72 bytes of raw JP ROM data at 0x08A5D1E8..0x08A5D230,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5D1E8, "a", %progbits
	.global data_08A5D1E8
data_08A5D1E8:
	@ de-pointered (scripts/repoint_table.py): ptr=6 data=0 skip=12
	.4byte 0x08A5D180
	.4byte 0x08A5D184
	.4byte 0x08A5D1D0
	.4byte 0x08A5D1D4
	.4byte 0x08A5D1D8
	.4byte 0x08A5D1DC
	.4byte 0x08A5FCB5
	.4byte 0x08A60014
	.4byte 0x0891CF68
	.4byte 0x0891CF68
	.4byte UnitDef_Ch17BAlly_1
	.4byte UnitDef_Ch17BAlly_2
	.4byte UnitDef_Ch17BAlly_3
	.4byte UnitDef_Ch17BEnemy_6
	.4byte UnitDef_Ch17BEnemy_7
	.4byte UnitDef_Ch17BEnemy_8
	.4byte 0x08A6F0E4
	.4byte 0x08A6F124
