@ data_0890C914: 8 bytes of raw JP ROM data at 0x0890C914..0x0890C91C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0890C914, "a", %progbits
	.global REDA_Ch9AAlly_3_TANA
REDA_Ch9AAlly_3_TANA:
	.incbin "data/residual/data_0890C914.bin"
