@ data_0867B54C: 320 bytes of raw JP ROM data at 0x0867B54C..0x0867B68C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0867B54C, "a", %progbits
	.global data_0867B54C
data_0867B54C:
	.incbin "baserom.gba", 0x67B54C, 0x140
