@ data_08908354: 100 bytes of raw JP ROM data at 0x08908354..0x089083B8,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08908354, "a", %progbits
	.global data_08908354
data_08908354:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=21 skip=3
	.4byte 0x08004E0F
	.4byte 0x030003C9
	.4byte data_08908228
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x0C000B6B
	.4byte 0x0100028D
	.4byte 0x08908240
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x0C004F40
	.4byte 0x010002CC
	.4byte 0x08908248
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
