@ data_0855F8C0: 36 bytes of raw JP ROM data at 0x0855F8C0..0x0855F8E4,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0855F8C0, "a", %progbits
	.global data_0855F8C0
data_0855F8C0:
	@ de-pointered (scripts/repoint_table.py): ptr=7 data=1 skip=1
	.4byte 0x940A0007
	.4byte 0x0820F8E8
	.4byte song061_bgm_sys_fase_cp_1
	.4byte song061_bgm_sys_fase_cp_2
	.4byte song061_bgm_sys_fase_cp_3
	.4byte song061_bgm_sys_fase_cp_4
	.4byte song061_bgm_sys_fase_cp_5
	.4byte song061_bgm_sys_fase_cp_6
	.4byte song061_bgm_sys_fase_cp_7
