@ data_08A62A14: 48 bytes of raw JP ROM data at 0x08A62A14..0x08A62A44,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A62A14, "a", %progbits
	.global EventScr_Ch2Tutorial3
EventScr_Ch2Tutorial3:
	.incbin "data/residual/data_08A62A14.bin"
