@ gChDAsset_230: 256 bytes of raw JP ROM data at 0x0819EADC..0x0819EBDC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0819EADC, "a", %progbits
	.global gChDAsset_230
gChDAsset_230:
	.incbin "data/residual/gChDAsset_230.bin"
