@ UnitDef_Ch4Ally_3: 60 bytes of raw JP ROM data at 0x089092B0..0x089092EC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.089092B0, "a", %progbits
	.global UnitDef_Ch4Ally_3
UnitDef_Ch4Ally_3:
	.incbin "data/residual/data_089092B0.bin"
