@ data_086BAB74: 380 bytes of raw JP ROM data at 0x086BAB74..0x086BACF0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.086BAB74, "a", %progbits
	.global data_086BAB74
data_086BAB74:
	.incbin "data/residual/data_086BAB74.bin"
