@ data_08A5AF38: 92 bytes of raw JP ROM data at 0x08A5AF38..0x08A5AF94,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A5AF38, "a", %progbits
	.global data_08A5AF38
data_08A5AF38:
	@ de-pointered (scripts/repoint_table.py): ptr=4 data=19 skip=0
	.4byte 0x00000002
	.4byte EventScr_Ch7_0
	.4byte 0x00800001
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00030005
	.4byte 0x00000001
	.4byte 0x00110409
	.4byte 0x00000005
	.4byte EventScr_Ch7_1
	.4byte 0x00100F01
	.4byte 0x00000005
	.4byte EventScr_Ch7_2
	.4byte 0x00101511
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte data_085B9EE8
	.4byte 0x00000065
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000000
