@ data_087E1A58: 328 bytes of raw JP ROM data at 0x087E1A58..0x087E1BA0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.087E1A58, "a", %progbits
	.global data_087E1A58
data_087E1A58:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=52 skip=29
	.4byte 0x40000000
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x087E1A59
	.4byte 0x80000000
	.4byte 0x00000001
	.4byte data_080ED67C
	.4byte 0x00000003
	.4byte 0x0807848D
	.4byte 0x00000003
	.4byte 0x080784A9
	.4byte 0x00000003
	.4byte 0x080784D1
	.4byte 0x00000003
	.4byte 0x0807850D
	.4byte 0x00000003
	.4byte 0x08078535
	.4byte 0x00000003
	.4byte 0x08078571
	.4byte 0x00000003
	.4byte 0x08078599
	.4byte 0x00000003
	.4byte 0x080785D5
	.4byte 0x00000003
	.4byte 0x080785FD
	.4byte 0x00000003
	.4byte 0x0807863D
	.4byte 0x00000003
	.4byte 0x0807866D
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte 0x080ED688
	.4byte 0x00000003
	.4byte 0x0807848D
	.4byte 0x0000000B
	.4byte 0x00000000
	.4byte 0x00000003
	.4byte 0x08078671
	.4byte 0x00000003
	.4byte 0x080786B1
	.4byte 0x0014000E
	.4byte 0x00000000
	.4byte 0x0001000B
	.4byte 0x00000000
	.4byte 0x00000003
	.4byte 0x080786F1
	.4byte 0x00000003
	.4byte 0x080786B1
	.4byte 0x0005000B
	.4byte 0x00000000
	.4byte 0x00000003
	.4byte 0x0807863D
	.4byte 0x00000003
	.4byte 0x0807866D
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte 0x080ED694
	.4byte 0x00000003
	.4byte 0x080787A1
	.4byte 0x00000003
	.4byte 0x08078801
	.4byte 0x00000003
	.4byte 0x08078821
	.4byte 0x00000003
	.4byte 0x08078885
	.4byte 0x00000000
	.4byte 0x00000000
	.4byte 0x00000001
	.4byte 0x080ED6A8
	.4byte 0x00000003
	.4byte 0x080788A5
	.4byte 0x00000003
	.4byte 0x080788D1
	.4byte 0x00000003
	.4byte 0x08078935
	.4byte 0x00000000
	.4byte 0x00000000
