@ data_08A61EAC: 52 bytes of raw JP ROM data at 0x08A61EAC..0x08A61EE0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08A61EAC, "a", %progbits
	.global EventScr_Ch1Tut_EirikaVisitHouseEnd
EventScr_Ch1Tut_EirikaVisitHouseEnd:
	@ de-pointered (scripts/repoint_table.py): ptr=1 data=12 skip=0
	.4byte 0x00070228
	.4byte 0x00001120
	.4byte 0x00001A23
	.4byte 0x000B0540
	.4byte 0x00380048
	.4byte 0x09011B20
	.4byte 0x00001D20
	.4byte 0x00001B22
	.4byte 0x00CF0229
	.4byte 0x010A1120
	.4byte 0x00010B41
	.4byte EventScr_Ch1Tut_GuideTerrainHeal
	.4byte 0x00000120
