@ data_081BAC98: 344 bytes of raw JP ROM data at 0x081BAC98..0x081BADF0,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.081BAC98, "a", %progbits
	.global data_081BAC98
data_081BAC98:
	.incbin "data/residual/data_081BAC98.bin"
