@ Tsa_OpAnimSaleh2: 212 bytes of raw JP ROM data at 0x08B7229C..0x08B72370,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08B7229C, "a", %progbits
	.global Tsa_OpAnimSaleh2
Tsa_OpAnimSaleh2:
	.incbin "data/residual/Tsa_OpAnimSaleh2.bin"
