@ data_08B3E1C8: 228 bytes of raw JP ROM data at 0x08B3E1C8..0x08B3E2AC,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.08B3E1C8, "a", %progbits
	.global data_08B3E1C8
data_08B3E1C8:
	.incbin "baserom.gba", 0xB3E1C8, 0xE4
