@ data_0890D554: 200 bytes of raw JP ROM data at 0x0890D554..0x0890D61C,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.0890D554, "a", %progbits
	.global data_0890D554
data_0890D554:
	.incbin "baserom.gba", 0x90D554, 0xC8
