@ Generated by scripts/gen_layout.py from layout/baseline_syms.tsv.
@ Typed symbols for baseline-resident code/data referenced by decompiled
@ source, so the linker resolves them at their JP address (Thumb BL gets
@ no interwork veneer). Do not edit by hand.

	.thumb

	.global crt0
	.type   crt0, %function
	.set    crt0, 0x080000C0

	.global memcpy
	.type   memcpy, %function
	.thumb_func
	.set    memcpy, 0x080D6908 + 1

	.global __modsi3
	.type   __modsi3, %function
	.thumb_func
	.set    __modsi3, 0x080D6690 + 1

	.global CpuFastSet
	.type   CpuFastSet, %function
	.thumb_func
	.set    CpuFastSet, 0x080D636C + 1

	.global IrqMain
	.set    IrqMain, 0x080000FC

	.global IntrMain_Buffer
	.set    IntrMain_Buffer, 0x03004100

	.global gIRQHandlers
	.set    gIRQHandlers, 0x03003090

	.global PrintDebugStringToBG
	.type   PrintDebugStringToBG, %function
	.thumb_func
	.set    PrintDebugStringToBG, 0x08003750 + 1

	.global gBuildDateTime
	.set    gBuildDateTime, 0x080DC110

	.global gYearProjectCreated
	.set    gYearProjectCreated, 0x080DC12C

	.global gPlaySt
	.set    gPlaySt, 0x0202BCEC

	.global GetUnit
	.type   GetUnit, %function
	.thumb_func
	.set    GetUnit, 0x08019108 + 1

	.global gSpellAssocData
	.set    gSpellAssocData, 0x08904164

	.global GetItemIndex
	.type   GetItemIndex, %function
	.thumb_func
	.set    GetItemIndex, 0x08017294 + 1

	.global gActiveUnit
	.set    gActiveUnit, 0x03004DF0

	.global gWorkingMovementScript
	.set    gWorkingMovementScript, 0x02033EF8

	.global GetFacingDirection
	.type   GetFacingDirection, %function
	.thumb_func
	.set    GetFacingDirection, 0x0807DD00 + 1

	.global SetAutoMuMoveScript
	.type   SetAutoMuMoveScript, %function
	.thumb_func
	.set    SetAutoMuMoveScript, 0x0807AB24 + 1

	.global ProcScr_WorldMapMain
	.set    ProcScr_WorldMapMain, 0x08AC1108

	.global gGMData
	.set    gGMData, 0x03005270

	.global AddGmPath
	.type   AddGmPath, %function
	.thumb_func
	.set    AddGmPath, 0x080C16FC + 1

	.global GmHideMuUnit
	.type   GmHideMuUnit, %function
	.thumb_func
	.set    GmHideMuUnit, 0x080C2C24 + 1

	.global GmMu_RemoveUnit
	.type   GmMu_RemoveUnit, %function
	.thumb_func
	.set    GmMu_RemoveUnit, 0x080C2B14 + 1

	.global GmShowMuUnit
	.type   GmShowMuUnit, %function
	.thumb_func
	.set    GmShowMuUnit, 0x080C2BAC + 1

	.global MapMU_SetUnitChar
	.type   MapMU_SetUnitChar, %function
	.thumb_func
	.set    MapMU_SetUnitChar, 0x080C333C + 1

	.global MapMU_SetUnitClass
	.type   MapMU_SetUnitClass, %function
	.thumb_func
	.set    MapMU_SetUnitClass, 0x080C3320 + 1

	.global MapRoute_BeginRouteTransition
	.type   MapRoute_BeginRouteTransition, %function
	.thumb_func
	.set    MapRoute_BeginRouteTransition, 0x080C10E0 + 1

	.global Proc_Find
	.type   Proc_Find, %function
	.thumb_func
	.set    Proc_Find, 0x08002DEC + 1

	.global gUnitArrayBlue
	.set    gUnitArrayBlue, 0x0202BE48

	.global ClearUnit
	.type   ClearUnit, %function
	.thumb_func
	.set    ClearUnit, 0x0801759C + 1

	.global CopyUnit
	.type   CopyUnit, %function
	.thumb_func
	.set    CopyUnit, 0x080175C4 + 1

	.global CpuSet
	.type   CpuSet, %function
	.thumb_func
	.set    CpuSet, 0x080D6370 + 1

	.global gGameClock
	.set    gGameClock, 0x03000010

	.global __udivsi3
	.type   __udivsi3, %function
	.thumb_func
	.set    __udivsi3, 0x080D67D0 + 1

	.global __umodsi3
	.type   __umodsi3, %function
	.thumb_func
	.set    __umodsi3, 0x080D6848 + 1

	.global _call_via_r3
	.type   _call_via_r3, %function
	.thumb_func
	.set    _call_via_r3, 0x080D65C8 + 1

	.global LoadGMMonsterRnState
	.type   LoadGMMonsterRnState, %function
	.thumb_func
	.set    LoadGMMonsterRnState, 0x080ABC10 + 1

	.global ReadSramFast
	.set    ReadSramFast, 0x03006790

	.global WriteSaveBlockInfo
	.type   WriteSaveBlockInfo, %function
	.thumb_func
	.set    WriteSaveBlockInfo, 0x080A79D8 + 1

	.global IsSramWorking
	.type   IsSramWorking, %function
	.thumb_func
	.set    IsSramWorking, 0x080A76F4 + 1

	.global GetNextSuspendSaveId
	.type   GetNextSuspendSaveId, %function
	.thumb_func
	.set    GetNextSuspendSaveId, 0x080AADE8 + 1

	.global GetSaveWriteAddr
	.type   GetSaveWriteAddr, %function
	.thumb_func
	.set    GetSaveWriteAddr, 0x080A7AA8 + 1

	.global GetGameClock
	.type   GetGameClock, %function
	.thumb_func
	.set    GetGameClock, 0x08000CD8 + 1

	.global WriteAndVerifySramFast
	.type   WriteAndVerifySramFast, %function
	.thumb_func
	.set    WriteAndVerifySramFast, 0x080D6548 + 1

	.global StoreRNStateToActionStruct
	.type   StoreRNStateToActionStruct, %function
	.thumb_func
	.set    StoreRNStateToActionStruct, 0x08031F38 + 1

	.global WriteSramFast
	.type   WriteSramFast, %function
	.thumb_func
	.set    WriteSramFast, 0x080D6420 + 1

	.global WritePermanentFlags
	.type   WritePermanentFlags, %function
	.thumb_func
	.set    WritePermanentFlags, 0x080A7B94 + 1

	.global WriteChapterFlags
	.type   WriteChapterFlags, %function
	.thumb_func
	.set    WriteChapterFlags, 0x080A7B74 + 1

	.global WriteSupplyItems
	.type   WriteSupplyItems, %function
	.thumb_func
	.set    WriteSupplyItems, 0x080A7C28 + 1

	.global WritePidStats
	.type   WritePidStats, %function
	.thumb_func
	.set    WritePidStats, 0x080A8CA8 + 1

	.global WriteChapterStats
	.type   WriteChapterStats, %function
	.thumb_func
	.set    WriteChapterStats, 0x080A8CCC + 1

	.global WriteTraps
	.type   WriteTraps, %function
	.thumb_func
	.set    WriteTraps, 0x080AAD88 + 1

	.global GetForceDisabledMenuItems
	.type   GetForceDisabledMenuItems, %function
	.thumb_func
	.set    GetForceDisabledMenuItems, 0x08050488 + 1

	.global WriteWorldMapStuff
	.type   WriteWorldMapStuff, %function
	.thumb_func
	.set    WriteWorldMapStuff, 0x080ABAC8 + 1

	.global SaveDungeonRecords
	.type   SaveDungeonRecords, %function
	.thumb_func
	.set    SaveDungeonRecords, 0x08037F78 + 1

	.global SaveDungeonState
	.type   SaveDungeonState, %function
	.thumb_func
	.set    SaveDungeonState, 0x08037F34 + 1

	.global GetEventSlotCounter
	.type   GetEventSlotCounter, %function
	.thumb_func
	.set    GetEventSlotCounter, 0x0800D850 + 1

	.global WriteSwappedSuspendSaveId
	.type   WriteSwappedSuspendSaveId, %function
	.thumb_func
	.set    WriteSwappedSuspendSaveId, 0x080AADF8 + 1

	.global gActionData
	.set    gActionData, 0x0203A954

	.global gGenericBuffer
	.set    gGenericBuffer, 0x02020188

	.global gUnitArrayRed
	.set    gUnitArrayRed, 0x0202CFB8

	.global gUnitArrayGreen
	.set    gUnitArrayGreen, 0x0202DDC8

	.global gBmSt
	.set    gBmSt, 0x0202BCAC

	.global GetSaveReadAddr
	.type   GetSaveReadAddr, %function
	.thumb_func
	.set    GetSaveReadAddr, 0x080A7B58 + 1

	.global SetGameTime
	.type   SetGameTime, %function
	.thumb_func
	.set    SetGameTime, 0x08000CE4 + 1

	.global LoadRNStateFromActionStruct
	.type   LoadRNStateFromActionStruct, %function
	.thumb_func
	.set    LoadRNStateFromActionStruct, 0x08031F48 + 1

	.global InitUnits
	.type   InitUnits, %function
	.thumb_func
	.set    InitUnits, 0x0801756C + 1

	.global ReadPidStats
	.type   ReadPidStats, %function
	.thumb_func
	.set    ReadPidStats, 0x080A8C60 + 1

	.global ReadChapterStats
	.type   ReadChapterStats, %function
	.thumb_func
	.set    ReadChapterStats, 0x080A8C8C + 1

	.global ReadSupplyItems
	.type   ReadSupplyItems, %function
	.thumb_func
	.set    ReadSupplyItems, 0x080A7CB0 + 1

	.global ReadPermanentFlags
	.type   ReadPermanentFlags, %function
	.thumb_func
	.set    ReadPermanentFlags, 0x080A7BDC + 1

	.global ReadChapterFlags
	.type   ReadChapterFlags, %function
	.thumb_func
	.set    ReadChapterFlags, 0x080A7BB4 + 1

	.global ReadTraps
	.type   ReadTraps, %function
	.thumb_func
	.set    ReadTraps, 0x080AADA4 + 1

	.global SetForceDisabledMenuItems
	.type   SetForceDisabledMenuItems, %function
	.thumb_func
	.set    SetForceDisabledMenuItems, 0x080504C8 + 1

	.global ReadWorldMapStuff
	.type   ReadWorldMapStuff, %function
	.thumb_func
	.set    ReadWorldMapStuff, 0x080ABB50 + 1

	.global LoadDungeonRecords
	.type   LoadDungeonRecords, %function
	.thumb_func
	.set    LoadDungeonRecords, 0x08037F90 + 1

	.global LoadDungeonState
	.type   LoadDungeonState, %function
	.thumb_func
	.set    LoadDungeonState, 0x08037F5C + 1

	.global SetEventSlotCounter
	.type   SetEventSlotCounter, %function
	.thumb_func
	.set    SetEventSlotCounter, 0x0800D844 + 1

	.global LoadSavedBonusClaimFlags
	.type   LoadSavedBonusClaimFlags, %function
	.thumb_func
	.set    LoadSavedBonusClaimFlags, 0x080A9C64 + 1

	.global SetBonusContentClaimFlags
	.type   SetBonusContentClaimFlags, %function
	.thumb_func
	.set    SetBonusContentClaimFlags, 0x080A9778 + 1

	.global GetLastSuspendSaveId
	.type   GetLastSuspendSaveId, %function
	.thumb_func
	.set    GetLastSuspendSaveId, 0x080AADC8 + 1

	.global ReadSaveBlockInfo
	.type   ReadSaveBlockInfo, %function
	.thumb_func
	.set    ReadSaveBlockInfo, 0x080A793C + 1

	.global ReadGameSavePlaySt
	.type   ReadGameSavePlaySt, %function
	.thumb_func
	.set    ReadGameSavePlaySt, 0x080A9C44 + 1

	.global GetCharacterData
	.type   GetCharacterData, %function
	.thumb_func
	.set    GetCharacterData, 0x0801913C + 1

	.global GetClassData
	.type   GetClassData, %function
	.thumb_func
	.set    GetClassData, 0x0801911C + 1

	.global gBmMapTerrain
	.set    gBmMapTerrain, 0x0202E4D8

	.global RefreshEntityBmMaps
	.type   RefreshEntityBmMaps, %function
	.thumb_func
	.set    RefreshEntityBmMaps, 0x08019ECC + 1

	.global RefreshUnitSprites
	.type   RefreshUnitSprites, %function
	.thumb_func
	.set    RefreshUnitSprites, 0x08027144 + 1

	.global AddTarget
	.type   AddTarget, %function
	.thumb_func
	.set    AddTarget, 0x08050630 + 1

	.global gBmMapUnit
	.set    gBmMapUnit, 0x0202E4D4

	.global gBmMapSize
	.set    gBmMapSize, 0x0202E4D0

	.global _call_via_r0
	.type   _call_via_r0, %function
	.thumb_func
	.set    _call_via_r0, 0x080D65BC + 1

	.global Proc_Break
	.type   Proc_Break, %function
	.thumb_func
	.set    Proc_Break, 0x08002DE4 + 1

	.global CALLARM_ColorFadeTick
	.type   CALLARM_ColorFadeTick, %function
	.thumb_func
	.set    CALLARM_ColorFadeTick, 0x080DC0EC + 1

	.global EnablePaletteSync
	.type   EnablePaletteSync, %function
	.thumb_func
	.set    EnablePaletteSync, 0x08001EE4 + 1

	.global gPaletteBuffer
	.set    gPaletteBuffer, 0x020228A8

	.global ColorFadeSetStepRange
	.type   ColorFadeSetStepRange, %function
	.thumb_func
	.set    ColorFadeSetStepRange, 0x080017C8 + 1

	.global ProcScr_FadeCore
	.set    ProcScr_FadeCore, 0x085C2528

	.global SetBlendConfig
	.type   SetBlendConfig, %function
	.thumb_func
	.set    SetBlendConfig, 0x08001DF0 + 1

	.global SetBlendTargetA
	.type   SetBlendTargetA, %function
	.thumb_func
	.set    SetBlendTargetA, 0x08001E20 + 1

	.global SetBlendBackdropA
	.type   SetBlendBackdropA, %function
	.thumb_func
	.set    SetBlendBackdropA, 0x08001E98 + 1

	.global gLCDControlBuffer
	.set    gLCDControlBuffer, 0x03003020

	.global GetStringFromIndex
	.type   GetStringFromIndex, %function
	.thumb_func
	.set    GetStringFromIndex, 0x08009FA8 + 1

	.global GetUnitFromCharId
	.type   GetUnitFromCharId, %function
	.thumb_func
	.set    GetUnitFromCharId, 0x08017FB0 + 1

	.global GetUnitSupporterNum
	.type   GetUnitSupporterNum, %function
	.thumb_func
	.set    GetUnitSupporterNum, 0x0802833C + 1

	.global Proc_Start
	.type   Proc_Start, %function
	.thumb_func
	.set    Proc_Start, 0x08002BCC + 1

	.global m4aSongNumStart
	.type   m4aSongNumStart, %function
	.thumb_func
	.set    m4aSongNumStart, 0x080D4EF4 + 1

	.global SetHelpBoxInitPosition_bug
	.type   SetHelpBoxInitPosition_bug, %function
	.thumb_func
	.set    SetHelpBoxInitPosition_bug, 0x0808C74C + 1

	.global SetHelpBoxDefaultRect
	.type   SetHelpBoxDefaultRect, %function
	.thumb_func
	.set    SetHelpBoxDefaultRect, 0x0808C754 + 1

	.global ProcScr_Helpbox_bug_0
	.set    ProcScr_Helpbox_bug_0, 0x08A73730

	.global SetTextFontGlyphs
	.type   SetTextFontGlyphs, %function
	.thumb_func
	.set    SetTextFontGlyphs, 0x08003C24 + 1

	.global GetStringTextBox
	.type   GetStringTextBox, %function
	.thumb_func
	.set    GetStringTextBox, 0x08003EC8 + 1

	.global ApplyHelpBoxPosition_bug
	.type   ApplyHelpBoxPosition_bug, %function
	.thumb_func
	.set    ApplyHelpBoxPosition_bug, 0x0808C6D4 + 1

	.global ClearHelpBoxText
	.type   ClearHelpBoxText, %function
	.thumb_func
	.set    ClearHelpBoxText, 0x0808C428 + 1

	.global StartHelpBoxTextInit
	.type   StartHelpBoxTextInit, %function
	.thumb_func
	.set    StartHelpBoxTextInit, 0x0808C40C + 1

	.global Proc_BreakEach
	.type   Proc_BreakEach, %function
	.thumb_func
	.set    Proc_BreakEach, 0x08002FE4 + 1

	.global _call_via_r1
	.type   _call_via_r1, %function
	.thumb_func
	.set    _call_via_r1, 0x080D65C0 + 1

	.global gKeyStatusPtr
	.set    gKeyStatusPtr, 0x085775CC

	.global Proc_End
	.type   Proc_End, %function
	.thumb_func
	.set    Proc_End, 0x08002CBC + 1

	.global gHelpbox_0
	.set    gHelpbox_0, 0x08A73750

	.global GetHelpBoxItemInfoKind_bug
	.type   GetHelpBoxItemInfoKind_bug, %function
	.thumb_func
	.set    GetHelpBoxItemInfoKind_bug, 0x0808C764 + 1

	.global Proc_Goto
	.type   Proc_Goto, %function
	.thumb_func
	.set    Proc_Goto, 0x08002E74 + 1

	.global gManimSt
	.set    gManimSt, 0x0203E1EC

	.global MapAnim_AdvanceBattleRound
	.type   MapAnim_AdvanceBattleRound, %function
	.thumb_func
	.set    MapAnim_AdvanceBattleRound, 0x0807CBF0 + 1

	.global Sound_SetSEVolume
	.type   Sound_SetSEVolume, %function
	.thumb_func
	.set    Sound_SetSEVolume, 0x0800223C + 1

	.global ProcScr_ekrLvupFan
	.set    ProcScr_ekrLvupFan, 0x085E3580

	.global EfxPlaySE
	.type   EfxPlaySE, %function
	.thumb_func
	.set    EfxPlaySE, 0x08073E74 + 1

	.global M4aPlayWithPostionCtrl
	.type   M4aPlayWithPostionCtrl, %function
	.thumb_func
	.set    M4aPlayWithPostionCtrl, 0x08073F94 + 1

	.global StartTemporaryLock
	.type   StartTemporaryLock, %function
	.thumb_func
	.set    StartTemporaryLock, 0x080142F0 + 1

	.global Decompress
	.type   Decompress, %function
	.thumb_func
	.set    Decompress, 0x08013008 + 1

	.global CopyToPaletteBuffer
	.type   CopyToPaletteBuffer, %function
	.thumb_func
	.set    CopyToPaletteBuffer, 0x08000D68 + 1

	.global APProc_Create
	.type   APProc_Create, %function
	.thumb_func
	.set    APProc_Create, 0x08009608 + 1

	.global Img_MineFx
	.set    Img_MineFx, 0x085D1BC8

	.global Pal_MineFx
	.set    Pal_MineFx, 0x085D1DD0

	.global SpritAnim_MineFx
	.set    SpritAnim_MineFx, 0x085D1D3C

	.global StartSpriteAnimfx
	.type   StartSpriteAnimfx, %function
	.thumb_func
	.set    StartSpriteAnimfx, 0x080B342C + 1

	.global SetDefaultColorEffects
	.type   SetDefaultColorEffects, %function
	.thumb_func
	.set    SetDefaultColorEffects, 0x08001ED0 + 1

	.global SetBackgroundTileDataOffset
	.type   SetBackgroundTileDataOffset, %function
	.thumb_func
	.set    SetBackgroundTileDataOffset, 0x08000F8C + 1

	.global BG_Fill
	.type   BG_Fill, %function
	.thumb_func
	.set    BG_Fill, 0x080011D0 + 1

	.global BG_EnableSyncByMask
	.type   BG_EnableSyncByMask, %function
	.thumb_func
	.set    BG_EnableSyncByMask, 0x08001EFC + 1

	.global gBG2TilemapBuffer
	.set    gBG2TilemapBuffer, 0x02023CA8

	.global SetAllUnitNotBackSprite
	.type   SetAllUnitNotBackSprite, %function
	.thumb_func
	.set    SetAllUnitNotBackSprite, 0x08018670 + 1

	.global UnlockGame
	.type   UnlockGame, %function
	.thumb_func
	.set    UnlockGame, 0x08015394 + 1

	.global RenderBmMap
	.type   RenderBmMap, %function
	.thumb_func
	.set    RenderBmMap, 0x08019914 + 1

	.global BG_SetPosition
	.type   BG_SetPosition, %function
	.thumb_func
	.set    BG_SetPosition, 0x08001448 + 1

	.global StartMu
	.type   StartMu, %function
	.thumb_func
	.set    StartMu, 0x0807A888 + 1

	.global StartMuExt
	.type   StartMuExt, %function
	.thumb_func
	.set    StartMuExt, 0x0807A84C + 1

	.global MuExistsActive
	.type   MuExistsActive, %function
	.thumb_func
	.set    MuExistsActive, 0x0807AB5C + 1

	.global EndMu
	.type   EndMu, %function
	.thumb_func
	.set    EndMu, 0x0807B4C8 + 1

	.global ForceSyncUnitSpriteSheet
	.type   ForceSyncUnitSpriteSheet, %function
	.thumb_func
	.set    ForceSyncUnitSpriteSheet, 0x08026F38 + 1

	.global GetBanimDragonStatusType
	.type   GetBanimDragonStatusType, %function
	.thumb_func
	.set    GetBanimDragonStatusType, 0x08072060 + 1

	.global ProcScr_efxSpellCast
	.set    ProcScr_efxSpellCast, 0x085E3C64

	.global gpProcEfxSpellCast
	.set    gpProcEfxSpellCast, 0x02017778

	.global gPal_Banim
	.set    gPal_Banim, 0x0201C790

	.global Interpolate
	.type   Interpolate, %function
	.thumb_func
	.set    Interpolate, 0x08012E84 + 1

	.global EfxPalBlackInOut
	.type   EfxPalBlackInOut, %function
	.thumb_func
	.set    EfxPalBlackInOut, 0x080737A4 + 1

	.global PlaySFX
	.type   PlaySFX, %function
	.thumb_func
	.set    PlaySFX, 0x08074E80 + 1

	.global NewEfxFlashBgWhite
	.type   NewEfxFlashBgWhite, %function
	.thumb_func
	.set    NewEfxFlashBgWhite, 0x08054BF8 + 1

	.global EfxPalWhiteInOut
	.type   EfxPalWhiteInOut, %function
	.thumb_func
	.set    EfxPalWhiteInOut, 0x08073820 + 1

	.global gEfxPal
	.set    gEfxPal, 0x020165C8

	.global SpellFx_ClearBG1
	.type   SpellFx_ClearBG1, %function
	.thumb_func
	.set    SpellFx_ClearBG1, 0x08056130 + 1

	.global SetDefaultColorEffects_
	.type   SetDefaultColorEffects_, %function
	.thumb_func
	.set    SetDefaultColorEffects_, 0x08056214 + 1

	.global gEfxBgSemaphore
	.set    gEfxBgSemaphore, 0x0201774C

	.global GetConvoyItemArray
	.type   GetConvoyItemArray, %function
	.thumb_func
	.set    GetConvoyItemArray, 0x0803144C + 1

	.global gpBgVerticalScrollSt
	.set    gpBgVerticalScrollSt, 0x03004930

	.global SetPrimaryHBlankHandler
	.type   SetPrimaryHBlankHandler, %function
	.thumb_func
	.set    SetPrimaryHBlankHandler, 0x08001D28 + 1

	.global GetCharTextLen
	.type   GetCharTextLen, %function
	.thumb_func
	.set    GetCharTextLen, 0x08003E6C + 1

	.global CallARM_FillTileRect
	.type   CallARM_FillTileRect, %function
	.thumb_func
	.set    CallARM_FillTileRect, 0x080DC0DC + 1

	.global gTsa_UnkData_0
	.set    gTsa_UnkData_0, 0x08A7DCB8

	.global GetROMChapterStruct
	.type   GetROMChapterStruct, %function
	.thumb_func
	.set    GetROMChapterStruct, 0x08034520 + 1

	.global GetPlayChapterId
	.type   GetPlayChapterId, %function
	.thumb_func
	.set    GetPlayChapterId, 0x080C1DE8 + 1

	.global GetNextUnclearedNode
	.type   GetNextUnclearedNode, %function
	.thumb_func
	.set    GetNextUnclearedNode, 0x080C1E20 + 1

	.global gWMMonsterSpawnsSize
	.type   gWMMonsterSpawnsSize, %function
	.thumb_func
	.set    gWMMonsterSpawnsSize, 0x081F661C + 1

	.global gWMMonsterSpawnLocations
	.set    gWMMonsterSpawnLocations, 0x081F6614

	.global SetBlendTargetB
	.type   SetBlendTargetB, %function
	.thumb_func
	.set    SetBlendTargetB, 0x08001E5C + 1

	.global Img_EventWarp
	.set    Img_EventWarp, 0x085CF274

	.global Pal_EventWarp
	.set    Pal_EventWarp, 0x085CF9BC

	.global Tsa_EventWarp
	.set    Tsa_EventWarp, 0x085CF9DC

	.global gUiTmScratchA
	.set    gUiTmScratchA, 0x02003D2C

	.global gBG0TilemapBuffer
	.set    gBG0TilemapBuffer, 0x02022CA8

	.global TileMap_CopyRect
	.type   TileMap_CopyRect, %function
	.thumb_func
	.set    TileMap_CopyRect, 0x080DC0F4 + 1

	.global RenderBmMapOnBg2
	.type   RenderBmMapOnBg2, %function
	.thumb_func
	.set    RenderBmMapOnBg2, 0x08019994 + 1

	.global NewBMXFADE
	.type   NewBMXFADE, %function
	.thumb_func
	.set    NewBMXFADE, 0x0801DA28 + 1

	.global BmMapFill
	.type   BmMapFill, %function
	.thumb_func
	.set    BmMapFill, 0x080194BC + 1

	.global SetWorkingBmMap
	.type   SetWorkingBmMap, %function
	.thumb_func
	.set    SetWorkingBmMap, 0x0801B668 + 1

	.global GetUnitMagBy2Range
	.type   GetUnitMagBy2Range, %function
	.thumb_func
	.set    GetUnitMagBy2Range, 0x08018730 + 1

	.global MapAddInBoundedRange
	.type   MapAddInBoundedRange, %function
	.thumb_func
	.set    MapAddInBoundedRange, 0x0801B674 + 1

	.global CanUnitCrossTerrain
	.type   CanUnitCrossTerrain, %function
	.thumb_func
	.set    CanUnitCrossTerrain, 0x08019174 + 1

	.global gBmMapMovement
	.set    gBmMapMovement, 0x0202E4DC

	.global gBmMapRange
	.set    gBmMapRange, 0x0202E4E0

	.global gBmMapFog
	.set    gBmMapFog, 0x0202E4E4

	.global GetBackgroundTileDataOffset
	.type   GetBackgroundTileDataOffset, %function
	.thumb_func
	.set    GetBackgroundTileDataOffset, 0x08000F3C + 1

	.global gBG3TilemapBuffer
	.set    gBG3TilemapBuffer, 0x020244A8

	.global Pal_CommGameBgScreenInShop
	.set    Pal_CommGameBgScreenInShop, 0x08BB059C

	.global Img_CommGameBgScreen
	.set    Img_CommGameBgScreen, 0x08BABE04

	.global ProcScr_SlidingWallBg
	.set    ProcScr_SlidingWallBg, 0x08A7279C

	.global FlushLCDControl
	.type   FlushLCDControl, %function
	.thumb_func
	.set    FlushLCDControl, 0x08000E4C + 1

	.global FlushBackgrounds
	.type   FlushBackgrounds, %function
	.thumb_func
	.set    FlushBackgrounds, 0x080010FC + 1

	.global FlushTiles
	.type   FlushTiles, %function
	.thumb_func
	.set    FlushTiles, 0x08001FD8 + 1

	.global m4aSoundVSync
	.type   m4aSoundVSync, %function
	.thumb_func
	.set    m4aSoundVSync, 0x080D4814 + 1

	.global m4aSoundMain
	.type   m4aSoundMain, %function
	.thumb_func
	.set    m4aSoundMain, 0x080D4EE8 + 1

	.global UpdateKeyStatus
	.type   UpdateKeyStatus, %function
	.thumb_func
	.set    UpdateKeyStatus, 0x0800139C + 1

	.global SoftReset
	.type   SoftReset, %function
	.thumb_func
	.set    SoftReset, 0x080D63AC + 1

	.global VBlankIntrWait
	.type   VBlankIntrWait, %function
	.thumb_func
	.set    VBlankIntrWait, 0x080D63D8 + 1

	.global GmMu_StartMoveBetweenNodes
	.type   GmMu_StartMoveBetweenNodes, %function
	.thumb_func
	.set    GmMu_StartMoveBetweenNodes, 0x080C2C9C + 1

	.global GmMu_StartMoveToPosition
	.type   GmMu_StartMoveToPosition, %function
	.thumb_func
	.set    GmMu_StartMoveToPosition, 0x080C2D8C + 1

	.global GmMu_IsMoving
	.type   GmMu_IsMoving, %function
	.thumb_func
	.set    GmMu_IsMoving, 0x080C2F14 + 1

	.global EndAllMus
	.type   EndAllMus, %function
	.thumb_func
	.set    EndAllMus, 0x0807B4B8 + 1

	.global SetAutoMuDefaultFacing
	.type   SetAutoMuDefaultFacing, %function
	.thumb_func
	.set    SetAutoMuDefaultFacing, 0x0807AB0C + 1

	.global GetUnitMu
	.type   GetUnitMu, %function
	.thumb_func
	.set    GetUnitMu, 0x0807BFCC + 1

	.global BeginUnitCritDamageAnim
	.type   BeginUnitCritDamageAnim, %function
	.thumb_func
	.set    BeginUnitCritDamageAnim, 0x08035A2C + 1

	.global ApplyHazardHealing
	.type   ApplyHazardHealing, %function
	.thumb_func
	.set    ApplyHazardHealing, 0x080358A8 + 1

	.global GetUnitCurrentHp
	.type   GetUnitCurrentHp, %function
	.thumb_func
	.set    GetUnitCurrentHp, 0x08018E64 + 1

	.global PidStatsRecordDefeatInfo
	.type   PidStatsRecordDefeatInfo, %function
	.thumb_func
	.set    PidStatsRecordDefeatInfo, 0x080A90C8 + 1

	.global CheckForWaitEvents
	.type   CheckForWaitEvents, %function
	.thumb_func
	.set    CheckForWaitEvents, 0x08086604 + 1

	.global RunWaitEvents
	.type   RunWaitEvents, %function
	.thumb_func
	.set    RunWaitEvents, 0x08086694 + 1

	.global gPromoJidLut
	.set    gPromoJidLut, 0x089CDD18

	.global MakePromotionScreen
	.type   MakePromotionScreen, %function
	.thumb_func
	.set    MakePromotionScreen, 0x080D1184 + 1

	.global BMapDispResume
	.type   BMapDispResume, %function
	.thumb_func
	.set    BMapDispResume, 0x08030108 + 1

	.global RefreshBMapGraphics
	.type   RefreshBMapGraphics, %function
	.thumb_func
	.set    RefreshBMapGraphics, 0x080310F4 + 1

	.global Proc_StartBlocking
	.type   Proc_StartBlocking, %function
	.thumb_func
	.set    Proc_StartBlocking, 0x08002C30 + 1

	.global gBattleActor
	.set    gBattleActor, 0x0203A4E8

	.global gBattleTarget
	.set    gBattleTarget, 0x0203A568

	.global GetUnitEquippedWeapon
	.type   GetUnitEquippedWeapon, %function
	.thumb_func
	.set    GetUnitEquippedWeapon, 0x080168D0 + 1

	.global BMapDispSuspend
	.type   BMapDispSuspend, %function
	.thumb_func
	.set    BMapDispSuspend, 0x080300D4 + 1

	.global EndCgText
	.type   EndCgText, %function
	.thumb_func
	.set    EndCgText, 0x08091544 + 1

	.global ResetDialogueScreen
	.type   ResetDialogueScreen, %function
	.thumb_func
	.set    ResetDialogueScreen, 0x08010F98 + 1

	.global APProc_DeleteAll
	.type   APProc_DeleteAll, %function
	.thumb_func
	.set    APProc_DeleteAll, 0x080096B0 + 1

	.global EndMuralBackground_
	.type   EndMuralBackground_, %function
	.thumb_func
	.set    EndMuralBackground_, 0x08097D18 + 1

	.global EndAllProcChildren
	.type   EndAllProcChildren, %function
	.thumb_func
	.set    EndAllProcChildren, 0x080B2874 + 1

	.global UnitUpdateUsedItem
	.type   UnitUpdateUsedItem, %function
	.thumb_func
	.set    UnitUpdateUsedItem, 0x080186A8 + 1

	.global gUnk_80
	.set    gUnk_80, 0x03005388

	.global MusicProc4Exists
	.type   MusicProc4Exists, %function
	.thumb_func
	.set    MusicProc4Exists, 0x080029BC + 1

	.global ClassChgExecPromotionReal
	.type   ClassChgExecPromotionReal, %function
	.thumb_func
	.set    ClassChgExecPromotionReal, 0x080D2AEC + 1

	.global ClassChgPostConfirmWaitBanimEnd
	.type   ClassChgPostConfirmWaitBanimEnd, %function
	.thumb_func
	.set    ClassChgPostConfirmWaitBanimEnd, 0x080D2B70 + 1

	.global __muldi3
	.type   __muldi3, %function
	.thumb_func
	.set    __muldi3, 0x080D6760 + 1

	.global gUisupport_1
	.set    gUisupport_1, 0x02014FE4

	.global UpdateAllPhaseHealingAIStatus
	.type   UpdateAllPhaseHealingAIStatus, %function
	.thumb_func
	.set    UpdateAllPhaseHealingAIStatus, 0x0803E5D0 + 1

	.global SetupUnitInventoryAIFlags
	.type   SetupUnitInventoryAIFlags, %function
	.thumb_func
	.set    SetupUnitInventoryAIFlags, 0x0803BFF4 + 1

	.global gAiItemConfigTable
	.set    gAiItemConfigTable, 0x080DD214

	.global gProcScr_CpOrder
	.set    gProcScr_CpOrder, 0x085D1E64

	.global gProcScr_BerserkCpOrder
	.set    gProcScr_BerserkCpOrder, 0x085D1E7C

	.global BG_GetMapBuffer
	.type   BG_GetMapBuffer, %function
	.thumb_func
	.set    BG_GetMapBuffer, 0x08001BC0 + 1

	.global PutSprite
	.type   PutSprite, %function
	.thumb_func
	.set    PutSprite, 0x080052F0 + 1

	.global RegisterDataMove
	.type   RegisterDataMove, %function
	.thumb_func
	.set    RegisterDataMove, 0x08001F64 + 1

	.global Proc_EndEach
	.type   Proc_EndEach, %function
	.thumb_func
	.set    Proc_EndEach, 0x08002FC8 + 1

	.global LetsEmitStars
	.type   LetsEmitStars, %function
	.thumb_func
	.set    LetsEmitStars, 0x08021F08 + 1

	.global gConvoBackgroundData
	.set    gConvoBackgroundData, 0x089CD958

	.global __divsi3
	.type   __divsi3, %function
	.thumb_func
	.set    __divsi3, 0x080D65F8 + 1

	.global UpdateStatArrowSprites
	.type   UpdateStatArrowSprites, %function
	.thumb_func
	.set    UpdateStatArrowSprites, 0x08015BF0 + 1

	.global GetUnitEquippedWeaponSlot
	.type   GetUnitEquippedWeaponSlot, %function
	.thumb_func
	.set    GetUnitEquippedWeaponSlot, 0x08016900 + 1

	.global InitTextDb
	.type   InitTextDb, %function
	.thumb_func
	.set    InitTextDb, 0x08003CB4 + 1

	.global LoadIconPalette
	.type   LoadIconPalette, %function
	.thumb_func
	.set    LoadIconPalette, 0x08003520 + 1

	.global BattleGenerateUiStats
	.type   BattleGenerateUiStats, %function
	.thumb_func
	.set    BattleGenerateUiStats, 0x0802A38C + 1

	.global GetStringTextLen
	.type   GetStringTextLen, %function
	.thumb_func
	.set    GetStringTextLen, 0x08003E0C + 1

	.global DrawUiFrame2
	.type   DrawUiFrame2, %function
	.thumb_func
	.set    DrawUiFrame2, 0x0804F0EC + 1

	.global ResetIconGraphics_
	.type   ResetIconGraphics_, %function
	.thumb_func
	.set    ResetIconGraphics_, 0x080034C4 + 1

	.global LoadIconPalettes
	.type   LoadIconPalettes, %function
	.thumb_func
	.set    LoadIconPalettes, 0x08003508 + 1

	.global DrawIcon
	.type   DrawIcon, %function
	.thumb_func
	.set    DrawIcon, 0x08003608 + 1

	.global ResetTextFont
	.type   ResetTextFont, %function
	.thumb_func
	.set    ResetTextFont, 0x08003C50 + 1

	.global PutDrawText
	.type   PutDrawText, %function
	.thumb_func
	.set    PutDrawText, 0x08004374 + 1

	.global InitText
	.type   InitText, %function
	.thumb_func
	.set    InitText, 0x08003C8C + 1

	.global Text_Skip
	.type   Text_Skip, %function
	.thumb_func
	.set    Text_Skip, 0x08003D88 + 1

	.global Text_SetColor
	.type   Text_SetColor, %function
	.thumb_func
	.set    Text_SetColor, 0x08003D90 + 1

	.global Text_DrawString
	.type   Text_DrawString, %function
	.thumb_func
	.set    Text_DrawString, 0x08003F28 + 1

	.global Text_DrawNumberOrSpace
	.type   Text_DrawNumberOrSpace, %function
	.thumb_func
	.set    Text_DrawNumberOrSpace, 0x08003FEC + 1

	.global PutText
	.type   PutText, %function
	.thumb_func
	.set    PutText, 0x08003DA0 + 1

	.global ClearBg0Bg1
	.type   ClearBg0Bg1, %function
	.thumb_func
	.set    ClearBg0Bg1, 0x0804F610 + 1

	.global ARMCodeToCopy_End
	.set    ARMCodeToCopy_End, 0x08000A20

	.global ARMCodeToCopy_Start
	.set    ARMCodeToCopy_Start, 0x08000228

	.global gUnk_68
	.set    gUnk_68, 0x030036F0

	.global gUnk_67
	.set    gUnk_67, 0x030036E0

	.global DrawGlyph
	.set    DrawGlyph, 0x08000564

	.global DecodeStringRAMFunc
	.set    DecodeStringRAMFunc, 0x030040F0

	.global DecodeString
	.set    DecodeString, 0x080006E4

	.global gUnk_66
	.set    gUnk_66, 0x030030D0

	.global PutOamHi
	.set    PutOamHi, 0x08000494

	.global gUnk_69
	.set    gUnk_69, 0x030040F4

	.global PutOamLo
	.set    PutOamLo, 0x08000534

	.global gUnk_70
	.set    gUnk_70, 0x03004900

	.global MapFloodCoreStep
	.set    MapFloodCoreStep, 0x08000784

	.global gUnk_65
	.set    gUnk_65, 0x030030C8

	.global MapFloodCore
	.set    MapFloodCore, 0x08000874

	.global _call_via_r4
	.type   _call_via_r4, %function
	.thumb_func
	.set    _call_via_r4, 0x080D65CC + 1

	.global _call_via_r2
	.type   _call_via_r2, %function
	.thumb_func
	.set    _call_via_r2, 0x080D65C4 + 1

	.global StartPalFade
	.type   StartPalFade, %function
	.thumb_func
	.set    StartPalFade, 0x080139E0 + 1

	.global ProcScr_SioMu_0
	.set    ProcScr_SioMu_0, 0x085D48E0

	.global ProcScr_MuDeathFade
	.set    ProcScr_MuDeathFade, 0x08A13308

	.global ProcScr_MuRestorePalInfo
	.set    ProcScr_MuRestorePalInfo, 0x08A13380

	.global Pal_AllWhite
	.set    Pal_AllWhite, 0x085C25C0

	.global Pal_AllBlack
	.set    Pal_AllBlack, 0x085C25A0

	.global Pal_AllRed
	.set    Pal_AllRed, 0x085C25E0

	.global Pal_AllGreen
	.set    Pal_AllGreen, 0x085C2600

	.global Pal_AllBlue
	.set    Pal_AllBlue, 0x085C2620

	.global Pal_AllYellow
	.set    Pal_AllYellow, 0x085C2640

	.global gLinkArenaSt
	.set    gLinkArenaSt, 0x0203DA20

	.global ClearText
	.type   ClearText, %function
	.thumb_func
	.set    ClearText, 0x08003CF8 + 1

	.global gLinkArenaRuleData
	.set    gLinkArenaRuleData, 0x080DEE28

	.global gUnk_Sio_7
	.set    gUnk_Sio_7, 0x0203DA84

	.global DisplayUiHand
	.type   DisplayUiHand, %function
	.thumb_func
	.set    DisplayUiHand, 0x0804F528 + 1

	.global SioPlaySoundEffect
	.type   SioPlaySoundEffect, %function
	.thumb_func
	.set    SioPlaySoundEffect, 0x08043190 + 1

	.global ReadGameSave
	.type   ReadGameSave, %function
	.thumb_func
	.set    ReadGameSave, 0x080A9B40 + 1

	.global ApplyUnitSpritePalettes
	.type   ApplyUnitSpritePalettes, %function
	.thumb_func
	.set    ApplyUnitSpritePalettes, 0x080265CC + 1

	.global LinkArenaBattleMap_InitChapter
	.type   LinkArenaBattleMap_InitChapter, %function
	.thumb_func
	.set    LinkArenaBattleMap_InitChapter, 0x0804A4A0 + 1

	.global ProcScr_AtMenu
	.set    ProcScr_AtMenu, 0x08A93FE8

	.global ClearSioBGFull
	.type   ClearSioBGFull, %function
	.thumb_func
	.set    ClearSioBGFull, 0x08043020 + 1

	.global Nop_SioUiutils_0
	.type   Nop_SioUiutils_0, %function
	.thumb_func
	.set    Nop_SioUiutils_0, 0x0804D148 + 1

	.global EndLinkArenaTitleBanner
	.type   EndLinkArenaTitleBanner, %function
	.thumb_func
	.set    EndLinkArenaTitleBanner, 0x0804D298 + 1

	.global ResetLinkArenaUiBlend
	.type   ResetLinkArenaUiBlend, %function
	.thumb_func
	.set    ResetLinkArenaUiBlend, 0x0804D330 + 1

	.global EndLinkArenaButtonSpriteDraw
	.type   EndLinkArenaButtonSpriteDraw, %function
	.thumb_func
	.set    EndLinkArenaButtonSpriteDraw, 0x0804D0BC + 1

	.global BMapVSync_End
	.type   BMapVSync_End, %function
	.thumb_func
	.set    BMapVSync_End, 0x080300C4 + 1

	.global StartPrepAtMenu
	.type   StartPrepAtMenu, %function
	.thumb_func
	.set    StartPrepAtMenu, 0x08098738 + 1

	.global gUnk_Sio_12
	.set    gUnk_Sio_12, 0x0203DD20

	.global Img_GasTrapVertical
	.set    Img_GasTrapVertical, 0x085C9A30

	.global SpriteAnim_GasTrapVertical
	.set    SpriteAnim_GasTrapVertical, 0x085C9518

	.global Img_GasTrapHorizontal
	.set    Img_GasTrapHorizontal, 0x085CA018

	.global SpriteAnim_GasTrapHorizontal
	.set    SpriteAnim_GasTrapHorizontal, 0x085C97BC

	.global PlaySeSpacial
	.type   PlaySeSpacial, %function
	.thumb_func
	.set    PlaySeSpacial, 0x08014B50 + 1

	.global Pal_GasTrap
	.set    Pal_GasTrap, 0x085CA58C

	.global Img_FireTrap
	.set    Img_FireTrap, 0x085CAE60

	.global SpriteAnim_FireTrap
	.set    SpriteAnim_FireTrap, 0x085CB31C

	.global Pal_FireTrap
	.set    Pal_FireTrap, 0x085CB2FC

	.global Pal_FireTrap2
	.set    Pal_FireTrap2, 0x085CB9B0

	.global Obj_WallBreakAnim
	.set    Obj_WallBreakAnim, 0x08A17660

	.global Img_WallBreakAnim
	.set    Img_WallBreakAnim, 0x08A1E108

	.global Pal_WallBreakAnim
	.set    Pal_WallBreakAnim, 0x08A1E394

	.global EnsureCameraOntoPosition
	.type   EnsureCameraOntoPosition, %function
	.thumb_func
	.set    EnsureCameraOntoPosition, 0x08015E18 + 1

	.global Img_ArrowTrap
	.set    Img_ArrowTrap, 0x085CA5CC

	.global Pal_ArrowTrap
	.set    Pal_ArrowTrap, 0x085CA5AC

	.global SpriteAnim_ArrowTrap
	.set    SpriteAnim_ArrowTrap, 0x085CA8A4

	.global APProc_Exists
	.type   APProc_Exists, %function
	.thumb_func
	.set    APProc_Exists, 0x080096C0 + 1

	.global SetBlendBackdropB
	.type   SetBlendBackdropB, %function
	.thumb_func
	.set    SetBlendBackdropB, 0x08001EB4 + 1

	.global gUnk_32
	.type   gUnk_32, %function
	.thumb_func
	.set    gUnk_32, 0x0201C5D0 + 1

	.global gUnk_31
	.set    gUnk_31, 0x0201C5D0

	.global gUnk_26
	.set    gUnk_26, 0x0201BE32

	.global gUnk_28
	.set    gUnk_28, 0x0201C5C0

	.global gWmHblankStatus
	.set    gWmHblankStatus, 0x0201BE30

	.global gUnk_30
	.type   gUnk_30, %function
	.thumb_func
	.set    gUnk_30, 0x0201C5CE + 1

	.global gUnk_27
	.set    gUnk_27, 0x0201C5B4

	.global gManimActiveScanlineBuf
	.set    gManimActiveScanlineBuf, 0x0203E758

	.global gManimScanlineBufs
	.set    gManimScanlineBufs, 0x0203E750

	.global gUnk_29
	.set    gUnk_29, 0x0201C5CC

	.global gWMNodeData
	.set    gWMNodeData, 0x081F5D7C

	.global ProcScr_GmapTimeMons
	.set    ProcScr_GmapTimeMons, 0x08AC2468

	.global GmMu_SetPosition
	.type   GmMu_SetPosition, %function
	.thumb_func
	.set    GmMu_SetPosition, 0x080C3144 + 1

	.global GmMu_GetPosition
	.type   GmMu_GetPosition, %function
	.thumb_func
	.set    GmMu_GetPosition, 0x080C318C + 1

	.global StartPromoClassSelect
	.type   StartPromoClassSelect, %function
	.thumb_func
	.set    StartPromoClassSelect, 0x080D1A3C + 1

	.global PutMapCursor
	.type   PutMapCursor, %function
	.thumb_func
	.set    PutMapCursor, 0x08015AB4 + 1

	.global StartMapSongBgm
	.type   StartMapSongBgm, %function
	.thumb_func
	.set    StartMapSongBgm, 0x080160DC + 1

	.global gMusicProc3Script
	.set    gMusicProc3Script, 0x08577638

	.global gAiDecision
	.set    gAiDecision, 0x0203AA90

	.global UnitBeginAction
	.type   UnitBeginAction, %function
	.thumb_func
	.set    UnitBeginAction, 0x08018370 + 1

	.global HideUnitSprite
	.type   HideUnitSprite, %function
	.thumb_func
	.set    HideUnitSprite, 0x080280A0 + 1

	.global GenerateUnitMovementMap
	.type   GenerateUnitMovementMap, %function
	.thumb_func
	.set    GenerateUnitMovementMap, 0x0801A05C + 1

	.global GenerateBestMovementScript
	.type   GenerateBestMovementScript, %function
	.thumb_func
	.set    GenerateBestMovementScript, 0x0801A304 + 1

	.global UnitApplyWorkingMovementScript
	.type   UnitApplyWorkingMovementScript, %function
	.thumb_func
	.set    UnitApplyWorkingMovementScript, 0x0801A508 + 1

	.global SetCursorMapPosition
	.type   SetCursorMapPosition, %function
	.thumb_func
	.set    SetCursorMapPosition, 0x08015BD8 + 1

	.global MoveActiveUnit
	.type   MoveActiveUnit, %function
	.thumb_func
	.set    MoveActiveUnit, 0x08018454 + 1

	.global ShowUnitSprite
	.type   ShowUnitSprite, %function
	.thumb_func
	.set    ShowUnitSprite, 0x080280C4 + 1

	.global GetTrapAt
	.type   GetTrapAt, %function
	.thumb_func
	.set    GetTrapAt, 0x0802E128 + 1

	.global EquipUnitItemSlot
	.type   EquipUnitItemSlot, %function
	.thumb_func
	.set    EquipUnitItemSlot, 0x08016968 + 1

	.global gActiveUnitId
	.set    gActiveUnitId, 0x0202BE40

	.global ApplyUnitAction
	.type   ApplyUnitAction, %function
	.thumb_func
	.set    ApplyUnitAction, 0x08031F58 + 1

	.global UnitAddItem
	.type   UnitAddItem, %function
	.thumb_func
	.set    UnitAddItem, 0x080176F0 + 1

	.global UnitRemoveItem
	.type   UnitRemoveItem, %function
	.thumb_func
	.set    UnitRemoveItem, 0x0801915C + 1

	.global NewPopup_ItemStealing
	.type   NewPopup_ItemStealing, %function
	.thumb_func
	.set    NewPopup_ItemStealing, 0x08011780 + 1

	.global ProcScr_CamMove
	.set    ProcScr_CamMove, 0x085C29C8

	.global CanUnitUseStaff
	.type   CanUnitUseStaff, %function
	.thumb_func
	.set    CanUnitUseStaff, 0x0801654C + 1

	.global AiStaffHealMendRecover
	.type   AiStaffHealMendRecover, %function
	.thumb_func
	.set    AiStaffHealMendRecover, 0x0803FB38 + 1

	.global AiStaffPhysicRescue
	.type   AiStaffPhysicRescue, %function
	.thumb_func
	.set    AiStaffPhysicRescue, 0x0803FCB0 + 1

	.global AiStaffFortify
	.type   AiStaffFortify, %function
	.thumb_func
	.set    AiStaffFortify, 0x0803FE80 + 1

	.global AiStaffWarp
	.type   AiStaffWarp, %function
	.thumb_func
	.set    AiStaffWarp, 0x0803FF8C + 1

	.global AiStaffRestore
	.type   AiStaffRestore, %function
	.thumb_func
	.set    AiStaffRestore, 0x080400E4 + 1

	.global AiStaffSilence
	.type   AiStaffSilence, %function
	.thumb_func
	.set    AiStaffSilence, 0x080402D4 + 1

	.global AiStaffSleepBerserk
	.type   AiStaffSleepBerserk, %function
	.thumb_func
	.set    AiStaffSleepBerserk, 0x08040460 + 1

	.global AiStaffBarrier
	.type   AiStaffBarrier, %function
	.thumb_func
	.set    AiStaffBarrier, 0x080405E4 + 1

	.global CallEvent
	.type   CallEvent, %function
	.thumb_func
	.set    CallEvent, 0x0800D340 + 1

	.global EventScr_DisplayBattleQuote
	.set    EventScr_DisplayBattleQuote, 0x085B9D6C

	.global gEventSlots
	.set    gEventSlots, 0x030004B0

	.global EventEngine_CreateBattle
	.type   EventEngine_CreateBattle, %function
	.thumb_func
	.set    EventEngine_CreateBattle, 0x0800D404 + 1

	.global EventScr_TriggerQueuedTileChanges
	.set    EventScr_TriggerQueuedTileChanges, 0x085B9D80

	.global gEventSlotQueue
	.set    gEventSlotQueue, 0x030004E8

	.global EventScr_OpenChest
	.set    EventScr_OpenChest, 0x085B9D8C

	.global EventScr_MapSupportConversation
	.set    EventScr_MapSupportConversation, 0x085B9DD4

	.global EventScr_SupportViewerConversation
	.set    EventScr_SupportViewerConversation, 0x085B9E14

	.global EventScr_SkirmishRetreat
	.set    EventScr_SkirmishRetreat, 0x085B9E3C

	.global EventScr_SuspendPrompt
	.set    EventScr_SuspendPrompt, 0x085B9E9C

	.global EventEngine_Create
	.type   EventEngine_Create, %function
	.thumb_func
	.set    EventEngine_Create, 0x0800D374 + 1

	.global EventScr_GameOver
	.set    EventScr_GameOver, 0x085B9EE8

	.global ProcScr_EventVerticalQuakefx
	.set    ProcScr_EventVerticalQuakefx, 0x08A60168

	.global ProcScr_EventHorizontalQuakefx
	.set    ProcScr_EventHorizontalQuakefx, 0x08A60138

	.global Sound_FadeOutSE
	.type   Sound_FadeOutSE, %function
	.thumb_func
	.set    Sound_FadeOutSE, 0x08002330 + 1

	.global GetBgXOffset
	.type   GetBgXOffset, %function
	.thumb_func
	.set    GetBgXOffset, 0x080B34A0 + 1

	.global ProcScr_EventQuakefx
	.set    ProcScr_EventQuakefx, 0x08A60180

	.global SetFlag
	.type   SetFlag, %function
	.thumb_func
	.set    SetFlag, 0x080860A8 + 1

	.global ClearFlag
	.type   ClearFlag, %function
	.thumb_func
	.set    ClearFlag, 0x080860BC + 1

	.global UnitRemoveInvalidItems
	.type   UnitRemoveInvalidItems, %function
	.thumb_func
	.set    UnitRemoveInvalidItems, 0x0801772C + 1

	.global GetUnitItemCount
	.type   GetUnitItemCount, %function
	.thumb_func
	.set    GetUnitItemCount, 0x08017780 + 1

	.global UnpackUiBarPalette
	.type   UnpackUiBarPalette, %function
	.thumb_func
	.set    UnpackUiBarPalette, 0x0804EEBC + 1

	.global GetUnitPower
	.type   GetUnitPower, %function
	.thumb_func
	.set    GetUnitPower, 0x08018EC4 + 1

	.global GetUnitSkill
	.type   GetUnitSkill, %function
	.thumb_func
	.set    GetUnitSkill, 0x08018EE4 + 1

	.global GetUnitSpeed
	.type   GetUnitSpeed, %function
	.thumb_func
	.set    GetUnitSpeed, 0x08018F24 + 1

	.global GetUnitLuck
	.type   GetUnitLuck, %function
	.thumb_func
	.set    GetUnitLuck, 0x08018FAC + 1

	.global GetUnitDefense
	.type   GetUnitDefense, %function
	.thumb_func
	.set    GetUnitDefense, 0x08018F64 + 1

	.global GetUnitResistance
	.type   GetUnitResistance, %function
	.thumb_func
	.set    GetUnitResistance, 0x08018F84 + 1

	.global DrawStatBarGfx
	.type   DrawStatBarGfx, %function
	.thumb_func
	.set    DrawStatBarGfx, 0x08088DE8 + 1

	.global PutNumberOrBlank
	.type   PutNumberOrBlank, %function
	.thumb_func
	.set    PutNumberOrBlank, 0x08004A9C + 1

	.global TileMap_FillRect
	.type   TileMap_FillRect, %function
	.thumb_func
	.set    TileMap_FillRect, 0x080DC0E4 + 1

	.global DrawPrepScreenSprites
	.type   DrawPrepScreenSprites, %function
	.thumb_func
	.set    DrawPrepScreenSprites, 0x08098C3C + 1

	.global APProc_Delete
	.type   APProc_Delete, %function
	.thumb_func
	.set    APProc_Delete, 0x080096A4 + 1

	.global ProcScr_PrepScreenSpriteDraw
	.set    ProcScr_PrepScreenSpriteDraw, 0x08A943F8

	.global ProcScr_ViewCounter
	.set    ProcScr_ViewCounter, 0x08A945CC

	.global CloseHelpBox
	.type   CloseHelpBox, %function
	.thumb_func
	.set    CloseHelpBox, 0x0808B2A4 + 1

	.global GetUiHandPrevDisplayX
	.type   GetUiHandPrevDisplayX, %function
	.thumb_func
	.set    GetUiHandPrevDisplayX, 0x0804F5F8 + 1

	.global GetUiHandPrevDisplayY
	.type   GetUiHandPrevDisplayY, %function
	.thumb_func
	.set    GetUiHandPrevDisplayY, 0x0804F604 + 1

	.global StartHelpBox
	.type   StartHelpBox, %function
	.thumb_func
	.set    StartHelpBox, 0x0808B06C + 1

	.global gProcScr_PrepHelpboxListener
	.set    gProcScr_PrepHelpboxListener, 0x08A945EC

	.global CanUnitUseWeapon
	.type   CanUnitUseWeapon, %function
	.thumb_func
	.set    CanUnitUseWeapon, 0x0801631C + 1

	.global GetItemAttributes
	.type   GetItemAttributes, %function
	.thumb_func
	.set    GetItemAttributes, 0x08017314 + 1

	.global PutSpriteExt
	.type   PutSpriteExt, %function
	.thumb_func
	.set    PutSpriteExt, 0x08005330 + 1

	.global gObject_32x16
	.set    gObject_32x16, 0x085B8D24

	.global ProcScr_TacticianNameSelection
	.set    ProcScr_TacticianNameSelection, 0x085D351C

	.global LoadLegacyUiFrameGraphics
	.type   LoadLegacyUiFrameGraphics, %function
	.thumb_func
	.set    LoadLegacyUiFrameGraphics, 0x0804F8E0 + 1

	.global UnsetBmStLinkArenaFlag
	.type   UnsetBmStLinkArenaFlag, %function
	.thumb_func
	.set    UnsetBmStLinkArenaFlag, 0x08042E0C + 1

	.global InitTextFont
	.type   InitTextFont, %function
	.thumb_func
	.set    InitTextFont, 0x08003BE8 + 1

	.global Font_0
	.set    Font_0, 0x0203DB60

	.global ClearSioBG
	.type   ClearSioBG, %function
	.thumb_func
	.set    ClearSioBG, 0x08042FC8 + 1

	.global InitSioBG
	.type   InitSioBG, %function
	.thumb_func
	.set    InitSioBG, 0x0804D0DC + 1

	.global InitSpriteTextFont
	.type   InitSpriteTextFont, %function
	.thumb_func
	.set    InitSpriteTextFont, 0x080044A4 + 1

	.global InitSpriteText
	.type   InitSpriteText, %function
	.thumb_func
	.set    InitSpriteText, 0x080044E0 + 1

	.global SpriteText_DrawBackgroundExt
	.type   SpriteText_DrawBackgroundExt, %function
	.thumb_func
	.set    SpriteText_DrawBackgroundExt, 0x080045BC + 1

	.global Sio_SortPlayersByScore
	.type   Sio_SortPlayersByScore, %function
	.thumb_func
	.set    Sio_SortPlayersByScore, 0x08049694 + 1

	.global SioPostBattle_DrawRankingText
	.type   SioPostBattle_DrawRankingText, %function
	.thumb_func
	.set    SioPostBattle_DrawRankingText, 0x0804550C + 1

	.global SioPostBattle_StartMusicProc
	.type   SioPostBattle_StartMusicProc, %function
	.thumb_func
	.set    SioPostBattle_StartMusicProc, 0x080455B0 + 1

	.global Img_TacticianSelObj
	.set    Img_TacticianSelObj, 0x085D6004

	.global Img_LinkArenaPlayerBanners
	.set    Img_LinkArenaPlayerBanners, 0x085D7CD8

	.global Img_LinkArenaPlacementRanks
	.set    Img_LinkArenaPlacementRanks, 0x085D737C

	.global Pal_TacticianSelObj
	.set    Pal_TacticianSelObj, 0x085D7EE8

	.global Pal_LinkArenaPlacementRanks
	.set    Pal_LinkArenaPlacementRanks, 0x085D8068

	.global Img_LinkArenaActiveBannerFx
	.set    Img_LinkArenaActiveBannerFx, 0x085D6FD0

	.global Pal_LinkArenaActiveBannerFx
	.set    Pal_LinkArenaActiveBannerFx, 0x085D80A8

	.global Img_LinkArenaPostBattleBg
	.set    Img_LinkArenaPostBattleBg, 0x085D9350

	.global Pal_LinkArenaPostBattleBg
	.set    Pal_LinkArenaPostBattleBg, 0x085DA9FC

	.global Tsa_LinkArenaPostBattleBg
	.set    Tsa_LinkArenaPostBattleBg, 0x085DAA7C

	.global Font_Sio_0
	.set    Font_Sio_0, 0x02000C60

	.global Pal_Text
	.set    Pal_Text, 0x085C7420

	.global Texts_1
	.set    Texts_1, 0x0203DB10

	.global gSioSt
	.set    gSioSt, 0x085D31E8

	.global UpdateLinkArenaActiveBannerBgGlow
	.type   UpdateLinkArenaActiveBannerBgGlow, %function
	.thumb_func
	.set    UpdateLinkArenaActiveBannerBgGlow, 0x0804E468 + 1

	.global SioPostBattle_DrawRankingRowBar
	.type   SioPostBattle_DrawRankingRowBar, %function
	.thumb_func
	.set    SioPostBattle_DrawRankingRowBar, 0x08045484 + 1

	.global StartDrawLinkArenaRankSprites
	.type   StartDrawLinkArenaRankSprites, %function
	.thumb_func
	.set    StartDrawLinkArenaRankSprites, 0x08045434 + 1

	.global gUnk_Sio_16
	.set    gUnk_Sio_16, 0x0203DD8C

	.global m4aMPlayFadeOut
	.type   m4aMPlayFadeOut, %function
	.thumb_func
	.set    m4aMPlayFadeOut, 0x080D508C + 1

	.global gMPlayTable
	.set    gMPlayTable, 0x082140B4

	.global gSongTable
	.set    gSongTable, 0x08214120

	.global StartBgmExt
	.type   StartBgmExt, %function
	.thumb_func
	.set    StartBgmExt, 0x08002434 + 1

	.global gUnk_41
	.set    gUnk_41, 0x03001808

	.global ArenaGetResult
	.type   ArenaGetResult, %function
	.thumb_func
	.set    ArenaGetResult, 0x08031E24 + 1

	.global DisplayGoldBoxText
	.type   DisplayGoldBoxText, %function
	.thumb_func
	.set    DisplayGoldBoxText, 0x080B9A5C + 1

	.global Proc_ForEach
	.type   Proc_ForEach, %function
	.thumb_func
	.set    Proc_ForEach, 0x08002EE8 + 1

	.global gProcScr_GoldBox
	.set    gProcScr_GoldBox, 0x08ABCAB8

	.global ProcScr_Mu
	.set    ProcScr_Mu, 0x08A132D0

	.global ShowMu
	.type   ShowMu, %function
	.thumb_func
	.set    ShowMu, 0x0807BBF0 + 1

	.global SetInitTalkTextFont
	.type   SetInitTalkTextFont, %function
	.thumb_func
	.set    SetInitTalkTextFont, 0x0800687C + 1

	.global ClearTalkText
	.type   ClearTalkText, %function
	.thumb_func
	.set    ClearTalkText, 0x0800814C + 1

	.global StartTalkExt
	.type   StartTalkExt, %function
	.thumb_func
	.set    StartTalkExt, 0x08006890 + 1

	.global SetTalkPrintColor
	.type   SetTalkPrintColor, %function
	.thumb_func
	.set    SetTalkPrintColor, 0x08006A14 + 1

	.global SetTalkFlag
	.type   SetTalkFlag, %function
	.thumb_func
	.set    SetTalkFlag, 0x080069AC + 1

	.global SetActiveTalkFace
	.type   SetActiveTalkFace, %function
	.thumb_func
	.set    SetActiveTalkFace, 0x0800773C + 1

	.global SetTextFont
	.type   SetTextFont, %function
	.thumb_func
	.set    SetTextFont, 0x08003C68 + 1

	.global InitSystemTextFont
	.type   InitSystemTextFont, %function
	.thumb_func
	.set    InitSystemTextFont, 0x080042E0 + 1

	.global PutString
	.type   PutString, %function
	.thumb_func
	.set    PutString, 0x08014450 + 1

	.global PutNumber
	.type   PutNumber, %function
	.thumb_func
	.set    PutNumber, 0x08004A90 + 1

	.global GetItemName
	.type   GetItemName, %function
	.thumb_func
	.set    GetItemName, 0x0801729C + 1

	.global gMid_Lv
	.set    gMid_Lv, 0x08A73210

	.global gArenaState
	.set    gArenaState, 0x0203A8EC

	.global StartBgmCore
	.type   StartBgmCore, %function
	.thumb_func
	.set    StartBgmCore, 0x08002398 + 1

	.global EndGmapEffect
	.type   EndGmapEffect, %function
	.thumb_func
	.set    EndGmapEffect, 0x080C619C + 1

	.global unit_icon_move_table
	.set    unit_icon_move_table, 0x08A13488

	.global gUnk_6
	.set    gUnk_6, 0x0200AF00

	.global AP_Delete
	.type   AP_Delete, %function
	.thumb_func
	.set    AP_Delete, 0x08009194 + 1

	.global gObject_8x8
	.set    gObject_8x8, 0x085B8CDC

	.global HideMoveRangeGraphics
	.type   HideMoveRangeGraphics, %function
	.thumb_func
	.set    HideMoveRangeGraphics, 0x0801D730 + 1

	.global ReadGlobalSaveInfo
	.type   ReadGlobalSaveInfo, %function
	.thumb_func
	.set    ReadGlobalSaveInfo, 0x080A776C + 1

	.global Checksum16
	.type   Checksum16, %function
	.thumb_func
	.set    Checksum16, 0x080A7740 + 1

	.global GetStringTextCenteredPos
	.type   GetStringTextCenteredPos, %function
	.thumb_func
	.set    GetStringTextCenteredPos, 0x08003EAC + 1

	.global Text_InsertDrawString
	.type   Text_InsertDrawString, %function
	.thumb_func
	.set    Text_InsertDrawString, 0x080043B8 + 1

	.global gParticlesFx_7
	.set    gParticlesFx_7, 0x085CFC50

	.global gParticlesFx_6
	.set    gParticlesFx_6, 0x085CFBA0

	.global GetTextDisplaySpeed
	.type   GetTextDisplaySpeed, %function
	.thumb_func
	.set    GetTextDisplaySpeed, 0x08030BE4 + 1

	.global GetCgTextBoxDimensions
	.type   GetCgTextBoxDimensions, %function
	.thumb_func
	.set    GetCgTextBoxDimensions, 0x080916FC + 1

	.global PutTalkBubbleTm
	.type   PutTalkBubbleTm, %function
	.thumb_func
	.set    PutTalkBubbleTm, 0x08008564 + 1

	.global PutTalkBubbleTail
	.type   PutTalkBubbleTail, %function
	.thumb_func
	.set    PutTalkBubbleTail, 0x080083DC + 1

	.global CgText_AdjustBoxPosition
	.type   CgText_AdjustBoxPosition, %function
	.thumb_func
	.set    CgText_AdjustBoxPosition, 0x080916AC + 1

	.global StartParallelWorker
	.type   StartParallelWorker, %function
	.thumb_func
	.set    StartParallelWorker, 0x080B1D98 + 1

	.global CgText_ClearSpriteText
	.type   CgText_ClearSpriteText, %function
	.thumb_func
	.set    CgText_ClearSpriteText, 0x08091590 + 1

	.global CgText_Display
	.type   CgText_Display, %function
	.thumb_func
	.set    CgText_Display, 0x0809189C + 1

	.global SetSecondaryHBlankHandler
	.type   SetSecondaryHBlankHandler, %function
	.thumb_func
	.set    SetSecondaryHBlankHandler, 0x08001D3C + 1

	.global GetFaceDisplayBitsById
	.type   GetFaceDisplayBitsById, %function
	.thumb_func
	.set    GetFaceDisplayBitsById, 0x080056B0 + 1

	.global SetFaceDisplayBitsById
	.type   SetFaceDisplayBitsById, %function
	.thumb_func
	.set    SetFaceDisplayBitsById, 0x08005694 + 1

	.global EndCgTextInterpreter
	.type   EndCgTextInterpreter, %function
	.thumb_func
	.set    EndCgTextInterpreter, 0x080922C8 + 1

	.global StartFaceFadeOut
	.type   StartFaceFadeOut, %function
	.thumb_func
	.set    StartFaceFadeOut, 0x08005E3C + 1

	.global gProcScr_E_FACE
	.set    gProcScr_E_FACE, 0x085B8EEC

	.global SetDialogueSkipEvBit
	.type   SetDialogueSkipEvBit, %function
	.thumb_func
	.set    SetDialogueSkipEvBit, 0x0800D6A8 + 1

	.global GetChapterEventDataPointer
	.type   GetChapterEventDataPointer, %function
	.thumb_func
	.set    GetChapterEventDataPointer, 0x080345B8 + 1

	.global GetBattleMapKind
	.type   GetBattleMapKind, %function
	.thumb_func
	.set    GetBattleMapKind, 0x080C1E74 + 1

	.global RefreshAllies
	.type   RefreshAllies, %function
	.thumb_func
	.set    RefreshAllies, 0x08018E1C + 1

	.global EventScr_SkirmishCommonEnd
	.set    EventScr_SkirmishCommonEnd, 0x08A71E1C

	.global CheckFlag
	.type   CheckFlag, %function
	.thumb_func
	.set    CheckFlag, 0x080860D0 + 1

	.global ShouldCallEndEvent
	.type   ShouldCallEndEvent, %function
	.thumb_func
	.set    ShouldCallEndEvent, 0x08085588 + 1

	.global gSioResultRankings
	.set    gSioResultRankings, 0x0203DC40

	.global SioStrCpy
	.type   SioStrCpy, %function
	.thumb_func
	.set    SioStrCpy, 0x08042D4C + 1

	.global gUnk_Sio_9
	.type   gUnk_Sio_9, %function
	.thumb_func
	.set    gUnk_Sio_9, 0x0203DAC0 + 1

	.global gUnk_47
	.set    gUnk_47, 0x03001838

	.global SetBackgroundScreenSize
	.type   SetBackgroundScreenSize, %function
	.thumb_func
	.set    SetBackgroundScreenSize, 0x08000FFC + 1

	.global BgAffineSetOpAnim
	.type   BgAffineSetOpAnim, %function
	.thumb_func
	.set    BgAffineSetOpAnim, 0x080CBAFC + 1

	.global gObject_32x32
	.set    gObject_32x32, 0x085B8CEC

	.global BlendPaletteToColor
	.type   BlendPaletteToColor, %function
	.thumb_func
	.set    BlendPaletteToColor, 0x080CB8BC + 1

	.global gPal_TitleMainBackground
	.set    gPal_TitleMainBackground, 0x08B43988

	.global gPal_Titlescreen_2
	.set    gPal_Titlescreen_2, 0x08B48918

	.global gGfx_TitleDemonKing
	.set    gGfx_TitleDemonKing, 0x08B49B6C

	.global gTsa_TitleDemonKing
	.set    gTsa_TitleDemonKing, 0x08B4A8B8

	.global gPal_TitleDemonKing
	.set    gPal_TitleDemonKing, 0x08B4AC2C

	.global Title_SetBg2AffineScale
	.type   Title_SetBg2AffineScale, %function
	.thumb_func
	.set    Title_SetBg2AffineScale, 0x080CA318 + 1

	.global SetBackgroundMapDataOffset
	.type   SetBackgroundMapDataOffset, %function
	.thumb_func
	.set    SetBackgroundMapDataOffset, 0x08000FB4 + 1

	.global gGfx_Titlescreen_3
	.set    gGfx_Titlescreen_3, 0x08B48D58

	.global gTsa_Titlescreen_3
	.set    gTsa_Titlescreen_3, 0x08B49A20

	.global gPal_Titlescreen_4
	.set    gPal_Titlescreen_4, 0x08B49B4C

	.global GetAnimPosition
	.type   GetAnimPosition, %function
	.thumb_func
	.set    GetAnimPosition, 0x0805AF10 + 1

	.global gEkrGaugeHp
	.set    gEkrGaugeHp, 0x0203E1A8

	.global gPalEfxHpBarGreen
	.set    gPalEfxHpBarGreen, 0x088570DC

	.global gPalEfxHpBarPurple
	.set    gPalEfxHpBarPurple, 0x088571DC

	.global gBanimFactionPal
	.set    gBanimFactionPal, 0x0203E110

	.global gBanimmisc_10
	.set    gBanimmisc_10, 0x0885705C

	.global EfxSplitColor
	.type   EfxSplitColor, %function
	.thumb_func
	.set    EfxSplitColor, 0x080739D0 + 1

	.global EfxCalcSplitedColorStep
	.type   EfxCalcSplitedColorStep, %function
	.thumb_func
	.set    EfxCalcSplitedColorStep, 0x08073A68 + 1

	.global gpProcEfxHpBarColorChange
	.set    gpProcEfxHpBarColorChange, 0x0201777C

	.global ProcScr_efxHPBarColorChange
	.set    ProcScr_efxHPBarColorChange, 0x085E3BA4

	.global gFrameLut_EfxHPBarColorChange1
	.set    gFrameLut_EfxHPBarColorChange1, 0x080DFC44

	.global gFrameLut_EfxHPBarColorChange2
	.set    gFrameLut_EfxHPBarColorChange2, 0x080DFC6E

	.global gEfxSplitedColorBufA
	.set    gEfxSplitedColorBufA, 0x0201F948

	.global gBanimmisc_11
	.set    gBanimmisc_11, 0x0885711C

	.global gEfxSplitedColorBufB
	.set    gEfxSplitedColorBufB, 0x0201F978

	.global gEfxSplitedColorBufC
	.set    gEfxSplitedColorBufC, 0x0201F9A8

	.global gEfxSplitedColorBufD
	.set    gEfxSplitedColorBufD, 0x0201FA08

	.global gEfxSplitedColorBufE
	.set    gEfxSplitedColorBufE, 0x0201FA38

	.global gEfxSplitedColorBufF
	.set    gEfxSplitedColorBufF, 0x0201FA68

	.global EfxAdvanceFrameLut
	.type   EfxAdvanceFrameLut, %function
	.thumb_func
	.set    EfxAdvanceFrameLut, 0x08056890 + 1

	.global EfxDecodeSplitedPalette
	.type   EfxDecodeSplitedPalette, %function
	.thumb_func
	.set    EfxDecodeSplitedPalette, 0x08073AE8 + 1

	.global EfxCreateFrontAnim
	.type   EfxCreateFrontAnim, %function
	.thumb_func
	.set    EfxCreateFrontAnim, 0x080564F0 + 1

	.global ProcScr_efxDarkbreathOBJ
	.set    ProcScr_efxDarkbreathOBJ, 0x085FF6A8

	.global AnimScr_DarkBreath_Close
	.set    AnimScr_DarkBreath_Close, 0x08612650

	.global AnimScr_DarkBreath_Far
	.set    AnimScr_DarkBreath_Far, 0x0874FDE0

	.global gEkrDistanceType
	.set    gEkrDistanceType, 0x0203E11C

	.global SpellFx_RegisterObjPal
	.type   SpellFx_RegisterObjPal, %function
	.thumb_func
	.set    SpellFx_RegisterObjPal, 0x0805679C + 1

	.global SpellFx_RegisterObjGfx
	.type   SpellFx_RegisterObjGfx, %function
	.thumb_func
	.set    SpellFx_RegisterObjGfx, 0x08056774 + 1

	.global Pal_DarkBreathSprites
	.set    Pal_DarkBreathSprites, 0x0860C620

	.global Img_BreathSprites
	.set    Img_BreathSprites, 0x0860A83C

	.global AnimDelete
	.type   AnimDelete, %function
	.thumb_func
	.set    AnimDelete, 0x08004F0C + 1

	.global efxCrimsonEyeOBJ_GetOffsetX
	.type   efxCrimsonEyeOBJ_GetOffsetX, %function
	.thumb_func
	.set    efxCrimsonEyeOBJ_GetOffsetX, 0x0806C958 + 1

	.global efxCrimsonEyeOBJ_GetOffsetY
	.type   efxCrimsonEyeOBJ_GetOffsetY, %function
	.thumb_func
	.set    efxCrimsonEyeOBJ_GetOffsetY, 0x0806C970 + 1

	.global Div
	.type   Div, %function
	.thumb_func
	.set    Div, 0x080D6374 + 1

	.global SetObjAffine
	.type   SetObjAffine, %function
	.thumb_func
	.set    SetObjAffine, 0x08002100 + 1

	.global gSinLookup
	.set    gSinLookup, 0x080DC15C

	.global CopyPalWithFade
	.type   CopyPalWithFade, %function
	.thumb_func
	.set    CopyPalWithFade, 0x0807A3EC + 1

	.global SpellFx_RegisterBgPal
	.type   SpellFx_RegisterBgPal, %function
	.thumb_func
	.set    SpellFx_RegisterBgPal, 0x080567E0 + 1

	.global Pal_Ekrdragonfx_2
	.set    Pal_Ekrdragonfx_2, 0x088481AC

	.global Pal_DemonLightSprites
	.set    Pal_DemonLightSprites, 0x087F9CA4

	.global Img_DemonLightSprites
	.set    Img_DemonLightSprites, 0x087F98E8

	.global EfxTmCpyBgHFlip
	.type   EfxTmCpyBgHFlip, %function
	.thumb_func
	.set    EfxTmCpyBgHFlip, 0x080733E8 + 1

	.global gEkrTsaBuffer
	.set    gEkrTsaBuffer, 0x02019790

	.global gBG1TilemapBuffer
	.set    gBG1TilemapBuffer, 0x020234A8

	.global EfxTmCpyBG
	.type   EfxTmCpyBG, %function
	.thumb_func
	.set    EfxTmCpyBG, 0x080733B8 + 1

	.global EfxChapterMapFadeOUT
	.type   EfxChapterMapFadeOUT, %function
	.thumb_func
	.set    EfxChapterMapFadeOUT, 0x08073B80 + 1

	.global gBanimBG
	.set    gBanimBG, 0x0203E0FA

	.global PutBanimBgPAL
	.type   PutBanimBgPAL, %function
	.thumb_func
	.set    PutBanimBgPAL, 0x08077EE8 + 1

	.global gUnk_Banim_Ekrbattle_10
	.set    gUnk_Banim_Ekrbattle_10, 0x0201FB28

	.global AnimScr_EfxLiveOBJ2
	.set    AnimScr_EfxLiveOBJ2, 0x086A1D7C

	.global DisablePaletteSync
	.type   DisablePaletteSync, %function
	.thumb_func
	.set    DisablePaletteSync, 0x08001EF0 + 1

	.global ProcScr_efxArrowOBJ
	.set    ProcScr_efxArrowOBJ, 0x085FF340

	.global AnimScr_ArrowCloseLeft
	.set    AnimScr_ArrowCloseLeft, 0x08605008

	.global AnimScr_ArrowCloseRight
	.set    AnimScr_ArrowCloseRight, 0x08604F7C

	.global AnimScr_ArrowFarLeft
	.set    AnimScr_ArrowFarLeft, 0x08605018

	.global AnimScr_ArrowFarRight
	.set    AnimScr_ArrowFarRight, 0x08604F8C

	.global Pal_TeonoOBJ
	.set    Pal_TeonoOBJ, 0x08604784

	.global Img_EfxArrowOBJ
	.set    Img_EfxArrowOBJ, 0x08604ED4

	.global SpellFx_Begin
	.type   SpellFx_Begin, %function
	.thumb_func
	.set    SpellFx_Begin, 0x08056108 + 1

	.global SpellFx_ClearBG1Position
	.type   SpellFx_ClearBG1Position, %function
	.thumb_func
	.set    SpellFx_ClearBG1Position, 0x08056120 + 1

	.global GetAnimRoundTypeAnotherSide
	.type   GetAnimRoundTypeAnotherSide, %function
	.thumb_func
	.set    GetAnimRoundTypeAnotherSide, 0x0805B0B4 + 1

	.global CheckRoundMiss
	.type   CheckRoundMiss, %function
	.thumb_func
	.set    CheckRoundMiss, 0x0805AF28 + 1

	.global NewEfxTeyariOBJ
	.type   NewEfxTeyariOBJ, %function
	.thumb_func
	.set    NewEfxTeyariOBJ, 0x0805D628 + 1

	.global ProcScr_efxTeyari
	.set    ProcScr_efxTeyari, 0x085FF358

	.global Pal_SpellJavelin
	.set    Pal_SpellJavelin, 0x08605258

	.global Img_SpellJavelin
	.set    Img_SpellJavelin, 0x08605028

	.global Pal_SpellJavelinCavalier
	.set    Pal_SpellJavelinCavalier, 0x08605494

	.global Img_SpellJavelinCavalier
	.set    Img_SpellJavelinCavalier, 0x08605278

	.global Pal_SpellJavelinSoldier
	.set    Pal_SpellJavelinSoldier, 0x086056CC

	.global Img_SpellJavelinSoldier
	.set    Img_SpellJavelinSoldier, 0x086054B4

	.global Pal_SpellJavelinPaladin
	.set    Pal_SpellJavelinPaladin, 0x08605908

	.global Img_SpellJavelinPaladin
	.set    Img_SpellJavelinPaladin, 0x086056EC

	.global Pal_SpellJavelinPegasusKnight
	.set    Pal_SpellJavelinPegasusKnight, 0x08605B54

	.global Img_SpellJavelinPegasusKnight
	.set    Img_SpellJavelinPegasusKnight, 0x08605928

	.global Pal_SpellJavelinFalcon
	.set    Pal_SpellJavelinFalcon, 0x08605DBC

	.global Img_SpellJavelinFalcon
	.set    Img_SpellJavelinFalcon, 0x08605B74

	.global Pal_SpellJavelinWyvernRider
	.set    Pal_SpellJavelinWyvernRider, 0x08606014

	.global Img_SpellJavelinWyvernRider
	.set    Img_SpellJavelinWyvernRider, 0x08605DDC

	.global Pal_SpellJavelinWyvernLord
	.set    Pal_SpellJavelinWyvernLord, 0x08606298

	.global Img_SpellJavelinWyvernLord
	.set    Img_SpellJavelinWyvernLord, 0x08606034

	.global Pal_SpellJavelinGenerial
	.set    Pal_SpellJavelinGenerial, 0x08606528

	.global Img_SpellJavelinGenerial
	.set    Img_SpellJavelinGenerial, 0x086062B8

	.global Pal_SpellJavelinUnk
	.set    Pal_SpellJavelinUnk, 0x08606778

	.global Img_SpellJavelinUnk
	.set    Img_SpellJavelinUnk, 0x08606548

	.global NewEfxFarAttackWithDistance
	.type   NewEfxFarAttackWithDistance, %function
	.thumb_func
	.set    NewEfxFarAttackWithDistance, 0x080540C0 + 1

	.global GetAnimAnotherSide
	.type   GetAnimAnotherSide, %function
	.thumb_func
	.set    GetAnimAnotherSide, 0x0805B058 + 1

	.global StartBattleAnimHitEffectsDefault
	.type   StartBattleAnimHitEffectsDefault, %function
	.thumb_func
	.set    StartBattleAnimHitEffectsDefault, 0x08056220 + 1

	.global GetEfxHpChangeType
	.type   GetEfxHpChangeType, %function
	.thumb_func
	.set    GetEfxHpChangeType, 0x080748E4 + 1

	.global CheckRoundCrit
	.type   CheckRoundCrit, %function
	.thumb_func
	.set    CheckRoundCrit, 0x0805B00C + 1

	.global NewEfxPierceCritical
	.type   NewEfxPierceCritical, %function
	.thumb_func
	.set    NewEfxPierceCritical, 0x0806EA40 + 1

	.global NewEfxNormalEffect
	.type   NewEfxNormalEffect, %function
	.thumb_func
	.set    NewEfxNormalEffect, 0x0806EBA0 + 1

	.global EfxPlayHittedSFX
	.type   EfxPlayHittedSFX, %function
	.thumb_func
	.set    EfxPlayHittedSFX, 0x08074934 + 1

	.global SpellFx_Finish
	.type   SpellFx_Finish, %function
	.thumb_func
	.set    SpellFx_Finish, 0x08056114 + 1

	.global SpellFx_WriteBgMap
	.type   SpellFx_WriteBgMap, %function
	.thumb_func
	.set    SpellFx_WriteBgMap, 0x0805660C + 1

	.global FillBGRect
	.type   FillBGRect, %function
	.thumb_func
	.set    FillBGRect, 0x080732A0 + 1

	.global ProcScr_efxLokmsunaOBJ
	.set    ProcScr_efxLokmsunaOBJ, 0x086036B4

	.global AnimScr_EfxLokmsunaObjLeft
	.set    AnimScr_EfxLokmsunaObjLeft, 0x087A89EC

	.global AnimScr_EfxLokmsunaObjRight
	.set    AnimScr_EfxLokmsunaObjRight, 0x087A8B10

	.global Img_EfxLokmsunaObj
	.set    Img_EfxLokmsunaObj, 0x087A874C

	.global ProcScr_efxKingPika
	.set    ProcScr_efxKingPika, 0x086036CC

	.global NewEfxFlashUnit
	.type   NewEfxFlashUnit, %function
	.thumb_func
	.set    NewEfxFlashUnit, 0x080554C4 + 1

	.global gAnims
	.set    gAnims, 0x02000000

	.global ProcScr_efxFlashFX
	.set    ProcScr_efxFlashFX, 0x086036E4

	.global ProcScr_efxSongOBJ2
	.set    ProcScr_efxSongOBJ2, 0x086036FC

	.global AnimScr_EfxSongObj2
	.set    AnimScr_EfxSongObj2, 0x08607BDC

	.global Pal_EfxDanceObj
	.set    Pal_EfxDanceObj, 0x086073AC

	.global Img_EfxDanceObj
	.set    Img_EfxDanceObj, 0x08607238

	.global ProcScr_efxDanceOBJ
	.set    ProcScr_efxDanceOBJ, 0x08603714

	.global AnimScr_EfxDanceObj
	.set    AnimScr_EfxDanceObj, 0x08607BAC

	.global gEfxSpecalEffectExist
	.set    gEfxSpecalEffectExist, 0x02017768

	.global gpEkrBattleUnitLeft
	.set    gpEkrBattleUnitLeft, 0x0203E184

	.global IsWeaponLegency
	.type   IsWeaponLegency, %function
	.thumb_func
	.set    IsWeaponLegency, 0x080598F8 + 1

	.global gpEkrBattleUnitRight
	.set    gpEkrBattleUnitRight, 0x0203E188

	.global NewEfxSRankWeaponEffect
	.type   NewEfxSRankWeaponEffect, %function
	.thumb_func
	.set    NewEfxSRankWeaponEffect, 0x0806FCA8 + 1

	.global ProcScr_efxSpecalEffect
	.set    ProcScr_efxSpecalEffect, 0x0860372C

	.global gpProcEfxStatusUnits
	.set    gpProcEfxStatusUnits, 0x0201776C

	.global EfxPalFlashingInOut
	.type   EfxPalFlashingInOut, %function
	.thumb_func
	.set    EfxPalFlashingInOut, 0x080738A4 + 1

	.global GetEkrDragonStatusUnk1
	.type   GetEkrDragonStatusUnk1, %function
	.thumb_func
	.set    GetEkrDragonStatusUnk1, 0x08072048 + 1

	.global BanimSetFrontPaletteForDragon
	.type   BanimSetFrontPaletteForDragon, %function
	.thumb_func
	.set    BanimSetFrontPaletteForDragon, 0x0807290C + 1

	.global gpEfxUnitPaletteBackup
	.set    gpEfxUnitPaletteBackup, 0x02000054

	.global ProcScr_ekrsubAnimeEmulator
	.set    ProcScr_ekrsubAnimeEmulator, 0x087A8F64

	.global AnimDisplay
	.type   AnimDisplay, %function
	.thumb_func
	.set    AnimDisplay, 0x08004F3C + 1

	.global gAnimSpriteRotScalePosX
	.set    gAnimSpriteRotScalePosX, 0x080E67B4

	.global gAnimSpriteRotScalePosY
	.set    gAnimSpriteRotScalePosY, 0x080E67D4

	.global EfxTmCpyExt
	.type   EfxTmCpyExt, %function
	.thumb_func
	.set    EfxTmCpyExt, 0x08073418 + 1

	.global gTmB_Banim
	.set    gTmB_Banim, 0x0201D428

	.global GetBattleAnimArenaFlag
	.type   GetBattleAnimArenaFlag, %function
	.thumb_func
	.set    GetBattleAnimArenaFlag, 0x0805BDCC + 1

	.global DoM4aSongNumStop
	.type   DoM4aSongNumStop, %function
	.thumb_func
	.set    DoM4aSongNumStop, 0x08073F28 + 1

	.global NewEkrBattleDeamon
	.type   NewEkrBattleDeamon, %function
	.thumb_func
	.set    NewEkrBattleDeamon, 0x08050AD4 + 1

	.global AnimClearAll
	.type   AnimClearAll, %function
	.thumb_func
	.set    AnimClearAll, 0x08004DC0 + 1

	.global GetBanimInitPosReal
	.type   GetBanimInitPosReal, %function
	.thumb_func
	.set    GetBanimInitPosReal, 0x08052E7C + 1

	.global gEkrInitPosReal
	.set    gEkrInitPosReal, 0x02017744

	.global SetMainUpdateRoutine
	.type   SetMainUpdateRoutine, %function
	.thumb_func
	.set    SetMainUpdateRoutine, 0x080012D8 + 1

	.global MainUpdate_0
	.type   MainUpdate_0, %function
	.thumb_func
	.set    MainUpdate_0, 0x08056BF0 + 1

	.global ProcScr_efxStatusUnit
	.set    ProcScr_efxStatusUnit, 0x085E3C14

	.global gProc_ekrTogiInit
	.set    gProc_ekrTogiInit, 0x085E400C

	.global InitOam
	.type   InitOam, %function
	.thumb_func
	.set    InitOam, 0x0800204C + 1

	.global EfxClearScreenFx
	.type   EfxClearScreenFx, %function
	.thumb_func
	.set    EfxClearScreenFx, 0x080529BC + 1

	.global UpdateBanimFrame
	.type   UpdateBanimFrame, %function
	.thumb_func
	.set    UpdateBanimFrame, 0x0805A78C + 1

	.global NewEkrGauge
	.type   NewEkrGauge, %function
	.thumb_func
	.set    NewEkrGauge, 0x08051C2C + 1

	.global NewEkrDispUP
	.type   NewEkrDispUP, %function
	.thumb_func
	.set    NewEkrDispUP, 0x080527BC + 1

	.global NewEkrBattle
	.type   NewEkrBattle, %function
	.thumb_func
	.set    NewEkrBattle, 0x08050B48 + 1

	.global gEkrInitialHitSide
	.set    gEkrInitialHitSide, 0x0203E0FC

	.global Pal_ArenaBattleBg_A
	.set    Pal_ArenaBattleBg_A, 0x085E91C4

	.global LZ77UnCompVram
	.type   LZ77UnCompVram, %function
	.thumb_func
	.set    LZ77UnCompVram, 0x080D6390 + 1

	.global LZ77UnCompWram
	.type   LZ77UnCompWram, %function
	.thumb_func
	.set    LZ77UnCompWram, 0x080D6394 + 1

	.global Img_ArenaBattleBg
	.set    Img_ArenaBattleBg, 0x085E63B8

	.global Tsa_ArenaBattleBg
	.set    Tsa_ArenaBattleBg, 0x085E8A24

	.global NewEkrTogiColor
	.type   NewEkrTogiColor, %function
	.thumb_func
	.set    NewEkrTogiColor, 0x0805C0F0 + 1

	.global EndEkrTogiColor
	.type   EndEkrTogiColor, %function
	.thumb_func
	.set    EndEkrTogiColor, 0x0805C124 + 1

	.global gProc_ekrTogiEnd
	.set    gProc_ekrTogiEnd, 0x085E403C

	.global EndEkrBattleDeamon
	.type   EndEkrBattleDeamon, %function
	.thumb_func
	.set    EndEkrBattleDeamon, 0x08050B00 + 1

	.global EndEkrGauge
	.type   EndEkrGauge, %function
	.thumb_func
	.set    EndEkrGauge, 0x08051EA0 + 1

	.global SetInterrupt_LCDVBlank
	.type   SetInterrupt_LCDVBlank, %function
	.thumb_func
	.set    SetInterrupt_LCDVBlank, 0x08001208 + 1

	.global OnMain
	.type   OnMain, %function
	.thumb_func
	.set    OnMain, 0x08015318 + 1

	.global OnVBlank
	.type   OnVBlank, %function
	.thumb_func
	.set    OnVBlank, 0x080152C8 + 1

	.global NewEkrUnitKakudai
	.type   NewEkrUnitKakudai, %function
	.thumb_func
	.set    NewEkrUnitKakudai, 0x08057888 + 1

	.global NewEkrBaseKaiten
	.type   NewEkrBaseKaiten, %function
	.thumb_func
	.set    NewEkrBaseKaiten, 0x08057424 + 1

	.global NewEkrWindowAppear
	.type   NewEkrWindowAppear, %function
	.thumb_func
	.set    NewEkrWindowAppear, 0x08057CAC + 1

	.global NewEkrBaseAppear
	.type   NewEkrBaseAppear, %function
	.thumb_func
	.set    NewEkrBaseAppear, 0x08057EA8 + 1

	.global gEkrBmLocation
	.set    gEkrBmLocation, 0x0203E11E

	.global InitBmBgLayers
	.type   InitBmBgLayers, %function
	.thumb_func
	.set    InitBmBgLayers, 0x08015624 + 1

	.global ResetUnitSprites
	.type   ResetUnitSprites, %function
	.thumb_func
	.set    ResetUnitSprites, 0x0802662C + 1

	.global BMapDispResume_FromBattleDelayed
	.type   BMapDispResume_FromBattleDelayed, %function
	.thumb_func
	.set    BMapDispResume_FromBattleDelayed, 0x080310A0 + 1

	.global UnpackChapterMapPalette
	.type   UnpackChapterMapPalette, %function
	.thumb_func
	.set    UnpackChapterMapPalette, 0x0801964C + 1

	.global GetBanimLinkArenaFlag
	.type   GetBanimLinkArenaFlag, %function
	.thumb_func
	.set    GetBanimLinkArenaFlag, 0x08050AC8 + 1

	.global LoadLinkArenaFogPlaceholder
	.type   LoadLinkArenaFogPlaceholder, %function
	.thumb_func
	.set    LoadLinkArenaFogPlaceholder, 0x0804A584 + 1

	.global RefreshBMapDisplay_FromBattle
	.type   RefreshBMapDisplay_FromBattle, %function
	.thumb_func
	.set    RefreshBMapDisplay_FromBattle, 0x08031044 + 1

	.global GetEkrDragonPalette
	.type   GetEkrDragonPalette, %function
	.thumb_func
	.set    GetEkrDragonPalette, 0x08072880 + 1

	.global SetEkrDragonPaletteFront
	.type   SetEkrDragonPaletteFront, %function
	.thumb_func
	.set    SetEkrDragonPaletteFront, 0x080728DC + 1

	.global SetEkrDragonPaletteBack
	.type   SetEkrDragonPaletteBack, %function
	.thumb_func
	.set    SetEkrDragonPaletteBack, 0x080728AC + 1

	.global ProcScr_EkrDragon_0
	.set    ProcScr_EkrDragon_0, 0x087A8C54

	.global gEkrdragon_0
	.set    gEkrdragon_0, 0x087A8C74

	.global EkrDemonkingObj_SetBgPosition
	.type   EkrDemonkingObj_SetBgPosition, %function
	.thumb_func
	.set    EkrDemonkingObj_SetBgPosition, 0x0807A2D0 + 1

	.global EkrDragonTmCpyExt
	.type   EkrDragonTmCpyExt, %function
	.thumb_func
	.set    EkrDragonTmCpyExt, 0x080720DC + 1

	.global gUnk_76
	.set    gUnk_76, 0x03004F90

	.global gEkrBgPosition
	.set    gEkrBgPosition, 0x0201FB0C

	.global gUnk_77
	.set    gUnk_77, 0x03004F94

	.global gEkrdragonDemonkingobj_2
	.set    gEkrdragonDemonkingobj_2, 0x08856004

	.global SetBlackPal
	.type   SetBlackPal, %function
	.thumb_func
	.set    SetBlackPal, 0x08013B3C + 1

	.global Tsa_Ekrdk_0
	.set    Tsa_Ekrdk_0, 0x08848B28

	.global EkrDemonkingObj_StartDissolveProc
	.type   EkrDemonkingObj_StartDissolveProc, %function
	.thumb_func
	.set    EkrDemonkingObj_StartDissolveProc, 0x0807A310 + 1

	.global gBanimmisc_9
	.set    gBanimmisc_9, 0x08856E5C

	.global GetAISLayerId
	.type   GetAISLayerId, %function
	.thumb_func
	.set    GetAISLayerId, 0x0805AEF8 + 1

	.global StartClassReelSpellAnim
	.type   StartClassReelSpellAnim, %function
	.thumb_func
	.set    StartClassReelSpellAnim, 0x08071104 + 1

	.global RegisterAISSheetGraphics
	.type   RegisterAISSheetGraphics, %function
	.thumb_func
	.set    RegisterAISSheetGraphics, 0x0805A6E0 + 1

	.global NewEkrChienCHR
	.type   NewEkrChienCHR, %function
	.thumb_func
	.set    NewEkrChienCHR, 0x0805A6B0 + 1

	.global banim_data
	.set    banim_data, 0x08C00008

	.global BanimDefaultModeConfig
	.set    BanimDefaultModeConfig, 0x080DFF00

	.global BanimScr_DefaultAnim
	.set    BanimScr_DefaultAnim, 0x085E3F8C

	.global AnimCreate
	.type   AnimCreate, %function
	.thumb_func
	.set    AnimCreate, 0x08004E50 + 1

	.global character_battle_animation_palette_table
	.set    character_battle_animation_palette_table, 0x08EF8008

	.global Img_DanceringFx
	.set    Img_DanceringFx, 0x085D0494

	.global Pal_DanceringFx
	.set    Pal_DanceringFx, 0x085D14B4

	.global Tsa_DanceringFx
	.set    Tsa_DanceringFx, 0x085D1278

	.global gBattleStats
	.set    gBattleStats, 0x0203A4D0

	.global ProcBmFx_CommonEnd
	.type   ProcBmFx_CommonEnd, %function
	.thumb_func
	.set    ProcBmFx_CommonEnd, 0x08021360 + 1

	.global pMADebugInfoData
	.set    pMADebugInfoData, 0x08A13E98

	.global Text_InsertDrawNumberOrBlank
	.type   Text_InsertDrawNumberOrBlank, %function
	.thumb_func
	.set    Text_InsertDrawNumberOrBlank, 0x080043DC + 1

	.global MADebugStrings1
	.set    MADebugStrings1, 0x08A13DF8

	.global ProcScr_DebugMonitor
	.set    ProcScr_DebugMonitor, 0x085C2EDC

	.global ResetText
	.type   ResetText, %function
	.thumb_func
	.set    ResetText, 0x08003BC4 + 1

	.global MADebugStrings2
	.set    MADebugStrings2, 0x08A13E70

	.global gMapanimDebug_0
	.set    gMapanimDebug_0, 0x08A13E20

	.global ClearBattleHits
	.type   ClearBattleHits, %function
	.thumb_func
	.set    ClearBattleHits, 0x0802AE00 + 1

	.global gBattleHitArray
	.set    gBattleHitArray, 0x0203A5E8

	.global BeginBattleMapAnims
	.type   BeginBattleMapAnims, %function
	.thumb_func
	.set    BeginBattleMapAnims, 0x0807DB9C + 1

	.global AddAttr2dBitMap
	.type   AddAttr2dBitMap, %function
	.thumb_func
	.set    AddAttr2dBitMap, 0x08001570 + 1

	.global gMapanimEventcall_0
	.set    gMapanimEventcall_0, 0x081F523C

	.global gMapanimEventcall_1
	.set    gMapanimEventcall_1, 0x081F5244

	.global gMapanimEventcall_2
	.set    gMapanimEventcall_2, 0x081F5246

	.global ProcScr_MapanimEventcall_1
	.set    ProcScr_MapanimEventcall_1, 0x08A14A1C

	.global ProcScr_MapanimEventcall_2
	.set    ProcScr_MapanimEventcall_2, 0x08A14ABC

	.global ProcScr_MapanimEventcall_3
	.set    ProcScr_MapanimEventcall_3, 0x08A14B14

	.global gUnk_57
	.set    gUnk_57, 0x03001C74

	.global MapEventcallFx2_HBlankWobble
	.type   MapEventcallFx2_HBlankWobble, %function
	.thumb_func
	.set    MapEventcallFx2_HBlankWobble, 0x08082748 + 1

	.global gMapanimEventcall_23
	.set    gMapanimEventcall_23, 0x08A28A48

	.global gMapanimEventcall_79
	.set    gMapanimEventcall_79, 0x08A42A60

	.global gMapanimEventcall_135
	.set    gMapanimEventcall_135, 0x08A43160

	.global gMapanimEventcall_24
	.set    gMapanimEventcall_24, 0x08A2904C

	.global gMapanimEventcall_80
	.set    gMapanimEventcall_80, 0x08A42A80

	.global gMapanimEventcall_136
	.set    gMapanimEventcall_136, 0x08A432B8

	.global gMapanimEventcall_25
	.set    gMapanimEventcall_25, 0x08A29760

	.global gMapanimEventcall_81
	.set    gMapanimEventcall_81, 0x08A42AA0

	.global gMapanimEventcall_137
	.set    gMapanimEventcall_137, 0x08A43448

	.global gMapanimEventcall_26
	.set    gMapanimEventcall_26, 0x08A29F64

	.global gMapanimEventcall_82
	.set    gMapanimEventcall_82, 0x08A42AC0

	.global gMapanimEventcall_138
	.set    gMapanimEventcall_138, 0x08A43600

	.global gMapanimEventcall_27
	.set    gMapanimEventcall_27, 0x08A2A818

	.global gMapanimEventcall_83
	.set    gMapanimEventcall_83, 0x08A42AE0

	.global gMapanimEventcall_139
	.set    gMapanimEventcall_139, 0x08A437B8

	.global gMapanimEventcall_28
	.set    gMapanimEventcall_28, 0x08A2B060

	.global gMapanimEventcall_84
	.set    gMapanimEventcall_84, 0x08A42B00

	.global gMapanimEventcall_140
	.set    gMapanimEventcall_140, 0x08A43960

	.global gMapanimEventcall_29
	.set    gMapanimEventcall_29, 0x08A2B950

	.global gMapanimEventcall_85
	.set    gMapanimEventcall_85, 0x08A42B20

	.global gMapanimEventcall_141
	.set    gMapanimEventcall_141, 0x08A43B28

	.global gMapanimEventcall_30
	.set    gMapanimEventcall_30, 0x08A2C3F0

	.global gMapanimEventcall_86
	.set    gMapanimEventcall_86, 0x08A42B40

	.global gMapanimEventcall_142
	.set    gMapanimEventcall_142, 0x08A43D38

	.global gMapanimEventcall_31
	.set    gMapanimEventcall_31, 0x08A2CF0C

	.global gMapanimEventcall_87
	.set    gMapanimEventcall_87, 0x08A42B60

	.global gMapanimEventcall_143
	.set    gMapanimEventcall_143, 0x08A43F54

	.global gMapanimEventcall_32
	.set    gMapanimEventcall_32, 0x08A2DA3C

	.global gMapanimEventcall_88
	.set    gMapanimEventcall_88, 0x08A42B80

	.global gMapanimEventcall_144
	.set    gMapanimEventcall_144, 0x08A4415C

	.global gMapanimEventcall_33
	.set    gMapanimEventcall_33, 0x08A2E570

	.global gMapanimEventcall_89
	.set    gMapanimEventcall_89, 0x08A42BA0

	.global gMapanimEventcall_145
	.set    gMapanimEventcall_145, 0x08A44380

	.global gMapanimEventcall_34
	.set    gMapanimEventcall_34, 0x08A2F118

	.global gMapanimEventcall_90
	.set    gMapanimEventcall_90, 0x08A42BC0

	.global gMapanimEventcall_146
	.set    gMapanimEventcall_146, 0x08A445A8

	.global gMapanimEventcall_35
	.set    gMapanimEventcall_35, 0x08A2FC84

	.global gMapanimEventcall_91
	.set    gMapanimEventcall_91, 0x08A42BE0

	.global gMapanimEventcall_147
	.set    gMapanimEventcall_147, 0x08A447D8

	.global gMapanimEventcall_36
	.set    gMapanimEventcall_36, 0x08A305EC

	.global gMapanimEventcall_92
	.set    gMapanimEventcall_92, 0x08A42C00

	.global gMapanimEventcall_148
	.set    gMapanimEventcall_148, 0x08A449B4

	.global gMapanimEventcall_37
	.set    gMapanimEventcall_37, 0x08A30F48

	.global gMapanimEventcall_93
	.set    gMapanimEventcall_93, 0x08A42C20

	.global gMapanimEventcall_149
	.set    gMapanimEventcall_149, 0x08A44B88

	.global gMapanimEventcall_38
	.set    gMapanimEventcall_38, 0x08A31818

	.global gMapanimEventcall_94
	.set    gMapanimEventcall_94, 0x08A42C40

	.global gMapanimEventcall_150
	.set    gMapanimEventcall_150, 0x08A44D4C

	.global gMapanimEventcall_39
	.set    gMapanimEventcall_39, 0x08A32230

	.global gMapanimEventcall_95
	.set    gMapanimEventcall_95, 0x08A42C60

	.global gMapanimEventcall_151
	.set    gMapanimEventcall_151, 0x08A44F34

	.global gMapanimEventcall_40
	.set    gMapanimEventcall_40, 0x08A32B04

	.global gMapanimEventcall_96
	.set    gMapanimEventcall_96, 0x08A42C80

	.global gMapanimEventcall_152
	.set    gMapanimEventcall_152, 0x08A450E8

	.global gMapanimEventcall_41
	.set    gMapanimEventcall_41, 0x08A33278

	.global gMapanimEventcall_97
	.set    gMapanimEventcall_97, 0x08A42CA0

	.global gMapanimEventcall_153
	.set    gMapanimEventcall_153, 0x08A45284

	.global gMapanimEventcall_42
	.set    gMapanimEventcall_42, 0x08A3392C

	.global gMapanimEventcall_98
	.set    gMapanimEventcall_98, 0x08A42CC0

	.global gMapanimEventcall_154
	.set    gMapanimEventcall_154, 0x08A453FC

	.global gMapanimEventcall_43
	.set    gMapanimEventcall_43, 0x08A34030

	.global gMapanimEventcall_99
	.set    gMapanimEventcall_99, 0x08A42CE0

	.global gMapanimEventcall_155
	.set    gMapanimEventcall_155, 0x08A45554

	.global gMapanimEventcall_44
	.set    gMapanimEventcall_44, 0x08A34570

	.global gMapanimEventcall_100
	.set    gMapanimEventcall_100, 0x08A42D00

	.global gMapanimEventcall_156
	.set    gMapanimEventcall_156, 0x08A45664

	.global gMapanimEventcall_45
	.set    gMapanimEventcall_45, 0x08A34B04

	.global gMapanimEventcall_101
	.set    gMapanimEventcall_101, 0x08A42D20

	.global gMapanimEventcall_157
	.set    gMapanimEventcall_157, 0x08A45788

	.global gMapanimEventcall_46
	.set    gMapanimEventcall_46, 0x08A34EBC

	.global gMapanimEventcall_102
	.set    gMapanimEventcall_102, 0x08A42D40

	.global gMapanimEventcall_158
	.set    gMapanimEventcall_158, 0x08A4589C

	.global gMapanimEventcall_47
	.set    gMapanimEventcall_47, 0x08A34F68

	.global gMapanimEventcall_103
	.set    gMapanimEventcall_103, 0x08A42D60

	.global gMapanimEventcall_159
	.set    gMapanimEventcall_159, 0x08A45958

	.global gMapanimEventcall_48
	.set    gMapanimEventcall_48, 0x08A34FE4

	.global gMapanimEventcall_104
	.set    gMapanimEventcall_104, 0x08A42D80

	.global gMapanimEventcall_160
	.set    gMapanimEventcall_160, 0x08A45A14

	.global gMapanimEventcall_49
	.set    gMapanimEventcall_49, 0x08A35054

	.global gMapanimEventcall_105
	.set    gMapanimEventcall_105, 0x08A42DA0

	.global gMapanimEventcall_161
	.set    gMapanimEventcall_161, 0x08A45AC8

	.global gMapanimEventcall_50
	.set    gMapanimEventcall_50, 0x08A354C0

	.global gMapanimEventcall_106
	.set    gMapanimEventcall_106, 0x08A42DC0

	.global gMapanimEventcall_162
	.set    gMapanimEventcall_162, 0x08A45BC8

	.global gMapanimEventcall_51
	.set    gMapanimEventcall_51, 0x08A359B0

	.global gMapanimEventcall_107
	.set    gMapanimEventcall_107, 0x08A42DE0

	.global gMapanimEventcall_163
	.set    gMapanimEventcall_163, 0x08A45CE0

	.global gMapanimEventcall_52
	.set    gMapanimEventcall_52, 0x08A35CFC

	.global gMapanimEventcall_108
	.set    gMapanimEventcall_108, 0x08A42E00

	.global gMapanimEventcall_164
	.set    gMapanimEventcall_164, 0x08A45DEC

	.global gMapanimEventcall_53
	.set    gMapanimEventcall_53, 0x08A35DBC

	.global gMapanimEventcall_109
	.set    gMapanimEventcall_109, 0x08A42E20

	.global gMapanimEventcall_165
	.set    gMapanimEventcall_165, 0x08A45EA8

	.global gMapanimEventcall_54
	.set    gMapanimEventcall_54, 0x08A35E60

	.global gMapanimEventcall_110
	.set    gMapanimEventcall_110, 0x08A42E40

	.global gMapanimEventcall_166
	.set    gMapanimEventcall_166, 0x08A45F68

	.global gMapanimEventcall_55
	.set    gMapanimEventcall_55, 0x08A365F8

	.global gMapanimEventcall_111
	.set    gMapanimEventcall_111, 0x08A42E60

	.global gMapanimEventcall_167
	.set    gMapanimEventcall_167, 0x08A460A8

	.global gMapanimEventcall_56
	.set    gMapanimEventcall_56, 0x08A36C74

	.global gMapanimEventcall_112
	.set    gMapanimEventcall_112, 0x08A42E80

	.global gMapanimEventcall_168
	.set    gMapanimEventcall_168, 0x08A461E0

	.global gMapanimEventcall_57
	.set    gMapanimEventcall_57, 0x08A370E0

	.global gMapanimEventcall_113
	.set    gMapanimEventcall_113, 0x08A42EA0

	.global gMapanimEventcall_169
	.set    gMapanimEventcall_169, 0x08A46318

	.global gMapanimEventcall_58
	.set    gMapanimEventcall_58, 0x08A371A8

	.global gMapanimEventcall_114
	.set    gMapanimEventcall_114, 0x08A42EC0

	.global gMapanimEventcall_170
	.set    gMapanimEventcall_170, 0x08A463D4

	.global gMapanimEventcall_59
	.set    gMapanimEventcall_59, 0x08A37904

	.global gMapanimEventcall_115
	.set    gMapanimEventcall_115, 0x08A42EE0

	.global gMapanimEventcall_171
	.set    gMapanimEventcall_171, 0x08A46524

	.global gMapanimEventcall_60
	.set    gMapanimEventcall_60, 0x08A380B4

	.global gMapanimEventcall_116
	.set    gMapanimEventcall_116, 0x08A42F00

	.global gMapanimEventcall_172
	.set    gMapanimEventcall_172, 0x08A46678

	.global gMapanimEventcall_61
	.set    gMapanimEventcall_61, 0x08A38AC8

	.global gMapanimEventcall_117
	.set    gMapanimEventcall_117, 0x08A42F20

	.global gMapanimEventcall_173
	.set    gMapanimEventcall_173, 0x08A467F8

	.global gMapanimEventcall_62
	.set    gMapanimEventcall_62, 0x08A3944C

	.global gMapanimEventcall_118
	.set    gMapanimEventcall_118, 0x08A42F40

	.global gMapanimEventcall_174
	.set    gMapanimEventcall_174, 0x08A46980

	.global gMapanimEventcall_63
	.set    gMapanimEventcall_63, 0x08A3A0CC

	.global gMapanimEventcall_119
	.set    gMapanimEventcall_119, 0x08A42F60

	.global gMapanimEventcall_175
	.set    gMapanimEventcall_175, 0x08A46B74

	.global gMapanimEventcall_64
	.set    gMapanimEventcall_64, 0x08A3AACC

	.global gMapanimEventcall_120
	.set    gMapanimEventcall_120, 0x08A42F80

	.global gMapanimEventcall_176
	.set    gMapanimEventcall_176, 0x08A46D58

	.global gMapanimEventcall_65
	.set    gMapanimEventcall_65, 0x08A3B098

	.global gMapanimEventcall_121
	.set    gMapanimEventcall_121, 0x08A42FA0

	.global gMapanimEventcall_177
	.set    gMapanimEventcall_177, 0x08A46E7C

	.global gMapanimEventcall_66
	.set    gMapanimEventcall_66, 0x08A3BE38

	.global gMapanimEventcall_122
	.set    gMapanimEventcall_122, 0x08A42FC0

	.global gMapanimEventcall_178
	.set    gMapanimEventcall_178, 0x08A4712C

	.global gMapanimEventcall_67
	.set    gMapanimEventcall_67, 0x08A3D0B0

	.global gMapanimEventcall_123
	.set    gMapanimEventcall_123, 0x08A42FE0

	.global gMapanimEventcall_179
	.set    gMapanimEventcall_179, 0x08A474A4

	.global gMapanimEventcall_68
	.set    gMapanimEventcall_68, 0x08A3D514

	.global gMapanimEventcall_124
	.set    gMapanimEventcall_124, 0x08A43000

	.global gMapanimEventcall_180
	.set    gMapanimEventcall_180, 0x08A47594

	.global gMapanimEventcall_69
	.set    gMapanimEventcall_69, 0x08A3DCD8

	.global gMapanimEventcall_125
	.set    gMapanimEventcall_125, 0x08A43020

	.global gMapanimEventcall_181
	.set    gMapanimEventcall_181, 0x08A476D4

	.global gMapanimEventcall_70
	.set    gMapanimEventcall_70, 0x08A3E6C0

	.global gMapanimEventcall_126
	.set    gMapanimEventcall_126, 0x08A43040

	.global gMapanimEventcall_182
	.set    gMapanimEventcall_182, 0x08A47864

	.global gMapanimEventcall_71
	.set    gMapanimEventcall_71, 0x08A3F21C

	.global gMapanimEventcall_127
	.set    gMapanimEventcall_127, 0x08A43060

	.global gMapanimEventcall_183
	.set    gMapanimEventcall_183, 0x08A47A3C

	.global gMapanimEventcall_72
	.set    gMapanimEventcall_72, 0x08A3FE48

	.global gMapanimEventcall_128
	.set    gMapanimEventcall_128, 0x08A43080

	.global gMapanimEventcall_184
	.set    gMapanimEventcall_184, 0x08A47C44

	.global gMapanimEventcall_73
	.set    gMapanimEventcall_73, 0x08A40A14

	.global gMapanimEventcall_129
	.set    gMapanimEventcall_129, 0x08A430A0

	.global gMapanimEventcall_185
	.set    gMapanimEventcall_185, 0x08A47E54

	.global gMapanimEventcall_74
	.set    gMapanimEventcall_74, 0x08A41490

	.global gMapanimEventcall_130
	.set    gMapanimEventcall_130, 0x08A430C0

	.global gMapanimEventcall_186
	.set    gMapanimEventcall_186, 0x08A4803C

	.global gMapanimEventcall_75
	.set    gMapanimEventcall_75, 0x08A41CD0

	.global gMapanimEventcall_131
	.set    gMapanimEventcall_131, 0x08A430E0

	.global gMapanimEventcall_187
	.set    gMapanimEventcall_187, 0x08A48200

	.global gMapanimEventcall_76
	.set    gMapanimEventcall_76, 0x08A4232C

	.global gMapanimEventcall_132
	.set    gMapanimEventcall_132, 0x08A43100

	.global gMapanimEventcall_188
	.set    gMapanimEventcall_188, 0x08A4838C

	.global gMapanimEventcall_77
	.set    gMapanimEventcall_77, 0x08A42768

	.global gMapanimEventcall_133
	.set    gMapanimEventcall_133, 0x08A43120

	.global gMapanimEventcall_189
	.set    gMapanimEventcall_189, 0x08A484D0

	.global gMapanimEventcall_78
	.set    gMapanimEventcall_78, 0x08A42994

	.global gMapanimEventcall_134
	.set    gMapanimEventcall_134, 0x08A43140

	.global gMapanimEventcall_190
	.set    gMapanimEventcall_190, 0x08A485D0

	.global MapAnim_DrawNumber
	.type   MapAnim_DrawNumber, %function
	.thumb_func
	.set    MapAnim_DrawNumber, 0x0807DD70 + 1

	.global MapAnim_DrawBar
	.type   MapAnim_DrawBar, %function
	.thumb_func
	.set    MapAnim_DrawBar, 0x0807DE88 + 1

	.global gMapanimExpbar_0
	.set    gMapanimExpbar_0, 0x08A13D48

	.global Img_EkrExpBar
	.set    Img_EkrExpBar, 0x0885729C

	.global Img_EkrExpBarChange
	.set    Img_EkrExpBarChange, 0x0885761C

	.global Img_BarNumfx
	.set    Img_BarNumfx, 0x0885791C

	.global Pal_ExpBar
	.set    Pal_ExpBar, 0x08857AE8

	.global gMapanimLevelup_0
	.set    gMapanimLevelup_0, 0x08A1DB20

	.global ProcScr_ManimLevelUp
	.set    ProcScr_ManimLevelUp, 0x08A145FC

	.global PutManimLevelUpFrame
	.type   PutManimLevelUpFrame, %function
	.thumb_func
	.set    PutManimLevelUpFrame, 0x08080DD8 + 1

	.global PutManimLevelUpStat
	.type   PutManimLevelUpStat, %function
	.thumb_func
	.set    PutManimLevelUpStat, 0x08080EE4 + 1

	.global StartFace
	.type   StartFace, %function
	.thumb_func
	.set    StartFace, 0x08005544 + 1

	.global StartManimLevelUpStatGainLabels
	.type   StartManimLevelUpStatGainLabels, %function
	.thumb_func
	.set    StartManimLevelUpStatGainLabels, 0x08081138 + 1

	.global gFaces
	.set    gFaces, 0x03004920

	.global ProcScr_MapAnimDefaultItemEffect
	.set    ProcScr_MapAnimDefaultItemEffect, 0x08A14DEC

	.global StartMuActionAnim
	.type   StartMuActionAnim, %function
	.thumb_func
	.set    StartMuActionAnim, 0x0807BCC4 + 1

	.global StartMuDelayedFaceDefender
	.type   StartMuDelayedFaceDefender, %function
	.thumb_func
	.set    StartMuDelayedFaceDefender, 0x0807BCFC + 1

	.global CallDelayed
	.type   CallDelayed, %function
	.thumb_func
	.set    CallDelayed, 0x080148F0 + 1

	.global AP_SwitchAnimation
	.type   AP_SwitchAnimation, %function
	.thumb_func
	.set    AP_SwitchAnimation, 0x08009408 + 1

	.global StartMuSpeedUpAnim
	.type   StartMuSpeedUpAnim, %function
	.thumb_func
	.set    StartMuSpeedUpAnim, 0x0807BD58 + 1

	.global DeleteAllPaletteAnimator
	.type   DeleteAllPaletteAnimator, %function
	.thumb_func
	.set    DeleteAllPaletteAnimator, 0x08014494 + 1

	.global ProcScr_MapLatonaShiningfx
	.set    ProcScr_MapLatonaShiningfx, 0x08A140C8

	.global New6C_SummonGfx
	.type   New6C_SummonGfx, %function
	.thumb_func
	.set    New6C_SummonGfx, 0x0808306C + 1

	.global SetNextGameActionId
	.type   SetNextGameActionId, %function
	.thumb_func
	.set    SetNextGameActionId, 0x08009EB0 + 1

	.global gOpAnimSt
	.set    gOpAnimSt, 0x02022188

	.global ProcScr_OpAnimfxTerminator
	.set    ProcScr_OpAnimfxTerminator, 0x08B3F298

	.global Sqrt
	.type   Sqrt, %function
	.thumb_func
	.set    Sqrt, 0x080D63D4 + 1

	.global ProcScr_WorldMapFaceHolder
	.set    ProcScr_WorldMapFaceHolder, 0x08AC10A0

	.global gGuideTable
	.set    gGuideTable, 0x08BB2E60

	.global AiGetInRangeCombatPositionScoreComponent
	.type   AiGetInRangeCombatPositionScoreComponent, %function
	.thumb_func
	.set    AiGetInRangeCombatPositionScoreComponent, 0x0803E17C + 1

	.global AiGetTerrainCombatPositionScoreComponent
	.type   AiGetTerrainCombatPositionScoreComponent, %function
	.thumb_func
	.set    AiGetTerrainCombatPositionScoreComponent, 0x0803E1CC + 1

	.global AiGetFriendZoneCombatPositionScoreComponent
	.type   AiGetFriendZoneCombatPositionScoreComponent, %function
	.thumb_func
	.set    AiGetFriendZoneCombatPositionScoreComponent, 0x0803E20C + 1

	.global gBmMapOther
	.set    gBmMapOther, 0x0202E4EC

	.global BattleGenerateSimulation
	.type   BattleGenerateSimulation, %function
	.thumb_func
	.set    BattleGenerateSimulation, 0x0802A2A4 + 1

	.global BattleGenerateBallistaSimulation
	.type   BattleGenerateBallistaSimulation, %function
	.thumb_func
	.set    BattleGenerateBallistaSimulation, 0x0802A2F0 + 1

	.global AiComputeCombatScore
	.type   AiComputeCombatScore, %function
	.thumb_func
	.set    AiComputeCombatScore, 0x0803E108 + 1

	.global WriteFadedPaletteFromArchive
	.type   WriteFadedPaletteFromArchive, %function
	.thumb_func
	.set    WriteFadedPaletteFromArchive, 0x08013608 + 1

	.global GetPalFadeStClkEnd1
	.type   GetPalFadeStClkEnd1, %function
	.thumb_func
	.set    GetPalFadeStClkEnd1, 0x08013560 + 1

	.global GetPalFadeStClkEnd2
	.type   GetPalFadeStClkEnd2, %function
	.thumb_func
	.set    GetPalFadeStClkEnd2, 0x0801356C + 1

	.global GetPalFadeStClkEnd3
	.type   GetPalFadeStClkEnd3, %function
	.thumb_func
	.set    GetPalFadeStClkEnd3, 0x0801357C + 1

	.global ArchiveCurrentPalettes
	.type   ArchiveCurrentPalettes, %function
	.thumb_func
	.set    ArchiveCurrentPalettes, 0x0801358C + 1

	.global ProcScr_EventFadefx
	.set    ProcScr_EventFadefx, 0x085BA2E4

	.global ProcScr_menu_scroll
	.set    ProcScr_menu_scroll, 0x08A9454C

	.global Pal_MenuScrollBar
	.set    Pal_MenuScrollBar, 0x08A964FC

	.global Img_MenuScrollBar
	.set    Img_MenuScrollBar, 0x08A9645C

	.global LinkTargets
	.type   LinkTargets, %function
	.thumb_func
	.set    LinkTargets, 0x08050684 + 1

	.global GetFurthestTargetDistance
	.type   GetFurthestTargetDistance, %function
	.thumb_func
	.set    GetFurthestTargetDistance, 0x08050970 + 1

	.global PutUnitSprite
	.type   PutUnitSprite, %function
	.thumb_func
	.set    PutUnitSprite, 0x08027AF4 + 1

	.global gObject_16x16
	.set    gObject_16x16, 0x085B8CE4

	.global PrepUnitSwapProc_Init
	.type   PrepUnitSwapProc_Init, %function
	.thumb_func
	.set    PrepUnitSwapProc_Init, 0x0801E6BC + 1

	.global GetBattleAnimRoundTypeFlags
	.type   GetBattleAnimRoundTypeFlags, %function
	.thumb_func
	.set    GetBattleAnimRoundTypeFlags, 0x08059864 + 1

	.global NewEfxDamageMojiEffect
	.type   NewEfxDamageMojiEffect, %function
	.thumb_func
	.set    NewEfxDamageMojiEffect, 0x0806E940 + 1

	.global gEkrHpBarCount
	.set    gEkrHpBarCount, 0x02017728

	.global ProcScr_efxNoDamage
	.set    ProcScr_efxNoDamage, 0x085E3894

	.global gEfxHpLutOff
	.set    gEfxHpLutOff, 0x0203E14E

	.global ProcScr_efxNoDamageYure
	.set    ProcScr_efxNoDamageYure, 0x085E38BC

	.global SpellFx_RegisterBgGfx
	.type   SpellFx_RegisterBgGfx, %function
	.thumb_func
	.set    SpellFx_RegisterBgGfx, 0x080567B8 + 1

	.global SpellFx_SetSomeColorEffect
	.type   SpellFx_SetSomeColorEffect, %function
	.thumb_func
	.set    SpellFx_SetSomeColorEffect, 0x08056158 + 1

	.global ProcScr_efxSkillCommonBG
	.set    ProcScr_efxSkillCommonBG, 0x08603B18

	.global FrameLut_EfxSkill
	.set    FrameLut_EfxSkill, 0x080E49B6

	.global TsaLut_EfxSkill
	.set    TsaLut_EfxSkill, 0x08603A58

	.global ImgLut_EfxSkill
	.set    ImgLut_EfxSkill, 0x08603A98

	.global PalLut_EfxSkill
	.set    PalLut_EfxSkill, 0x08603AD8

	.global GetEfxHp
	.type   GetEfxHp, %function
	.thumb_func
	.set    GetEfxHp, 0x08059890 + 1

	.global EkrPrepareBanimfx
	.type   EkrPrepareBanimfx, %function
	.thumb_func
	.set    EkrPrepareBanimfx, 0x08059810 + 1

	.global gEkrSpellAnimIndex
	.set    gEkrSpellAnimIndex, 0x0203E114

	.global SwitchAISFrameDataFromBARoundType
	.type   SwitchAISFrameDataFromBARoundType, %function
	.thumb_func
	.set    SwitchAISFrameDataFromBARoundType, 0x0805AE20 + 1

	.global AddEkrDragonStatusAttr
	.type   AddEkrDragonStatusAttr, %function
	.thumb_func
	.set    AddEkrDragonStatusAttr, 0x08072004 + 1

	.global SetEkrDragonStatusType
	.type   SetEkrDragonStatusType, %function
	.thumb_func
	.set    SetEkrDragonStatusType, 0x08072034 + 1

	.global PutBanimBG
	.type   PutBanimBG, %function
	.thumb_func
	.set    PutBanimBG, 0x08077F0C + 1

	.global EkrGauge_Set4C
	.type   EkrGauge_Set4C, %function
	.thumb_func
	.set    EkrGauge_Set4C, 0x08051ED4 + 1

	.global EkrDispUpSet4C
	.type   EkrDispUpSet4C, %function
	.thumb_func
	.set    EkrDispUpSet4C, 0x08052820 + 1

