@ Generated by scripts/gen_layout.py from layout/baseline_syms.tsv.
@ Typed symbols for baseline-resident code/data referenced by decompiled
@ source, so the linker resolves them at their JP address (Thumb BL gets
@ no interwork veneer). Do not edit by hand.

	.thumb

	.global crt0
	.type   crt0, %function
	.set    crt0, 0x080000C0

	.global memcpy
	.type   memcpy, %function
	.thumb_func
	.set    memcpy, 0x080D6908 + 1

	.global __modsi3
	.type   __modsi3, %function
	.thumb_func
	.set    __modsi3, 0x080D6690 + 1

	.global CpuFastSet
	.type   CpuFastSet, %function
	.thumb_func
	.set    CpuFastSet, 0x080D636C + 1

	.global IrqMain
	.set    IrqMain, 0x080000FC

	.global IntrMain_Buffer
	.set    IntrMain_Buffer, 0x03004100

	.global gIRQHandlers
	.set    gIRQHandlers, 0x03003090

	.global PrintDebugStringToBG
	.type   PrintDebugStringToBG, %function
	.thumb_func
	.set    PrintDebugStringToBG, 0x08003750 + 1

	.global gBuildDateTime
	.set    gBuildDateTime, 0x080DC110

	.global gYearProjectCreated
	.set    gYearProjectCreated, 0x080DC12C

	.global gPlaySt
	.set    gPlaySt, 0x0202BCEC

	.global GetUnit
	.type   GetUnit, %function
	.thumb_func
	.set    GetUnit, 0x08019108 + 1

	.global gSpellAssocData
	.set    gSpellAssocData, 0x08904164

	.global GetItemIndex
	.type   GetItemIndex, %function
	.thumb_func
	.set    GetItemIndex, 0x08017294 + 1

	.global gActiveUnit
	.set    gActiveUnit, 0x03004DF0

	.global gWorkingMovementScript
	.set    gWorkingMovementScript, 0x02033EF8

	.global GetFacingDirection
	.type   GetFacingDirection, %function
	.thumb_func
	.set    GetFacingDirection, 0x0807DD00 + 1

	.global SetAutoMuMoveScript
	.type   SetAutoMuMoveScript, %function
	.thumb_func
	.set    SetAutoMuMoveScript, 0x0807AB24 + 1

	.global ProcScr_WorldMapMain
	.set    ProcScr_WorldMapMain, 0x08AC1108

	.global gGMData
	.set    gGMData, 0x03005270

	.global AddGmPath
	.type   AddGmPath, %function
	.thumb_func
	.set    AddGmPath, 0x080C16FC + 1

	.global GmHideMuUnit
	.type   GmHideMuUnit, %function
	.thumb_func
	.set    GmHideMuUnit, 0x080C2C24 + 1

	.global GmMu_RemoveUnit
	.type   GmMu_RemoveUnit, %function
	.thumb_func
	.set    GmMu_RemoveUnit, 0x080C2B14 + 1

	.global GmShowMuUnit
	.type   GmShowMuUnit, %function
	.thumb_func
	.set    GmShowMuUnit, 0x080C2BAC + 1

	.global MapMU_SetUnitChar
	.type   MapMU_SetUnitChar, %function
	.thumb_func
	.set    MapMU_SetUnitChar, 0x080C333C + 1

	.global MapMU_SetUnitClass
	.type   MapMU_SetUnitClass, %function
	.thumb_func
	.set    MapMU_SetUnitClass, 0x080C3320 + 1

	.global MapRoute_BeginRouteTransition
	.type   MapRoute_BeginRouteTransition, %function
	.thumb_func
	.set    MapRoute_BeginRouteTransition, 0x080C10E0 + 1

	.global Proc_Find
	.type   Proc_Find, %function
	.thumb_func
	.set    Proc_Find, 0x08002DEC + 1

	.global gUnitArrayBlue
	.set    gUnitArrayBlue, 0x0202BE48

	.global ClearUnit
	.type   ClearUnit, %function
	.thumb_func
	.set    ClearUnit, 0x0801759C + 1

	.global CopyUnit
	.type   CopyUnit, %function
	.thumb_func
	.set    CopyUnit, 0x080175C4 + 1

	.global CpuSet
	.type   CpuSet, %function
	.thumb_func
	.set    CpuSet, 0x080D6370 + 1

	.global gGameClock
	.set    gGameClock, 0x03000010

	.global __udivsi3
	.type   __udivsi3, %function
	.thumb_func
	.set    __udivsi3, 0x080D67D0 + 1

	.global __umodsi3
	.type   __umodsi3, %function
	.thumb_func
	.set    __umodsi3, 0x080D6848 + 1

	.global _call_via_r3
	.type   _call_via_r3, %function
	.thumb_func
	.set    _call_via_r3, 0x080D65C8 + 1

	.global LoadGMMonsterRnState
	.type   LoadGMMonsterRnState, %function
	.thumb_func
	.set    LoadGMMonsterRnState, 0x080ABC10 + 1

	.global ReadSramFast
	.set    ReadSramFast, 0x03006790

	.global WriteSaveBlockInfo
	.type   WriteSaveBlockInfo, %function
	.thumb_func
	.set    WriteSaveBlockInfo, 0x080A79D8 + 1

	.global IsSramWorking
	.type   IsSramWorking, %function
	.thumb_func
	.set    IsSramWorking, 0x080A76F4 + 1

	.global GetNextSuspendSaveId
	.type   GetNextSuspendSaveId, %function
	.thumb_func
	.set    GetNextSuspendSaveId, 0x080AADE8 + 1

	.global GetSaveWriteAddr
	.type   GetSaveWriteAddr, %function
	.thumb_func
	.set    GetSaveWriteAddr, 0x080A7AA8 + 1

	.global GetGameClock
	.type   GetGameClock, %function
	.thumb_func
	.set    GetGameClock, 0x08000CD8 + 1

	.global WriteAndVerifySramFast
	.type   WriteAndVerifySramFast, %function
	.thumb_func
	.set    WriteAndVerifySramFast, 0x080D6548 + 1

	.global StoreRNStateToActionStruct
	.type   StoreRNStateToActionStruct, %function
	.thumb_func
	.set    StoreRNStateToActionStruct, 0x08031F38 + 1

	.global WriteSramFast
	.type   WriteSramFast, %function
	.thumb_func
	.set    WriteSramFast, 0x080D6420 + 1

	.global WritePermanentFlags
	.type   WritePermanentFlags, %function
	.thumb_func
	.set    WritePermanentFlags, 0x080A7B94 + 1

	.global WriteChapterFlags
	.type   WriteChapterFlags, %function
	.thumb_func
	.set    WriteChapterFlags, 0x080A7B74 + 1

	.global WriteSupplyItems
	.type   WriteSupplyItems, %function
	.thumb_func
	.set    WriteSupplyItems, 0x080A7C28 + 1

	.global WritePidStats
	.type   WritePidStats, %function
	.thumb_func
	.set    WritePidStats, 0x080A8CA8 + 1

	.global WriteChapterStats
	.type   WriteChapterStats, %function
	.thumb_func
	.set    WriteChapterStats, 0x080A8CCC + 1

	.global WriteTraps
	.type   WriteTraps, %function
	.thumb_func
	.set    WriteTraps, 0x080AAD88 + 1

	.global GetForceDisabledMenuItems
	.type   GetForceDisabledMenuItems, %function
	.thumb_func
	.set    GetForceDisabledMenuItems, 0x08050488 + 1

	.global WriteWorldMapStuff
	.type   WriteWorldMapStuff, %function
	.thumb_func
	.set    WriteWorldMapStuff, 0x080ABAC8 + 1

	.global SaveDungeonRecords
	.type   SaveDungeonRecords, %function
	.thumb_func
	.set    SaveDungeonRecords, 0x08037F78 + 1

	.global SaveDungeonState
	.type   SaveDungeonState, %function
	.thumb_func
	.set    SaveDungeonState, 0x08037F34 + 1

	.global GetEventSlotCounter
	.type   GetEventSlotCounter, %function
	.thumb_func
	.set    GetEventSlotCounter, 0x0800D850 + 1

	.global WriteSwappedSuspendSaveId
	.type   WriteSwappedSuspendSaveId, %function
	.thumb_func
	.set    WriteSwappedSuspendSaveId, 0x080AADF8 + 1

	.global gActionData
	.set    gActionData, 0x0203A954

	.global gGenericBuffer
	.set    gGenericBuffer, 0x02020188

	.global gUnitArrayRed
	.set    gUnitArrayRed, 0x0202CFB8

	.global gUnitArrayGreen
	.set    gUnitArrayGreen, 0x0202DDC8

	.global gBmSt
	.set    gBmSt, 0x0202BCAC

	.global GetSaveReadAddr
	.type   GetSaveReadAddr, %function
	.thumb_func
	.set    GetSaveReadAddr, 0x080A7B58 + 1

	.global SetGameTime
	.type   SetGameTime, %function
	.thumb_func
	.set    SetGameTime, 0x08000CE4 + 1

	.global LoadRNStateFromActionStruct
	.type   LoadRNStateFromActionStruct, %function
	.thumb_func
	.set    LoadRNStateFromActionStruct, 0x08031F48 + 1

	.global InitUnits
	.type   InitUnits, %function
	.thumb_func
	.set    InitUnits, 0x0801756C + 1

	.global ReadPidStats
	.type   ReadPidStats, %function
	.thumb_func
	.set    ReadPidStats, 0x080A8C60 + 1

	.global ReadChapterStats
	.type   ReadChapterStats, %function
	.thumb_func
	.set    ReadChapterStats, 0x080A8C8C + 1

	.global ReadSupplyItems
	.type   ReadSupplyItems, %function
	.thumb_func
	.set    ReadSupplyItems, 0x080A7CB0 + 1

	.global ReadPermanentFlags
	.type   ReadPermanentFlags, %function
	.thumb_func
	.set    ReadPermanentFlags, 0x080A7BDC + 1

	.global ReadChapterFlags
	.type   ReadChapterFlags, %function
	.thumb_func
	.set    ReadChapterFlags, 0x080A7BB4 + 1

	.global ReadTraps
	.type   ReadTraps, %function
	.thumb_func
	.set    ReadTraps, 0x080AADA4 + 1

	.global SetForceDisabledMenuItems
	.type   SetForceDisabledMenuItems, %function
	.thumb_func
	.set    SetForceDisabledMenuItems, 0x080504C8 + 1

	.global ReadWorldMapStuff
	.type   ReadWorldMapStuff, %function
	.thumb_func
	.set    ReadWorldMapStuff, 0x080ABB50 + 1

	.global LoadDungeonRecords
	.type   LoadDungeonRecords, %function
	.thumb_func
	.set    LoadDungeonRecords, 0x08037F90 + 1

	.global LoadDungeonState
	.type   LoadDungeonState, %function
	.thumb_func
	.set    LoadDungeonState, 0x08037F5C + 1

	.global SetEventSlotCounter
	.type   SetEventSlotCounter, %function
	.thumb_func
	.set    SetEventSlotCounter, 0x0800D844 + 1

	.global LoadSavedBonusClaimFlags
	.type   LoadSavedBonusClaimFlags, %function
	.thumb_func
	.set    LoadSavedBonusClaimFlags, 0x080A9C64 + 1

	.global SetBonusContentClaimFlags
	.type   SetBonusContentClaimFlags, %function
	.thumb_func
	.set    SetBonusContentClaimFlags, 0x080A9778 + 1

	.global GetLastSuspendSaveId
	.type   GetLastSuspendSaveId, %function
	.thumb_func
	.set    GetLastSuspendSaveId, 0x080AADC8 + 1

	.global ReadSaveBlockInfo
	.type   ReadSaveBlockInfo, %function
	.thumb_func
	.set    ReadSaveBlockInfo, 0x080A793C + 1

	.global ReadGameSavePlaySt
	.type   ReadGameSavePlaySt, %function
	.thumb_func
	.set    ReadGameSavePlaySt, 0x080A9C44 + 1

	.global GetCharacterData
	.type   GetCharacterData, %function
	.thumb_func
	.set    GetCharacterData, 0x0801913C + 1

	.global GetClassData
	.type   GetClassData, %function
	.thumb_func
	.set    GetClassData, 0x0801911C + 1

	.global gBmMapTerrain
	.set    gBmMapTerrain, 0x0202E4D8

	.global RefreshEntityBmMaps
	.type   RefreshEntityBmMaps, %function
	.thumb_func
	.set    RefreshEntityBmMaps, 0x08019ECC + 1

	.global RefreshUnitSprites
	.type   RefreshUnitSprites, %function
	.thumb_func
	.set    RefreshUnitSprites, 0x08027144 + 1

	.global AddTarget
	.type   AddTarget, %function
	.thumb_func
	.set    AddTarget, 0x08050630 + 1

	.global gBmMapUnit
	.set    gBmMapUnit, 0x0202E4D4

	.global gBmMapSize
	.set    gBmMapSize, 0x0202E4D0

	.global _call_via_r0
	.type   _call_via_r0, %function
	.thumb_func
	.set    _call_via_r0, 0x080D65BC + 1

	.global Proc_Break
	.type   Proc_Break, %function
	.thumb_func
	.set    Proc_Break, 0x08002DE4 + 1

	.global CALLARM_ColorFadeTick
	.type   CALLARM_ColorFadeTick, %function
	.thumb_func
	.set    CALLARM_ColorFadeTick, 0x080DC0EC + 1

	.global EnablePaletteSync
	.type   EnablePaletteSync, %function
	.thumb_func
	.set    EnablePaletteSync, 0x08001EE4 + 1

	.global gPaletteBuffer
	.set    gPaletteBuffer, 0x020228A8

	.global ColorFadeSetStepRange
	.type   ColorFadeSetStepRange, %function
	.thumb_func
	.set    ColorFadeSetStepRange, 0x080017C8 + 1

	.global ProcScr_FadeCore
	.set    ProcScr_FadeCore, 0x085C2528

	.global SetBlendConfig
	.type   SetBlendConfig, %function
	.thumb_func
	.set    SetBlendConfig, 0x08001DF0 + 1

	.global SetBlendTargetA
	.type   SetBlendTargetA, %function
	.thumb_func
	.set    SetBlendTargetA, 0x08001E20 + 1

	.global SetBlendBackdropA
	.type   SetBlendBackdropA, %function
	.thumb_func
	.set    SetBlendBackdropA, 0x08001E98 + 1

	.global gLCDControlBuffer
	.set    gLCDControlBuffer, 0x03003020

	.global GetStringFromIndex
	.type   GetStringFromIndex, %function
	.thumb_func
	.set    GetStringFromIndex, 0x08009FA8 + 1

	.global GetUnitFromCharId
	.type   GetUnitFromCharId, %function
	.thumb_func
	.set    GetUnitFromCharId, 0x08017FB0 + 1

	.global GetUnitSupporterNum
	.type   GetUnitSupporterNum, %function
	.thumb_func
	.set    GetUnitSupporterNum, 0x0802833C + 1

