@ pad_FE4000: 110592 bytes of pure-0xFF ROM padding at JP 0x08FE4000..0x08FFF000
@ (inter-section / end-of-ROM alignment fill; NOT authored data). Emitted as an
@ explicit .fill so the final-goal metric counts it as real source instead of raw
@ incbin. .fill <n>,1,0xFF emits exactly <n> bytes of 0xFF -- byte-identical to the
@ incbin it replaces. NO .align (would grow the ROM); make compare is the oracle.
@ GENERATED by scripts/carve_padding.py (D27).

	.section .pad.FE4000, "a", %progbits
	.global pad_FE4000
pad_FE4000:
	.fill 0x1B000, 1, 0xFF
