@ pad_F2F5C0: 213600 bytes of pure-0xFF ROM padding at JP 0x08F2F5C0..0x08F63820
@ (inter-section / end-of-ROM alignment fill; NOT authored data). Emitted as an
@ explicit .fill so the final-goal metric counts it as real source instead of raw
@ incbin. .fill <n>,1,0xFF emits exactly <n> bytes of 0xFF -- byte-identical to the
@ incbin it replaces. NO .align (would grow the ROM); make compare is the oracle.
@ GENERATED by scripts/carve_padding.py (D27).

	.section .pad.F2F5C0, "a", %progbits
	.global pad_F2F5C0
pad_F2F5C0:
	.fill 0x34260, 1, 0xFF
