@ pad_E47180: 626304 bytes of pure-0xFF ROM padding at JP 0x08E47180..0x08EE0000
@ (inter-section / end-of-ROM alignment fill; NOT authored data). Emitted as an
@ explicit .fill so the final-goal metric counts it as real source instead of raw
@ incbin. .fill <n>,1,0xFF emits exactly <n> bytes of 0xFF -- byte-identical to the
@ incbin it replaces. NO .align (would grow the ROM); make compare is the oracle.
@ GENERATED by scripts/carve_padding.py (D27).

	.section .pad.E47180, "a", %progbits
	.global pad_E47180
pad_E47180:
	.fill 0x98E80, 1, 0xFF
