@ pad_EF2F18: 20712 bytes of pure-0xFF ROM padding at JP 0x08EF2F18..0x08EF8000
@ (inter-section / end-of-ROM alignment fill; NOT authored data). Emitted as an
@ explicit .fill so the final-goal metric counts it as real source instead of raw
@ incbin. .fill <n>,1,0xFF emits exactly <n> bytes of 0xFF -- byte-identical to the
@ incbin it replaces. NO .align (would grow the ROM); make compare is the oracle.
@ GENERATED by scripts/carve_padding.py (D27).

	.section .pad.EF2F18, "a", %progbits
	.global pad_EF2F18
pad_EF2F18:
	.fill 0x50E8, 1, 0xFF
