@ rom_header_080000C0: 360 bytes of raw JP ROM data at 0x080000C0..0x08000228,
@ descriptively included for byte-completeness (D29). This makes NO semantic
@ claim about the bytes — it is exactly the original ROM data at this address,
@ carried as committed source so the final-goal metric (every catch-all incbin
@ byte -> real source) reaches zero. NO .align (would grow the ROM); the bytes
@ stay byte-identical to the gap they replace and `make compare` is the oracle.
@ GENERATED by scripts/carve_incbin_residue.py.

	.section .data.residue.080000C0, "a", %progbits
	.global rom_header_080000C0
rom_header_080000C0:
	.incbin "baserom.gba", 0x0000C0, 0x168
