#!/usr/bin/env python3
"""misc_gfx -- graphics blobs from leftover mixed dat_*.s files (Phase-1).

Several `dat_*.s` files interleave real graphics (Img_/Tsa_/Pal_/gImg_/gPal_/
gGfx_) with non-graphics data. This driver carves ONLY the graphics symbols out
of the files below and leaves everything else as `.incbin "baserom.gba"`:

  dat_mapanim_nightmare.s / _monster_gorgon.s / _battleinfo.s  (map-anim FX gfx)
  dat_ui_palettes.s                                            (UI cursor/palettes)
  dat_data_opanim_gfx_p0.s / _p1.s                             (opening-anim gfx)
  dat_data_titlescreen.s / _p1.s / _p2.s                       (title-screen gfx)
  dat_phase_change.s                                           (phase-change banner)

Each blob is extracted FRESH from the JP ROM and byte-verified: LZ77 ->
DECOMPRESSED .bin (%.lz: %), uncompressed palette -> JASC .pal (-> .gbapal), and
palettes whose colors set GBA bit-15 (which gbagfx's .pal cannot reproduce) or
other verbatim blobs -> committed .bin incbin'd directly. unit_icon_pal_* in
dat_ui_palettes.s are palettes despite the non-Pal_ name (passed via extra_pal).

Usage:
  graphics/misc_gfx/extract_misc_gfx.py            # dry-run / verify
  graphics/misc_gfx/extract_misc_gfx.py --apply    # commit + rewrite + .mk
"""
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "_lib"))
import extract_mixed_gfx as m  # noqa: E402

GLOBS = [
    "asm/dat_mapanim_nightmare.s",
    "asm/dat_mapanim_monster_gorgon.s",
    "asm/dat_mapanim_battleinfo.s",
    "asm/dat_ui_palettes.s",
    "asm/dat_data_opanim_gfx_p0.s",
    "asm/dat_data_opanim_gfx_p1.s",
    "asm/dat_data_titlescreen.s",
    "asm/dat_data_titlescreen_p1.s",
    "asm/dat_data_titlescreen_p2.s",
    "asm/dat_phase_change.s",
]

HEADER = (
    "graphics/misc_gfx -- graphics blobs carved out of mixed dat_*.s files\n"
    "(map-anim FX, UI palettes, opening-anim, title-screen, phase-change). Non-\n"
    "graphics symbols in those files stay as incbin (data-table/code phases).\n"
    "LZ77 -> DECOMPRESSED .bin (%.lz: % gbagfx); uncompressed palette -> .pal\n"
    "(-> .gbapal); bit-15-set palettes / verbatim blobs -> .bin incbin'd direct.\n"
    "Auto-generated by graphics/misc_gfx/extract_misc_gfx.py."
)


def list_extra_pal_syms():
    """Palette symbols in dat_ui_palettes.s that lack a Pal_/gPal_ prefix."""
    syms = set()
    p = os.path.join(m.lib.REPO, "asm/dat_ui_palettes.s")
    for ln in open(p):
        mt = re.match(r"\s*\.global\s+(unit_icon_pal_\S+)", ln)
        if mt:
            syms.add(mt.group(1))
    return syms


if __name__ == "__main__":
    apply = "--apply" in sys.argv
    m.run(
        out_dir="graphics/misc_gfx",
        mk_name="misc_gfx.mk",
        globs=GLOBS,
        header=HEADER,
        apply=apply,
        extra_pal_syms=list_extra_pal_syms(),
    )
