# graphics/misc_gfx -- graphics blobs carved out of mixed dat_*.s files
# (map-anim FX, UI palettes, opening-anim, title-screen, phase-change). Non-
# graphics symbols in those files stay as incbin (data-table/code phases).
# LZ77 -> DECOMPRESSED .bin (%.lz: % gbagfx); uncompressed palette -> .pal
# (-> .gbapal); bit-15-set palettes / verbatim blobs -> .bin incbin'd direct.
# Auto-generated by graphics/misc_gfx/extract_misc_gfx.py.

asm/dat_data_opanim_gfx_p0.o: \
  graphics/misc_gfx/Img_OpAnimEphraim.bin.lz \
  graphics/misc_gfx/Img_OpAnimEphraimBlur1.bin.lz \
  graphics/misc_gfx/Img_OpAnimWorldMap.bin.lz \
  graphics/misc_gfx/Pal_OpAnimWorldMap.bin.lz \
  graphics/misc_gfx/Pal_OpAnimWorldMapFog.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimEphraim.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimEphraimBlur1.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimGenericCharacterBG.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimWorldMap.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimWorldMapFog.bin.lz

asm/dat_data_opanim_gfx_p1.o: \
  graphics/misc_gfx/Img_OpAnimEirikaBlur1.bin.lz \
  graphics/misc_gfx/Img_OpAnimEirikaBlur2.bin.lz \
  graphics/misc_gfx/Img_OpAnimEirikaBlur3.bin.lz \
  graphics/misc_gfx/Pal_OpAnimEphraimBlur.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimEirika.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimEirikaBlur1.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimEirikaBlur2.bin.lz \
  graphics/misc_gfx/Tsa_OpAnimEirikaBlur3.bin.lz

asm/dat_data_titlescreen.o: \
  graphics/misc_gfx/gGfx_TitleDragonForeground.bin.lz \
  graphics/misc_gfx/gGfx_TitleMainBackground_1.bin.lz \
  graphics/misc_gfx/gGfx_TitleMainBackground_2.bin.lz \
  graphics/misc_gfx/gPal_TitleDragonForeground.gbapal \
  graphics/misc_gfx/gPal_TitleMainBackground.gbapal

asm/dat_data_titlescreen_p1.o: \
  graphics/misc_gfx/gGfx_Titlescreen_0.bin.lz \
  graphics/misc_gfx/gGfx_Titlescreen_1.bin.lz \
  graphics/misc_gfx/gGfx_Titlescreen_2.bin.lz \
  graphics/misc_gfx/gPal_PressStart.gbapal \
  graphics/misc_gfx/gPal_Titlescreen_0.gbapal \
  graphics/misc_gfx/gPal_Titlescreen_1.gbapal \
  graphics/misc_gfx/gPal_Titlescreen_2.gbapal

asm/dat_data_titlescreen_p2.o: \
  graphics/misc_gfx/gGfx_TitleDemonKing.bin.lz \
  graphics/misc_gfx/gGfx_TitleLargeGlowingOrb.bin.lz \
  graphics/misc_gfx/gGfx_TitleSmallLightBubbles.bin.lz \
  graphics/misc_gfx/gPal_TitleDemonKing.gbapal \
  graphics/misc_gfx/gPal_TitleLargeGlowingOrb.gbapal \
  graphics/misc_gfx/gPal_TitleSmallLightBubbles.gbapal

src/data/mapanim/mapanim_battleinfo.o: \
  graphics/misc_gfx/Img_GmapSoguSprites.bin.lz \
  graphics/misc_gfx/Img_LinkArenaWarpFx.bin.lz \
  graphics/misc_gfx/Img_MapAnimAntitoxinPureWater.bin.lz \
  graphics/misc_gfx/Img_MapAnimBerserkfx.bin.lz \
  graphics/misc_gfx/Img_MapAnimBerserkfx_1.bin.lz \
  graphics/misc_gfx/Img_MapAnimRepairfx.bin.lz \
  graphics/misc_gfx/Img_MapAnimTorchfx.bin.lz \
  graphics/misc_gfx/Img_MapAnimUnlockBgfx.bin.lz \
  graphics/misc_gfx/Img_MapAnimUnlockObjfx.bin.lz \
  graphics/misc_gfx/Img_MapBattleInfoBox.bin.lz \
  graphics/misc_gfx/Img_MapBattleInfoHpBar.bin.lz \
  graphics/misc_gfx/Img_MapBattleInfoNum.bin.lz \
  graphics/misc_gfx/Img_PoisonAnim.bin.lz \
  graphics/misc_gfx/Img_ShopGoldBox.bin.lz \
  graphics/misc_gfx/Img_WallBreakAnim.bin.lz \
  graphics/misc_gfx/Pal_MapAnimBerserkfx.gbapal \
  graphics/misc_gfx/Pal_MapAnimBerserkfx_2.gbapal \
  graphics/misc_gfx/Pal_MapBattleInfoBlue.gbapal \
  graphics/misc_gfx/Pal_MapBattleInfoGreen.gbapal \
  graphics/misc_gfx/Pal_MapBattleInfoPurple.gbapal \
  graphics/misc_gfx/Pal_MapBattleInfoRed.gbapal \
  graphics/misc_gfx/Pal_PoisonAnim.gbapal \
  graphics/misc_gfx/Pal_WallBreakAnim.gbapal \
  graphics/misc_gfx/Tsa_MapBattleBoxGfx1.bin.lz \
  graphics/misc_gfx/Tsa_MapBattleBoxGfx2.bin.lz \
  graphics/misc_gfx/Tsa_MapBattleBoxGfx3.bin.lz \
  graphics/misc_gfx/Tsa_ShopWindows.bin.lz

src/data/mapanim/mapanim_monster_gorgon.o: \
  graphics/misc_gfx/Img_GorgonHatchCloud.bin.lz \
  graphics/misc_gfx/Img_MonsterStoneMapAnimfx.bin.lz \
  graphics/misc_gfx/Pal_GorgonHatchCloud.gbapal \
  graphics/misc_gfx/Pal_MonsterStoneMapAnimfx.gbapal \
  graphics/misc_gfx/Tsa_GorgonHatchCloud_A.bin.lz \
  graphics/misc_gfx/Tsa_GorgonHatchCloud_B.bin.lz \
  graphics/misc_gfx/Tsa_GorgonHatchCloud_C.bin.lz \
  graphics/misc_gfx/Tsa_GorgonHatchCloud_D.bin.lz \
  graphics/misc_gfx/Tsa_GorgonHatchCloud_E.bin.lz \
  graphics/misc_gfx/Tsa_GorgonHatchCloud_F.bin.lz \
  graphics/misc_gfx/Tsa_GorgonHatchCloud_G.bin.lz

src/data/mapanim/mapanim_nightmare.o: \
  graphics/misc_gfx/Img_ManimBarrierBgfx.bin.lz \
  graphics/misc_gfx/Img_NightMareMapAnimfx.bin.lz \
  graphics/misc_gfx/Pal_NightMareMapAnimfx.gbapal \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx1.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx10.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx11.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx12.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx13.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx14.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx15.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx16.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx17.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx18.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx19.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx2.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx20.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx21.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx22.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx23.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx24.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx25.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx26.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx27.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx28.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx29.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx3.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx30.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx31.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx32.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx33.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx4.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx5.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx6.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx7.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx8.bin.lz \
  graphics/misc_gfx/Tsa_NightMareMapAnimfx9.bin.lz

asm/dat_phase_change.o: \
  graphics/misc_gfx/Img_PhaseChangeEnemy.bin.lz \
  graphics/misc_gfx/Img_PhaseChangeOther.bin.lz \
  graphics/misc_gfx/Img_PhaseChangePlayer.bin.lz \
  graphics/misc_gfx/Img_PhaseChangeSquares.bin.lz \
  graphics/misc_gfx/Img_PhaseChangeUnk.bin.lz \
  graphics/misc_gfx/Pal_PhaseChangeEnemy.gbapal \
  graphics/misc_gfx/Pal_PhaseChangeOther.gbapal \
  graphics/misc_gfx/Pal_PhaseChangePlayer.gbapal \
  graphics/misc_gfx/Pal_PhaseChange_0.gbapal

asm/dat_ui_palettes.o: \
  graphics/misc_gfx/Pal_GreenTextColors.gbapal \
  graphics/misc_gfx/Pal_HelpBox.gbapal \
  graphics/misc_gfx/Pal_TalkBubble_Inverted.gbapal \
  graphics/misc_gfx/Pal_TalkText.gbapal \
  graphics/misc_gfx/Pal_Text.gbapal \
  graphics/misc_gfx/Pal_Text_Inverted.gbapal \
  graphics/misc_gfx/gImg_UiCursorHandBottom.bin.lz \
  graphics/misc_gfx/gImg_UiCursorHandTop.bin.lz \
  graphics/misc_gfx/gPal_HelpTextBox.gbapal \
  graphics/misc_gfx/gPal_LightRune.gbapal \
  graphics/misc_gfx/gPal_MapSprite.gbapal \
  graphics/misc_gfx/gPal_MapSpriteArena.gbapal \
  graphics/misc_gfx/gPal_MapSpriteSepia.gbapal \
  graphics/misc_gfx/gPal_MiscUiGraphics.gbapal \
  graphics/misc_gfx/gPal_YellowTextBox.gbapal \
  graphics/misc_gfx/unit_icon_pal_after_action.gbapal \
  graphics/misc_gfx/unit_icon_pal_enemy.gbapal \
  graphics/misc_gfx/unit_icon_pal_npc.gbapal

