#!/usr/bin/env python3
"""
Diff FE8J extracted graphics assets against the fe8u reference to surface
EXTRACTION MISTAKES (wrong width / missing-palette grayscale / wrong tile order)
as distinct from EXPECTED JP<->US differences (text / UI localization, JP art).

Oracle: fe8u's committed form. For each FE8J graphics PNG with a same-basename
fe8u twin, compare (width, height, color-mode) and — when those match — pixel
content. A (dims|mode) mismatch is UNREASONABLE (likely an extraction bug that
still round-trips byte-exact, e.g. issue #141's 8x240 grayscale opanim strips).
Same dims+mode with differing pixels is CONTENT-DIFF (usually localization —
reasonable — but listed for review).

Usage: python3 scripts/tools/asset_fe8u_diff.py [--fe8u ../fireemblem8u] [--full]
Writes docs/asset_fe8u_diff.md and prints a summary.
"""
import argparse, glob, os, sys, collections
from PIL import Image

def index_twins(fe8u_root):
    idx = collections.defaultdict(list)
    for p in glob.glob(os.path.join(fe8u_root, "graphics", "**", "*.png"), recursive=True):
        idx[os.path.basename(p)].append(p)
    return idx

def info(path):
    with Image.open(path) as im:
        return im.size[0], im.size[1], im.mode

def pixels_equal(a, b):
    try:
        with Image.open(a) as ia, Image.open(b) as ib:
            if ia.size != ib.size:
                return False
            return list(ia.convert("P").getdata()) == list(ib.convert("P").getdata())
    except Exception:
        return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fe8u", default="../fireemblem8u")
    ap.add_argument("--full", action="store_true", help="also pixel-compare same-dims/mode pairs")
    args = ap.parse_args()

    twins = index_twins(args.fe8u)
    buckets = collections.defaultdict(list)  # kind -> [(jpath, detail)]
    for jp in sorted(glob.glob("graphics/**/*.png", recursive=True)):
        base = os.path.basename(jp)
        cand = twins.get(base, [])
        if not cand:
            buckets["NO_TWIN"].append((jp, "JP-unique (no fe8u basename twin)"))
            continue
        if len(cand) > 1:
            buckets["AMBIGUOUS"].append((jp, f"{len(cand)} fe8u twins: {[os.path.relpath(c, args.fe8u) for c in cand]}"))
            continue
        up = cand[0]
        try:
            jw, jh, jm = info(jp); uw, uh, um = info(up)
        except Exception as e:
            buckets["ERROR"].append((jp, f"read error: {e}")); continue
        dims_bad = (jw, jh) != (uw, uh)
        mode_bad = jm != um
        if dims_bad or mode_bad:
            det = f"FE8J {jw}x{jh} {jm}  vs  fe8u {uw}x{uh} {um}"
            tags = []
            if dims_bad: tags.append("DIMS")
            if mode_bad: tags.append("MODE")
            # narrow-strip signature (issue #141 class): 8px wide, tall
            if jw <= 8 and jh >= 32 and (uw, uh) != (jw, jh):
                tags.append("STRIP")
            buckets["UNREASONABLE:" + "+".join(tags)].append((jp, det + f"   [twin {os.path.relpath(up, args.fe8u)}]"))
        elif args.full:
            eq = pixels_equal(jp, up)
            if eq is False:
                buckets["CONTENT_DIFF"].append((jp, f"same {jw}x{jh} {jm}, pixels differ (localization? review)"))
            elif eq is True:
                buckets["OK"].append((jp, "identical"))
        else:
            buckets["OK_DIMS"].append((jp, ""))

    # report
    lines = ["# FE8J extracted-asset diff vs fe8u\n",
             "> Generated by scripts/tools/asset_fe8u_diff.py. UNREASONABLE:* = likely",
             "> extraction mistake (wrong width / missing palette). CONTENT_DIFF = same",
             "> dims+mode, differing pixels (usually JP/US text/UI localization — expected).\n"]
    order = sorted(buckets, key=lambda k: (not k.startswith("UNREASONABLE"), k))
    print("== FE8J vs fe8u asset diff ==")
    for k in order:
        n = len(buckets[k])
        print(f"  {k:28s} {n}")
        lines.append(f"\n## {k} ({n})\n")
        for jp, det in sorted(buckets[k]):
            lines.append(f"- `{jp}` — {det}" if det else f"- `{jp}`")
    os.makedirs("docs", exist_ok=True)
    open("docs/asset_fe8u_diff.md", "w").write("\n".join(lines) + "\n")
    unreasonable = sum(len(v) for k, v in buckets.items() if k.startswith("UNREASONABLE"))
    print(f"\n  => UNREASONABLE (extraction-mistake candidates): {unreasonable}")
    print("  wrote docs/asset_fe8u_diff.md")

if __name__ == "__main__":
    main()
