#!/usr/bin/env python3
"""
Diff FE8J extracted graphics assets against the fe8u reference to surface
EXTRACTION MISTAKES (wrong width / missing-palette grayscale / wrong tile order)
as distinct from EXPECTED JP<->US differences (text / UI localization, JP art).

Oracle: fe8u's committed form. For each FE8J graphics PNG with a same-basename
fe8u twin, compare (width, height, color-mode) and — when those match — pixel
content. A (dims|mode) mismatch is UNREASONABLE (likely an extraction bug that
still round-trips byte-exact, e.g. issue #141's 8x240 grayscale opanim strips).
Same dims+mode with differing pixels is CONTENT-DIFF (usually localization —
reasonable — but listed for review).

Usage: python3 scripts/tools/asset_fe8u_diff.py [--fe8u ../fireemblem8u] [--full]
Writes docs/asset_fe8u_diff.md and prints a summary.
"""
import argparse, glob, os, sys, collections
from PIL import Image

def index_twins(fe8u_root):
    idx = collections.defaultdict(list)
    for p in glob.glob(os.path.join(fe8u_root, "graphics", "**", "*.png"), recursive=True):
        idx[os.path.basename(p)].append(p)
    return idx

def info(path):
    with Image.open(path) as im:
        return im.size[0], im.size[1], im.mode

def pixels_equal(a, b):
    try:
        with Image.open(a) as ia, Image.open(b) as ib:
            if ia.size != ib.size:
                return False
            return list(ia.convert("P").getdata()) == list(ib.convert("P").getdata())
    except Exception:
        return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fe8u", default="../fireemblem8u")
    ap.add_argument("--full", action="store_true", help="also pixel-compare same-dims/mode pairs")
    args = ap.parse_args()

    twins = index_twins(args.fe8u)
    buckets = collections.defaultdict(list)  # kind -> [(jpath, detail)]
    for jp in sorted(glob.glob("graphics/**/*.png", recursive=True)):
        base = os.path.basename(jp)
        cand = twins.get(base, [])
        if not cand:
            buckets["NO_TWIN"].append((jp, "JP-unique (no fe8u basename twin)"))
            continue
        if len(cand) > 1:
            buckets["AMBIGUOUS"].append((jp, f"{len(cand)} fe8u twins: {[os.path.relpath(c, args.fe8u) for c in cand]}"))
            continue
        up = cand[0]
        try:
            jw, jh, jm = info(jp); uw, uh, um = info(up)
        except Exception as e:
            buckets["ERROR"].append((jp, f"read error: {e}")); continue
        dims_bad = (jw, jh) != (uw, uh)
        mode_bad = jm != um
        jt = (jw // 8) * (jh // 8)
        ut = (uw // 8) * (uh // 8)
        twin = os.path.relpath(up, args.fe8u)
        if dims_bad or mode_bad:
            det = f"FE8J {jw}x{jh} {jm}  vs  fe8u {uw}x{uh} {um}   [twin {twin}]"
            if jt != ut:
                # different tile COUNT => genuine JP/US content difference (not a
                # reshapeable extraction bug); make compare being green means each
                # side is correct for its own ROM. REASONABLE.
                buckets["REASONABLE_CONTENT_JPUS"].append(
                    (jp, det + f"   (tiles JP={jt} vs US={ut})"))
            else:
                # same tile count, different arrangement/mode => one side extracted
                # at the wrong width / without a palette. UNREASONABLE (candidate).
                tags = []
                if dims_bad: tags.append("DIMS")
                if mode_bad: tags.append("MODE")
                if jw <= 8 and jh >= 32: tags.append("STRIP")
                buckets["UNREASONABLE:" + "+".join(tags)].append((jp, det))
        elif args.full:
            eq = pixels_equal(jp, up)
            if eq is False:
                buckets["REASONABLE_LOCALIZATION"].append(
                    (jp, f"same {jw}x{jh} {jm}, pixels differ (JP/US text/UI localization)  [twin {twin}]"))
            elif eq is True:
                buckets["IDENTICAL"].append((jp, ""))
            else:
                buckets["ERROR"].append((jp, "pixel-compare failed"))
        else:
            buckets["OK_DIMS_UNCHECKED"].append((jp, ""))

    # report
    lines = ["# FE8J extracted-asset diff vs fe8u\n",
             "> Generated by scripts/tools/asset_fe8u_diff.py (run with --full for the",
             "> localization pass). Classification:\n",
             "> - **UNREASONABLE:\\*** — same tile COUNT but wrong width/mode on one side",
             ">   (an 8px-wide / palette-less extraction bug that still round-trips byte-exact).",
             ">   The wrong side is fixed to match the code-correct form.",
             "> - **REASONABLE_CONTENT_JPUS** — different tile COUNT ⇒ genuine JP/US content",
             ">   difference (each side correct for its own ROM; not reshapeable).",
             "> - **REASONABLE_LOCALIZATION** — same dims+mode, differing pixels ⇒ JP/US",
             ">   text / UI localization (expected).",
             "> - **IDENTICAL** — byte-for-byte identical to the fe8u twin.",
             "> - **NO_TWIN** — JP-unique asset, no fe8u reference.\n"]
    def rank(k):
        pref = {"UNREASONABLE": 0, "REASONABLE_CONTENT": 1, "REASONABLE_LOCALIZATION": 2,
                "AMBIGUOUS": 3, "IDENTICAL": 8, "NO_TWIN": 9, "OK_DIMS": 7, "ERROR": 4}
        for p, r in pref.items():
            if k.startswith(p): return (r, k)
        return (5, k)
    order = sorted(buckets, key=rank)
    counts = {k: len(v) for k, v in buckets.items()}
    total = sum(counts.values())
    unreasonable = sum(n for k, n in counts.items() if k.startswith("UNREASONABLE"))
    reasonable = sum(n for k, n in counts.items() if k.startswith("REASONABLE"))
    lines.append("\n## Summary\n")
    lines.append(f"- Paired FE8J↔fe8u PNGs compared: **{total - counts.get('NO_TWIN', 0)}** "
                 f"(+{counts.get('NO_TWIN', 0)} JP-unique with no fe8u twin).")
    lines.append(f"- **UNREASONABLE (extraction mistakes to fix): {unreasonable}** — one side "
                 f"extracted at the wrong width / without a palette (tile count matches).")
    lines.append(f"- **REASONABLE diffs: {reasonable}** — expected JP/US differences "
                 f"(content: {counts.get('REASONABLE_CONTENT_JPUS', 0)} differing tile counts; "
                 f"localization: {counts.get('REASONABLE_LOCALIZATION', 0)} same-form pixel diffs).")
    lines.append(f"- **IDENTICAL: {counts.get('IDENTICAL', 0)}** shared byte-for-byte with fe8u.")
    lines.append(f"- **Localization finding:** same-form (same dims+mode) assets are "
                 f"{'ALL identical' if counts.get('REASONABLE_LOCALIZATION', 0) == 0 else 'mostly identical'}"
                 f" — JP/US text & UI localization is carried by the {counts.get('NO_TWIN', 0)} "
                 f"JP-unique (NO_TWIN) assets, not by pixel diffs on shared-form assets.")
    print("== FE8J vs fe8u asset diff ==")
    for k in order:
        n = len(buckets[k])
        print(f"  {k:28s} {n}")
        lines.append(f"\n## {k} ({n})\n")
        # keep IDENTICAL/OK_DIMS as a count only (too many to list)
        if k in ("IDENTICAL", "OK_DIMS_UNCHECKED"):
            lines.append(f"_{n} assets — byte/dims match fe8u; not listed individually._")
            continue
        for jp, det in sorted(buckets[k]):
            lines.append(f"- `{jp}` — {det}" if det else f"- `{jp}`")
    os.makedirs("docs", exist_ok=True)
    open("docs/asset_fe8u_diff.md", "w").write("\n".join(lines) + "\n")
    unreasonable = sum(len(v) for k, v in buckets.items() if k.startswith("UNREASONABLE"))
    print(f"\n  => UNREASONABLE (extraction-mistake candidates): {unreasonable}")
    print("  wrote docs/asset_fe8u_diff.md")

if __name__ == "__main__":
    main()
