#!/usr/bin/env python3
"""misc_gfx2 -- graphics blobs from the long-tail mixed dat_*.s files (Phase-1).

Second batch of mixed `dat_*.s` files (UI / ending staff-reel / world-map gmap &
minimap & skirmish / trap & particle FX / op-subtitle / level-up / save-menu bg /
various address-named data files). Carves ONLY the graphics-prefixed symbols
(Img_/Tsa_/Pal_/gImg_/gPal_/gGfx_/Gfx_) and leaves all non-graphics symbols as
`.incbin "baserom.gba"` (honest).

Extracted FRESH from the JP ROM, byte-verified (LZ77 -> DECOMPRESSED .bin; palette
-> .pal -> .gbapal; bit-15-set / verbatim -> .bin direct). Blobs that don't
decompress / recompress byte-exactly (e.g. gGfx_OpSubtitle_05, a region-different
feimg2 FETSATOOL graphic gbagfx can't reproduce) are left as incbin and reported.

Usage:
  graphics/misc_gfx2/extract_misc_gfx2.py            # dry-run / verify
  graphics/misc_gfx2/extract_misc_gfx2.py --apply    # commit + rewrite + .mk
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "_lib"))
import extract_mixed_gfx as m  # noqa: E402

GLOBS = [
    "asm/dat_data_99D6DC.s", "asm/dat_const_data_E162A_p1.s", "asm/dat_const_data_E162A_p2.s",
    "asm/dat_const_data_DB034_gf.s", "asm/dat_data_A01CC4_2.s", "asm/dat_data_A01CC4_p2.s",
    "asm/dat_worldmap_minimap_p2.s", "asm/dat_worldmap_minimap_p3.s",
    "asm/dat_mapanim_levelup.s", "asm/dat_trap_gas.s", "asm/dat_menu_save_main_bg_p0.s",
    "asm/dat_data_B12A60.s", "asm/dat_data_5AA96C.s", "asm/dat_data_5AA96C_p1.s",
    "asm/dat_data_5AA96C_p2.s", "asm/dat_data_5AA96C_p3.s", "asm/dat_particles_fx.s",
    "asm/dat_worldmap_skirmish.s", "asm/dat_worldmap_gmap_p0.s", "asm/dat_worldmap_gmap_p1.s",
    "asm/dat_trap_fire_pike.s", "asm/dat_trap_fire_pike_2.s", "asm/dat_mine_pal.s",
    "asm/dat_ending_staffreel_p0.s", "asm/dat_ending_staffreel_p1.s", "asm/dat_ending_staffreel_p2.s",
    "asm/dat_ending_staffreel_p3.s", "asm/dat_ending_staffreel_p4.s",
    "asm/dat_ending_details_p0.s", "asm/dat_ending_fin_p0.s", "asm/dat_ending_fin_p1.s",
    "asm/dat_gGfx_OpSubtitle_02_ref.s", "asm/dat_gGfx_OpSubtitle_03_ref.s",
    "asm/dat_gGfx_OpSubtitle_04_ref.s", "asm/dat_gGfx_OpSubtitle_05_ref.s",
    "asm/dat_gGfx_OpSubtitle_06_ref.s",
]

HEADER = (
    "graphics/misc_gfx2 -- long-tail graphics blobs carved out of mixed dat_*.s\n"
    "files (UI / ending staff-reel / worldmap gmap+minimap+skirmish / trap & particle\n"
    "FX / op-subtitle / level-up / save-menu bg / address-named data files). Non-\n"
    "graphics symbols in those files stay as incbin (data-table/code phases). LZ77 ->\n"
    "DECOMPRESSED .bin (%.lz: % gbagfx); palette -> .pal (-> .gbapal); bit-15-set /\n"
    "verbatim -> .bin direct. Auto-generated by graphics/misc_gfx2/extract_misc_gfx2.py."
)


if __name__ == "__main__":
    apply = "--apply" in sys.argv
    m.run(out_dir="graphics/misc_gfx2", mk_name="misc_gfx2.mk",
          globs=GLOBS, header=HEADER, apply=apply)
