# graphics/misc_gfx2 -- long-tail graphics blobs carved out of mixed dat_*.s
# files (UI / ending staff-reel / worldmap gmap+minimap+skirmish / trap & particle
# FX / op-subtitle / level-up / save-menu bg / address-named data files). Non-
# graphics symbols in those files stay as incbin (data-table/code phases). LZ77 ->
# DECOMPRESSED .bin (%.lz: % gbagfx); palette -> .pal (-> .gbapal); bit-15-set /
# verbatim -> .bin direct. Auto-generated by graphics/misc_gfx2/extract_misc_gfx2.py.

asm/dat_const_data_DB034_gf.o: \
  graphics/misc_gfx2/Img_ConstDataDB034_0.bin.lz \
  graphics/misc_gfx2/Img_ConstDataDB034_1.bin.lz \
  graphics/misc_gfx2/Img_ConstDataDB034_2.bin.lz \
  graphics/misc_gfx2/Img_ConstDataDB034_3.bin.lz \
  graphics/misc_gfx2/Img_ConstDataDB034_4.bin.lz \
  graphics/misc_gfx2/Pal_NewEkrBaseKaiten.gbapal

asm/dat_const_data_E162A_p1.o: \
  graphics/misc_gfx2/Tsa_EkrTriPegagusLeftBG1.bin.lz \
  graphics/misc_gfx2/Tsa_EkrTriPegagusLeftBG2.bin.lz \
  graphics/misc_gfx2/Tsa_EkrTriPegagusLeftBG3.bin.lz \
  graphics/misc_gfx2/Tsa_EkrTriPegagusRightBG1.bin.lz \
  graphics/misc_gfx2/Tsa_EkrTriPegagusRightBG2.bin.lz \
  graphics/misc_gfx2/Tsa_EkrTriPegagusRightBG3.bin.lz

asm/dat_const_data_E162A_p2.o: \
  graphics/misc_gfx2/Img_TriGenerialAxeAtkOBJ.bin.lz \
  graphics/misc_gfx2/Img_TriGenerialAxeOBJ.bin.lz \
  graphics/misc_gfx2/Img_TriGenerialHandAxeAtkOBJ.bin.lz \
  graphics/misc_gfx2/Img_TriGenerialHandAxeOBJ.bin.lz \
  graphics/misc_gfx2/Img_TriGenerialLanceAtkOBJ.bin.lz \
  graphics/misc_gfx2/Img_TriGenerialLanceOBJ.bin.lz \
  graphics/misc_gfx2/Img_TriKnightAtkOBJ.bin.lz \
  graphics/misc_gfx2/Img_TriKnightOBJ.bin.lz

asm/dat_data_5AA96C.o: \
  graphics/misc_gfx2/Img_LinkArenaPostBattleBg.bin.lz \
  graphics/misc_gfx2/Pal_LinkArenaPostBattleBg.gbapal \
  graphics/misc_gfx2/Tsa_LinkArenaPostBattleBg.bin.lz

asm/dat_data_5AA96C_p1.o: \
  graphics/misc_gfx2/Img_LinkArenaActiveBannerFx.bin.lz \
  graphics/misc_gfx2/Img_LinkArenaRankIcons.bin.lz

asm/dat_data_5AA96C_p2.o: \
  graphics/misc_gfx2/Img_LinkArenaPlayerBanners.bin.lz \
  graphics/misc_gfx2/Img_LinkArena_FogUnitPlaceholder.bin.lz \
  graphics/misc_gfx2/Pal_LinkArenaMenu.gbapal \
  graphics/misc_gfx2/Pal_LinkArenaRankIcons.gbapal \
  graphics/misc_gfx2/Pal_TacticianSelObj.gbapal

asm/dat_data_5AA96C_p3.o: \
  graphics/misc_gfx2/Pal_LinkArenaActiveBannerFx.gbapal \
  graphics/misc_gfx2/Pal_LinkArenaPlacementRanks.gbapal \
  graphics/misc_gfx2/Pal_UnkData_0.gbapal

asm/dat_data_99D6DC.o: \
  graphics/misc_gfx2/Img_99E1A4.bin.lz \
  graphics/misc_gfx2/Img_99ED44.bin.lz \
  graphics/misc_gfx2/Img_99F7D4.bin.lz \
  graphics/misc_gfx2/Img_9A0154.bin.lz \
  graphics/misc_gfx2/Img_9A0864.bin.lz \
  graphics/misc_gfx2/Img_Congratulations.bin.lz \
  graphics/misc_gfx2/Img_MapClear.bin.lz \
  graphics/misc_gfx2/Img_UnkData_0.bin.lz \
  graphics/misc_gfx2/Pal_Congratulations.gbapal \
  graphics/misc_gfx2/Pal_EventMapAnimMaskfx.gbapal \
  graphics/misc_gfx2/Pal_MapClear.gbapal

asm/dat_data_A01CC4_2.o: \
  graphics/misc_gfx2/Img_GameOverText.bin.lz \
  graphics/misc_gfx2/Pal_GameOverText1.gbapal \
  graphics/misc_gfx2/Pal_GameOverText2.gbapal \
  graphics/misc_gfx2/gGfx_UnkData_0.bin.lz

asm/dat_data_A01CC4_p2.o: \
  graphics/misc_gfx2/Img_ChapterIntroFog.bin.lz \
  graphics/misc_gfx2/Img_PlayerRankFog.bin.lz \
  graphics/misc_gfx2/Pal_PlayerRankFog.gbapal

asm/dat_data_B12A60.o: \
  graphics/misc_gfx2/Img_CommGameBgScreen.bin.lz \
  graphics/misc_gfx2/Img_UnkData_2.bin.lz \
  graphics/misc_gfx2/Pal_CommGameBgScreenInShop.gbapal \
  graphics/misc_gfx2/Pal_UnkData_2.gbapal \
  graphics/misc_gfx2/Tsa_UnkData_5.bin.lz

asm/dat_ending_details_p0.o: \
  graphics/misc_gfx2/Img_CharacterEndingMenu.bin.lz \
  graphics/misc_gfx2/Pal_CharacterEndingMenu.gbapal \
  graphics/misc_gfx2/Pal_EndingDetails_0.gbapal

asm/dat_ending_fin_p0.o: \
  graphics/misc_gfx2/Img_FinScreen.bin.lz \
  graphics/misc_gfx2/Pal_FinScreen.gbapal

asm/dat_ending_fin_p1.o: \
  graphics/misc_gfx2/Pal_FinScreen_1.gbapal

asm/dat_ending_staffreel_p0.o: \
  graphics/misc_gfx2/Img_StaffReelEnt_0.bin.lz \
  graphics/misc_gfx2/Img_StaffReelEnt_1.bin.lz \
  graphics/misc_gfx2/Img_StaffReelEnt_2.bin.lz \
  graphics/misc_gfx2/Img_StaffReelEnt_3.bin.lz \
  graphics/misc_gfx2/Img_StaffReelEnt_4.bin.lz \
  graphics/misc_gfx2/Img_StaffReelEnt_5.bin.lz \
  graphics/misc_gfx2/Img_StaffReelEnt_6.bin.lz

asm/dat_ending_staffreel_p1.o: \
  graphics/misc_gfx2/Img_StaffReelEnt_8.bin.lz \
  graphics/misc_gfx2/Img_StaffReelEnt_9.bin.lz

asm/dat_ending_staffreel_p2.o: \
  graphics/misc_gfx2/Tsa_StaffReelEnt_0.bin.lz \
  graphics/misc_gfx2/Tsa_StaffReelEnt_1.bin.lz \
  graphics/misc_gfx2/Tsa_StaffReelEnt_2.bin.lz \
  graphics/misc_gfx2/Tsa_StaffReelEnt_3.bin.lz \
  graphics/misc_gfx2/Tsa_StaffReelEnt_4.bin.lz \
  graphics/misc_gfx2/Tsa_StaffReelEnt_5.bin.lz

asm/dat_ending_staffreel_p3.o: \
  graphics/misc_gfx2/Tsa_StaffReelEnt_8.bin.lz \
  graphics/misc_gfx2/Tsa_StaffReelEnt_9.bin.lz

asm/dat_ending_staffreel_p4.o: \
  graphics/misc_gfx2/gGfx_BrownTextBox.bin.lz \
  graphics/misc_gfx2/gPal_BrownTextBox.gbapal

asm/dat_gGfx_OpSubtitle_02_ref.o: \
  graphics/misc_gfx2/gGfx_OpSubtitle_02.bin.lz

asm/dat_gGfx_OpSubtitle_03_ref.o: \
  graphics/misc_gfx2/gGfx_OpSubtitle_03.bin.lz

asm/dat_gGfx_OpSubtitle_04_ref.o: \
  graphics/misc_gfx2/gGfx_OpSubtitle_04.bin.lz

asm/dat_gGfx_OpSubtitle_06_ref.o: \
  graphics/misc_gfx2/gGfx_OpSubtitle_06.bin.lz

asm/dat_mapanim_levelup.o: \
  graphics/misc_gfx2/Img_ManimLevelUpStatGain.bin.lz \
  graphics/misc_gfx2/Img_ManimLevelUpText.bin.lz \
  graphics/misc_gfx2/Pal_ManimLevelUp.gbapal \
  graphics/misc_gfx2/Pal_ManimLevelUpStatGainCycling.gbapal

asm/dat_menu_save_main_bg_p0.o: \
  graphics/misc_gfx2/Img_MainMenuBgFog.bin.lz \
  graphics/misc_gfx2/Img_SaveMenuBG.bin.lz \
  graphics/misc_gfx2/Pal_MainMenuBgFog.gbapal \
  graphics/misc_gfx2/Pal_SaveMenuBG.gbapal

asm/dat_mine_pal.o: \
  graphics/misc_gfx2/Pal_EventCursorShinning.gbapal \
  graphics/misc_gfx2/Pal_MineFx.gbapal

asm/dat_particles_fx.o: \
  graphics/misc_gfx2/Img_LightRune.bin.lz \
  graphics/misc_gfx2/Pal_LightRune.gbapal \
  graphics/misc_gfx2/Tsa_LightRune.bin.lz

asm/dat_trap_fire_pike.o: \
  graphics/misc_gfx2/Img_FireTrap.bin.lz \
  graphics/misc_gfx2/Pal_FireTrap.gbapal

asm/dat_trap_fire_pike_2.o: \
  graphics/misc_gfx2/Img_PikeTrap.bin.lz \
  graphics/misc_gfx2/Pal_FireTrap2.gbapal

asm/dat_trap_gas.o: \
  graphics/misc_gfx2/Img_ArrowTrap.bin.lz \
  graphics/misc_gfx2/Img_GasTrapHorizontal.bin.lz \
  graphics/misc_gfx2/Img_GasTrapVertical.bin.lz \
  graphics/misc_gfx2/Pal_ArrowTrap.gbapal \
  graphics/misc_gfx2/Pal_GasTrap.gbapal

asm/dat_worldmap_gmap_p0.o: \
  graphics/misc_gfx2/Img_GmapCastleNodes.bin.lz \
  graphics/misc_gfx2/Img_GmapNodes.bin.lz

asm/dat_worldmap_gmap_p1.o: \
  graphics/misc_gfx2/gGfx_GMapPI_ShopIcons.bin.lz \
  graphics/misc_gfx2/gPal_GMapPI_ShopIcons.gbapal \
  graphics/misc_gfx2/gPal_WorldmapGmap_0.gbapal

asm/dat_worldmap_minimap_p2.o: \
  graphics/misc_gfx2/gGfx_GMapPI_LevelNums.bin.lz

asm/dat_worldmap_minimap_p3.o: \
  graphics/misc_gfx2/Img_EventGmap.bin.lz \
  graphics/misc_gfx2/Pal_EventGmap.gbapal \
  graphics/misc_gfx2/Tsa_EventGmap.bin.lz \
  graphics/misc_gfx2/gImg_WorldmapMinimap_0.bin.lz \
  graphics/misc_gfx2/gPal_WorldmapMinimap_0.gbapal

asm/dat_worldmap_skirmish.o: \
  graphics/misc_gfx2/Img_WorldMapPlaceDot.bin.lz \
  graphics/misc_gfx2/Pal_WmPlaceDot_Highlight.gbapal \
  graphics/misc_gfx2/Pal_WmPlaceDot_Standard.gbapal

