# graphics/btl_bg -- battle-background assets (region-extracted from the
# JP ROM). dat_data_btl_bg.s holds LZ77 tiles/tilemap/palette per bg. The
# committed source is the DECOMPRESSED blob (.feimg3.bin tiles / .fetsa3.bin
# tilemap) or a JASC .pal; the Makefile rebuilds .lz (gbagfx) byte-identical.
# Auto-generated by graphics/btl_bg/extract_btl_bg.py.
# Region-different assets (btl_bg_0..8, 52..60, 63, 66-68) extracted 2026-06-13
# via gbagfx -mindist 2 (all round-trip byte-perfect at mindist=2).

asm/dat_data_btl_bg_p0.o: \
  graphics/btl_bg/btl_bg_0.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_0.gbapal.lz \
  graphics/btl_bg/btl_bg_0.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_1.feimg3.bin.lz

asm/dat_data_btl_bg_p1.o: \
  graphics/btl_bg/btl_bg_1.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_2.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_2.gbapal.lz \
  graphics/btl_bg/btl_bg_2.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_3.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_3.gbapal.lz \
  graphics/btl_bg/btl_bg_3.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_4.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_4.gbapal.lz \
  graphics/btl_bg/btl_bg_4.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_5.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_5.gbapal.lz \
  graphics/btl_bg/btl_bg_5.fetsa3.bin.lz

asm/dat_data_btl_bg_p2.o: \
  graphics/btl_bg/btl_bg_6.gbapal.lz \
  graphics/btl_bg/btl_bg_6.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_7.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_7.gbapal.lz \
  graphics/btl_bg/btl_bg_7.fetsa3.bin.lz

asm/dat_data_btl_bg_p3.o: \
  graphics/btl_bg/btl_bg_8.gbapal.lz \
  graphics/btl_bg/btl_bg_8.fetsa3.bin.lz

asm/dat_data_btl_bg_p13.o: \
  graphics/btl_bg/btl_bg_52.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_52.gbapal.lz \
  graphics/btl_bg/btl_bg_52.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_53.gbapal.lz \
  graphics/btl_bg/btl_bg_54.gbapal.lz \
  graphics/btl_bg/btl_bg_59.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_59.gbapal.lz

asm/dat_data_btl_bg_p14.o: \
  graphics/btl_bg/btl_bg_55.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_55.gbapal.lz \
  graphics/btl_bg/btl_bg_55.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_56.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_56.gbapal.lz \
  graphics/btl_bg/btl_bg_56.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_57.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_57.gbapal.lz \
  graphics/btl_bg/btl_bg_57.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_58.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_58.gbapal.lz \
  graphics/btl_bg/btl_bg_58.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_60.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_60.gbapal.lz \
  graphics/btl_bg/btl_bg_60.fetsa3.bin.lz

asm/dat_data_btl_bg_p15.o: \
  graphics/btl_bg/btl_bg_63.gbapal.lz

asm/dat_data_btl_bg_p16.o: \
  graphics/btl_bg/btl_bg_66.gbapal.lz \
  graphics/btl_bg/btl_bg_67.gbapal.lz \
  graphics/btl_bg/btl_bg_68.gbapal.lz

asm/dat_data_btl_bg.o: \
  graphics/btl_bg/btl_bg_10.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_10.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_10.gbapal.lz \
  graphics/btl_bg/btl_bg_11.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_11.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_11.gbapal.lz \
  graphics/btl_bg/btl_bg_12.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_12.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_12.gbapal.lz \
  graphics/btl_bg/btl_bg_13.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_13.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_13.gbapal.lz \
  graphics/btl_bg/btl_bg_14.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_14.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_14.gbapal.lz \
  graphics/btl_bg/btl_bg_15.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_15.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_15.gbapal.lz \
  graphics/btl_bg/btl_bg_16.gbapal.lz \
  graphics/btl_bg/btl_bg_17.gbapal.lz \
  graphics/btl_bg/btl_bg_18.gbapal.lz \
  graphics/btl_bg/btl_bg_19.gbapal.lz \
  graphics/btl_bg/btl_bg_20.gbapal.lz \
  graphics/btl_bg/btl_bg_21.gbapal.lz \
  graphics/btl_bg/btl_bg_22.gbapal.lz \
  graphics/btl_bg/btl_bg_23.gbapal.lz \
  graphics/btl_bg/btl_bg_24.gbapal.lz \
  graphics/btl_bg/btl_bg_25.gbapal.lz \
  graphics/btl_bg/btl_bg_26.gbapal.lz \
  graphics/btl_bg/btl_bg_27.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_27.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_27.gbapal.lz \
  graphics/btl_bg/btl_bg_28.gbapal.lz \
  graphics/btl_bg/btl_bg_29.gbapal.lz \
  graphics/btl_bg/btl_bg_30.gbapal.lz \
  graphics/btl_bg/btl_bg_31.gbapal.lz \
  graphics/btl_bg/btl_bg_32.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_32.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_32.gbapal.lz \
  graphics/btl_bg/btl_bg_33.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_33.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_33.gbapal.lz \
  graphics/btl_bg/btl_bg_34.gbapal.lz \
  graphics/btl_bg/btl_bg_35.gbapal.lz \
  graphics/btl_bg/btl_bg_36.gbapal.lz \
  graphics/btl_bg/btl_bg_37.gbapal.lz \
  graphics/btl_bg/btl_bg_38.gbapal.lz \
  graphics/btl_bg/btl_bg_39.gbapal.lz \
  graphics/btl_bg/btl_bg_40.gbapal.lz \
  graphics/btl_bg/btl_bg_41.gbapal.lz \
  graphics/btl_bg/btl_bg_42.gbapal.lz \
  graphics/btl_bg/btl_bg_43.gbapal.lz \
  graphics/btl_bg/btl_bg_44.gbapal.lz \
  graphics/btl_bg/btl_bg_45.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_45.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_45.gbapal.lz \
  graphics/btl_bg/btl_bg_46.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_46.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_46.gbapal.lz \
  graphics/btl_bg/btl_bg_47.feimg3.bin.lz \
  graphics/btl_bg/btl_bg_47.fetsa3.bin.lz \
  graphics/btl_bg/btl_bg_47.gbapal.lz \
  graphics/btl_bg/btl_bg_48.gbapal.lz \
  graphics/btl_bg/btl_bg_49.gbapal.lz \
  graphics/btl_bg/btl_bg_50.gbapal.lz

