#!/usr/bin/env python3
"""btl_bg (battle backgrounds) graphics extractor -- Phase-1.

asm/dat_data_btl_bg.s is a flat list of `btl_bg_N_{tiles,palette,map}` symbols,
each an LZ77-compressed graphic blob in the JP ROM. FE8U commits per-bg `.png`
and rebuilds tiles/map with FETSATOOL (`%.feimg3.bin %.fetsa3.bin: %.png`), which
deduplicates tiles into the dat_data_btl_bg tile-arrangement format. FETSATOOL is
NOT part of the FE8J asset toolchain, so we instead commit the *decompressed*
blob directly as a descriptively-named binary source (the exact bytes the ROM
stores, just un-LZ'd) and let the Makefile's generic `%.lz: %` rule recompress it
byte-identically. Palettes commit a JASC `.pal` and rebuild `.pal -> .gbapal ->
.lz`. Every committed source rebuilds the exact JP ROM bytes with baserom removed.

  btl_bg_N_tiles    -> btl_bg_N.feimg3.bin  --gbagfx -mindist N--> .feimg3.bin.lz
  btl_bg_N_map      -> btl_bg_N.fetsa3.bin  --gbagfx -mindist N--> .fetsa3.bin.lz
  btl_bg_N_palette  -> btl_bg_N.pal --.gbapal--.lz

Usage:
  graphics/btl_bg/extract_btl_bg.py            # dry-run / verify
  graphics/btl_bg/extract_btl_bg.py --apply    # commit + rewrite .s + write .mk
"""
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "_lib"))
from extract_lz_blobs import run_subsystem  # noqa: E402

SUFFIX_MAP = [
    (r"_tiles$", (".feimg3.bin", ".feimg3.bin.lz")),
    (r"_map$", (".fetsa3.bin", ".fetsa3.bin.lz")),
    (r"_palette$", (".pal", ".gbapal.lz")),
]


def name_fn(sym):
    # btl_bg_10_tiles -> btl_bg_10 ; btl_bg_10_palette -> btl_bg_10
    return re.sub(r"_(tiles|map|palette)$", "", sym)


if __name__ == "__main__":
    apply = "--apply" in sys.argv
    run_subsystem(
        asm="asm/dat_data_btl_bg.s",
        out_dir="graphics/btl_bg",
        obj="asm/dat_data_btl_bg.o",
        suffix_map=SUFFIX_MAP,
        name_fn=name_fn,
        apply=apply,
        mk_header=(
            "graphics/btl_bg -- battle-background assets (region-extracted from the\n"
            "JP ROM). dat_data_btl_bg.s holds LZ77 tiles/tilemap/palette per bg. The\n"
            "committed source is the DECOMPRESSED blob (.feimg3.bin tiles / .fetsa3.bin\n"
            "tilemap) or a JASC .pal; the Makefile rebuilds .lz (gbagfx) byte-identical.\n"
            "Auto-generated by graphics/btl_bg/extract_btl_bg.py."
        ),
    )
