/* Auto-generated by gen_shared_oracles.py.  Inventory only. */
#ifndef SUB_8057F80_ORACLE_STUBS_GENERATED_H
#define SUB_8057F80_ORACLE_STUBS_GENERATED_H

#define SUB_8057F80_ORACLE_COUNT 26
static const char *const g_sub_8057F80_oracle_names[] = {
    "CheckBanimHensei",
    "CheckBattleScripted",
    "FilterBattleAnimCharacterPalette",
    "GetBanimBackgroundIndex",
    "GetBanimFactionPalette",
    "GetBanimLinkArenaFlag",
    "GetBanimTerrainGround",
    "GetBattleAnimArenaFlag",
    "GetBattleAnimPreconfType",
    "GetBattleAnimationId",
    "GetItemAttributes",
    "GetItemIndex",
    "GetROMChapterStruct",
    "GetSelectTargetCount",
    "GetSpellAnimId",
    "GetSpellAssocCharCount",
    "IsItemDisplayedInBattle",
    "IsItemEffectiveAgainst",
    "IsUnitEffectiveAgainst",
    "ParseBattleHitToBanimCmd",
    "ResetEkrDragonStatus",
    "SetBanimArenaFlag",
    "SetBanimLinkArenaFlag",
    "SetBattleUnscripted",
    "SetEkrDragonStatusType",
    "UnsetMapStaffAnim",
};

/* 000: CheckBanimHensei -- generate a ref-record/impl-assert shared oracle stub here. */
/* 001: CheckBattleScripted -- generate a ref-record/impl-assert shared oracle stub here. */
/* 002: FilterBattleAnimCharacterPalette -- generate a ref-record/impl-assert shared oracle stub here. */
/* 003: GetBanimBackgroundIndex -- generate a ref-record/impl-assert shared oracle stub here. */
/* 004: GetBanimFactionPalette -- generate a ref-record/impl-assert shared oracle stub here. */
/* 005: GetBanimLinkArenaFlag -- generate a ref-record/impl-assert shared oracle stub here. */
/* 006: GetBanimTerrainGround -- generate a ref-record/impl-assert shared oracle stub here. */
/* 007: GetBattleAnimArenaFlag -- generate a ref-record/impl-assert shared oracle stub here. */
/* 008: GetBattleAnimPreconfType -- generate a ref-record/impl-assert shared oracle stub here. */
/* 009: GetBattleAnimationId -- generate a ref-record/impl-assert shared oracle stub here. */
/* 010: GetItemAttributes -- generate a ref-record/impl-assert shared oracle stub here. */
/* 011: GetItemIndex -- generate a ref-record/impl-assert shared oracle stub here. */
/* 012: GetROMChapterStruct -- generate a ref-record/impl-assert shared oracle stub here. */
/* 013: GetSelectTargetCount -- generate a ref-record/impl-assert shared oracle stub here. */
/* 014: GetSpellAnimId -- generate a ref-record/impl-assert shared oracle stub here. */
/* 015: GetSpellAssocCharCount -- generate a ref-record/impl-assert shared oracle stub here. */
/* 016: IsItemDisplayedInBattle -- generate a ref-record/impl-assert shared oracle stub here. */
/* 017: IsItemEffectiveAgainst -- generate a ref-record/impl-assert shared oracle stub here. */
/* 018: IsUnitEffectiveAgainst -- generate a ref-record/impl-assert shared oracle stub here. */
/* 019: ParseBattleHitToBanimCmd -- generate a ref-record/impl-assert shared oracle stub here. */
/* 020: ResetEkrDragonStatus -- generate a ref-record/impl-assert shared oracle stub here. */
/* 021: SetBanimArenaFlag -- generate a ref-record/impl-assert shared oracle stub here. */
/* 022: SetBanimLinkArenaFlag -- generate a ref-record/impl-assert shared oracle stub here. */
/* 023: SetBattleUnscripted -- generate a ref-record/impl-assert shared oracle stub here. */
/* 024: SetEkrDragonStatusType -- generate a ref-record/impl-assert shared oracle stub here. */
/* 025: UnsetMapStaffAnim -- generate a ref-record/impl-assert shared oracle stub here. */

#endif
