# frontier_chap_title -- region-DIFFERENT chapter-title graphics (JP 0x08a7e188..0x08a92514).
# LZ77 tile/tilemap blobs: committed decompressed .bin rebuilds (gbagfx %.lz: %) byte-
# identical to the JP ROM. Two blobs whose FE8-compressor output gbagfx cannot reproduce
# at -mindist 1/2/3 are committed as verbatim compressed .bin (incbin'd directly). All
# extracted fresh from the JP ROM (region-different). Oracle: make compare.

asm/frontier_chap_title.o: \
  graphics/frontier_chap_title/frontier_chap_title_000_A7E188.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_001_A7E504.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_002_A7E800.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_003_A7EB7C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_004_A7EF88.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_005_A7F360.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_006_A7F754.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_007_A7FAA4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_008_A7FE84.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_009_A8021C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_010_A80584.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_011_A808BC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_012_A80CA0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_013_A81068.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_014_A813F8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_015_A81774.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_016_A81B1C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_017_A81F28.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_018_A82294.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_019_A8258C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_020_A829B4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_021_A82D58.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_022_A8306C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_023_A833D4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_024_A8383C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_025_A83C0C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_026_A83F64.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_027_A8436C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_028_A84720.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_029_A84BFC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_030_A84F64.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_031_A852E8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_032_A85670.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_033_A859E4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_034_A85D6C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_035_A860F4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_036_A86460.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_037_A867E4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_038_A86B60.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_039_A86EF8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_040_A8729C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_041_A8765C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_042_A87A14.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_043_A87DBC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_044_A88174.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_045_A88530.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_046_A888D0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_047_A88C8C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_048_A89048.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_049_A89428.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_050_A89710.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_051_A899E8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_052_A89CD8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_053_A89F80.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_054_A8A260.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_055_A8A5A0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_056_A8A85C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_057_A8AB8C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_058_A8AE74.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_059_A8B168.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_060_A8B39C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_061_A8B5DC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_062_A8B7F0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_064_A8BFB0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_065_A8C0EC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_066_A8C1E4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_067_A8C308.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_068_A8C424.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_069_A8C534.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_070_A8C734.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_071_A8C854.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_072_A8C974.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_073_A8CA74.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_074_A8CB94.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_075_A8CCAC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_076_A8CDF8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_077_A8CF14.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_078_A8D064.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_079_A8D1B0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_080_A8D2F4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_081_A8D430.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_082_A8D574.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_083_A8D6AC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_084_A8D7F4.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_085_A8D948.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_086_A8DAB0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_087_A8DBFC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_088_A8DE6C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_089_A8E080.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_090_A8E2EC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_091_A8E600.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_092_A8E8C8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_093_A8EAF8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_094_A8ED30.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_095_A8EFFC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_096_A8F28C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_097_A8F4CC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_098_A8F6F8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_099_A8F9C0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_100_A8FC68.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_101_A8FEC0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_102_A900FC.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_103_A90378.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_104_A9065C.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_105_A90898.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_106_A90A98.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_107_A90D84.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_108_A90FF0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_109_A911D0.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_110_A91418.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_111_A91760.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_112_A919F8.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_113_A91C28.bin.lz \
  graphics/frontier_chap_title/frontier_chap_title_114_A91F08.bin.lz

