#!/usr/bin/env python3
"""Generate the compact GitHub Pages site for fireemblem8j."""

import argparse
import datetime as _dt
import html
import os
import pathlib
import re
import shutil
import subprocess
import sys

PROJECT_NAME = "fireemblem8j"
DEFAULT_ELF = "fireemblem8.elf"
DEFAULT_PROGRESS = "progress.txt"
DEFAULT_OUT_DIR = "_site"
KNOWN_REL_ROOTS = (
    "src/",
    "asm/",
    "include/",
    "data/",
    "sound/",
    "graphics/",
    "graphics_jp/",
    "maps/",
    "tools/",
    "scripts/",
    "common_syms/",
)
FILE_LINE_RE = re.compile(r"\t(/[^\t\r\n:]+):(\d+)(?=$|\s)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "elf",
        nargs="?",
        default=os.environ.get("ELF", DEFAULT_ELF),
        help="ELF to read with arm-none-eabi-nm (default: $ELF or fireemblem8.elf)",
    )
    parser.add_argument(
        "--progress",
        default=DEFAULT_PROGRESS,
        help="progress.txt generated by scripts/calcprogress.py",
    )
    parser.add_argument(
        "--out-dir",
        default=DEFAULT_OUT_DIR,
        help="site output directory",
    )
    return parser.parse_args()


def git_value(args: list[str], fallback: str) -> str:
    try:
        return subprocess.check_output(["git", *args], text=True, stderr=subprocess.DEVNULL).strip()
    except (OSError, subprocess.CalledProcessError):
        return fallback


def normalize_path(path: str, repo_root: pathlib.Path, elf_path: pathlib.Path) -> str:
    normalized = path.replace("\\", "/")
    prefixes = []
    for candidate in (repo_root, elf_path.parent):
        try:
            prefixes.append(candidate.resolve().as_posix() + "/")
        except OSError:
            pass

    for prefix in prefixes:
        if normalized.startswith(prefix):
            return normalized[len(prefix) :]

    marker = f"/{PROJECT_NAME}/"
    if marker in normalized:
        return normalized.split(marker, 1)[1]

    for root in KNOWN_REL_ROOTS:
        needle = f"/{root}"
        if needle in normalized:
            return root + normalized.split(needle, 1)[1]

    return pathlib.PurePosixPath(normalized).name


def normalize_nm_line(line: str, repo_root: pathlib.Path, elf_path: pathlib.Path) -> str:
    def replace(match: re.Match[str]) -> str:
        rel = normalize_path(match.group(1), repo_root, elf_path)
        return f"\t{rel}:{match.group(2)}"

    return FILE_LINE_RE.sub(replace, line.rstrip("\n\r"))


# `ADDR TYPE NAME` from `arm-none-eabi-nm -n` (defined symbols carry a hex address;
# undefined/absolute-format rows without one simply do not match and stay bare).
NM_SYMBOL_RE = re.compile(r"^([0-9A-Fa-f]+) (\S) (.*)$")

# A usable addr2line result: absolute source path + real (>=1) line. This drops the
# `??:0` / `??:?` "unknown" forms AND quirks like `rom_header.o:?` (relative asm path,
# unknown line) that `nm -l` also leaves bare -- so only genuine locations are appended.
RESOLVED_LOCATION_RE = re.compile(r"^/.+:[1-9][0-9]*$")


def resolve_lines(elf_path: pathlib.Path, addresses: list[str]) -> list[str]:
    """Resolve many addresses to `file:line` in ONE `arm-none-eabi-addr2line` process.

    This replaces `nm -l`'s per-symbol DWARF walk -- which on the ~427 MB debug ELF
    (#142) took ~27 min AND, via the issue's proposed `objdump --dwarf=decodedline`,
    needs >16 GB (unusable) -- with a single shared-DWARF pass (~90 s, ~2.3 GB) that
    ALSO resolves data/bss symbols (decodedline is code-only and would drop them,
    failing the gMainCallback spot-check). Unresolved addresses come back as `??:0` /
    `??:?`; the caller drops those (bare row). Output is line-for-line parallel to
    `addresses`.

    This is ADDRESS-BASED resolution (issue #144's explicit "addr->file:line by
    address" design) and is NOT byte-identical to `nm -l`, which resolves with full
    symbol context. Measured on this ELF: 45938/46939 symbols (97.9%) match `nm -l`
    exactly, incl. the spot-check; 1001 (2.1%) differ -- for a function entry addr2line
    reports the first-statement line where `nm -l` reports the opening `{` line, and for
    a data/bss address claimed by several CUs, addr2line picks the first-by-address CU
    where `nm -l` picks the symbol's defining CU. symbols.txt is a fast address-based
    reference, not authoritative symbol-definition provenance; exact file:line is
    toolchain(bfd)-version dependent. #144 requires same FORMAT + the spot-check + <2
    min, not byte identity (that applies only to progress.txt)."""
    if not addresses:
        return []
    result = subprocess.run(
        ["arm-none-eabi-addr2line", "-e", str(elf_path)],
        input="".join(a + "\n" for a in addresses),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        raise subprocess.CalledProcessError(result.returncode, result.args, stderr=result.stderr)
    lines = result.stdout.splitlines()
    if len(lines) != len(addresses):
        raise RuntimeError(
            f"addr2line returned {len(lines)} lines for {len(addresses)} addresses"
        )
    return lines


def generate_symbols(elf_path: pathlib.Path, symbols_path: pathlib.Path, repo_root: pathlib.Path) -> int:
    if not elf_path.exists():
        raise FileNotFoundError(f"ELF not found: {elf_path}")

    # Fast symbol table (sorted by address, NO -l -- the -l per-symbol DWARF lookup is
    # the 27-min hotspot). Then resolve every address in one batched addr2line pass and
    # append the `\tfile:line` suffix (address-based; see resolve_lines for the accepted
    # differences from nm -l).
    nm = subprocess.run(
        ["arm-none-eabi-nm", "-n", str(elf_path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if nm.returncode != 0:
        raise subprocess.CalledProcessError(nm.returncode, nm.args, stderr=nm.stderr)

    nm_lines = nm.stdout.splitlines()
    addresses: list[str] = []
    addr_index: list[int | None] = []
    for raw_line in nm_lines:
        match = NM_SYMBOL_RE.match(raw_line)
        # `nm -l` resolves a symbol through ITS section, so ABSOLUTE symbols (type
        # `A`/`a` -- no section) never get a file:line. In this decomp most data lives
        # at fixed JP addresses defined absolutely via the layout manifests, so those
        # are `A`/`a`; addr2line would resolve them by raw address, which `nm -l` does
        # not. Only queue non-absolute symbols so the suffix set matches `nm -l`.
        if match and match.group(2) not in ("A", "a"):
            addr_index.append(len(addresses))
            addresses.append("0x" + match.group(1))
        else:
            addr_index.append(None)

    locations = resolve_lines(elf_path, addresses)

    count = 0
    previous = None
    with symbols_path.open("w", encoding="utf-8", newline="\n") as output:
        for raw_line, idx in zip(nm_lines, addr_index):
            if idx is not None:
                loc = locations[idx]
                if RESOLVED_LOCATION_RE.match(loc):
                    raw_line = f"{raw_line}\t{loc}"
            line = normalize_nm_line(raw_line, repo_root, elf_path)
            if line == previous:
                continue
            output.write(line + "\n")
            previous = line
            count += 1
    return count


def write_index(out_dir: pathlib.Path, progress_text: str) -> None:
    commit = git_value(["rev-parse", "--short=12", "HEAD"], "unknown")
    timestamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    index = f"""<!doctype html>
<html>
<head><meta charset=\"utf-8\"><title>fireemblem8j</title></head>
<body>
<h1>fireemblem8j</h1>
<p>commit: {html.escape(commit)}<br>generated: {html.escape(timestamp)}</p>
<ul>
<li><a href=\"progress.txt\">progress</a></li>
<li><a href=\"symbols.txt\">symbols</a></li>
</ul>
<pre>{html.escape(progress_text)}</pre>
</body>
</html>
"""
    (out_dir / "index.html").write_text(index, encoding="utf-8", newline="\n")


def main() -> int:
    args = parse_args()
    repo_root = pathlib.Path.cwd().resolve()
    elf_path = pathlib.Path(args.elf).expanduser()
    progress_path = pathlib.Path(args.progress)
    out_dir = pathlib.Path(args.out_dir)

    if not progress_path.exists():
        raise FileNotFoundError(f"progress file not found: {progress_path}")

    progress_text = progress_path.read_text(encoding="utf-8")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    (out_dir / "progress.txt").write_text(progress_text, encoding="utf-8", newline="\n")
    symbol_count = generate_symbols(elf_path, out_dir / "symbols.txt", repo_root)
    write_index(out_dir, progress_text)
    print(f"Generated {out_dir}/ with {symbol_count} symbol lines from {elf_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"gen_pages.py: error: {exc}", file=sys.stderr)
        raise SystemExit(1)
