#!/usr/bin/env python3
"""Generate the compact GitHub Pages site for fireemblem8j."""

import argparse
import datetime as _dt
import html
import os
import pathlib
import re
import shutil
import subprocess
import sys

PROJECT_NAME = "fireemblem8j"
DEFAULT_ELF = "fireemblem8.elf"
DEFAULT_PROGRESS = "progress.txt"
DEFAULT_OUT_DIR = "_site"
KNOWN_REL_ROOTS = (
    "src/",
    "asm/",
    "include/",
    "data/",
    "sound/",
    "graphics/",
    "graphics_jp/",
    "maps/",
    "tools/",
    "scripts/",
    "common_syms/",
)
FILE_LINE_RE = re.compile(r"\t(/[^\t\r\n:]+):(\d+)(?=$|\s)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "elf",
        nargs="?",
        default=os.environ.get("ELF", DEFAULT_ELF),
        help="ELF to read with arm-none-eabi-nm (default: $ELF or fireemblem8.elf)",
    )
    parser.add_argument(
        "--progress",
        default=DEFAULT_PROGRESS,
        help="progress.txt generated by scripts/calcprogress.py",
    )
    parser.add_argument(
        "--out-dir",
        default=DEFAULT_OUT_DIR,
        help="site output directory",
    )
    return parser.parse_args()


def git_value(args: list[str], fallback: str) -> str:
    try:
        return subprocess.check_output(["git", *args], text=True, stderr=subprocess.DEVNULL).strip()
    except (OSError, subprocess.CalledProcessError):
        return fallback


def normalize_path(path: str, repo_root: pathlib.Path, elf_path: pathlib.Path) -> str:
    normalized = path.replace("\\", "/")
    prefixes = []
    for candidate in (repo_root, elf_path.parent):
        try:
            prefixes.append(candidate.resolve().as_posix() + "/")
        except OSError:
            pass

    for prefix in prefixes:
        if normalized.startswith(prefix):
            return normalized[len(prefix) :]

    marker = f"/{PROJECT_NAME}/"
    if marker in normalized:
        return normalized.split(marker, 1)[1]

    for root in KNOWN_REL_ROOTS:
        needle = f"/{root}"
        if needle in normalized:
            return root + normalized.split(needle, 1)[1]

    return pathlib.PurePosixPath(normalized).name


def normalize_nm_line(line: str, repo_root: pathlib.Path, elf_path: pathlib.Path) -> str:
    def replace(match: re.Match[str]) -> str:
        rel = normalize_path(match.group(1), repo_root, elf_path)
        return f"\t{rel}:{match.group(2)}"

    return FILE_LINE_RE.sub(replace, line.rstrip("\n\r"))


def generate_symbols(elf_path: pathlib.Path, symbols_path: pathlib.Path, repo_root: pathlib.Path) -> int:
    if not elf_path.exists():
        raise FileNotFoundError(f"ELF not found: {elf_path}")

    process = subprocess.Popen(
        ["arm-none-eabi-nm", "-n", "-l", str(elf_path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    assert process.stdout is not None
    count = 0
    previous = None
    with symbols_path.open("w", encoding="utf-8", newline="\n") as output:
        for raw_line in process.stdout:
            line = normalize_nm_line(raw_line, repo_root, elf_path)
            if line == previous:
                continue
            output.write(line + "\n")
            previous = line
            count += 1

    stderr = process.stderr.read() if process.stderr is not None else ""
    rc = process.wait()
    if rc != 0:
        raise subprocess.CalledProcessError(rc, process.args, stderr=stderr)
    return count


def write_index(out_dir: pathlib.Path, progress_text: str) -> None:
    commit = git_value(["rev-parse", "--short=12", "HEAD"], "unknown")
    timestamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    index = f"""<!doctype html>
<html>
<head><meta charset=\"utf-8\"><title>fireemblem8j</title></head>
<body>
<h1>fireemblem8j</h1>
<p>commit: {html.escape(commit)}<br>generated: {html.escape(timestamp)}</p>
<ul>
<li><a href=\"progress.txt\">progress</a></li>
<li><a href=\"symbols.txt\">symbols</a></li>
</ul>
<pre>{html.escape(progress_text)}</pre>
</body>
</html>
"""
    (out_dir / "index.html").write_text(index, encoding="utf-8", newline="\n")


def main() -> int:
    args = parse_args()
    repo_root = pathlib.Path.cwd().resolve()
    elf_path = pathlib.Path(args.elf).expanduser()
    progress_path = pathlib.Path(args.progress)
    out_dir = pathlib.Path(args.out_dir)

    if not progress_path.exists():
        raise FileNotFoundError(f"progress file not found: {progress_path}")

    progress_text = progress_path.read_text(encoding="utf-8")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    (out_dir / "progress.txt").write_text(progress_text, encoding="utf-8", newline="\n")
    symbol_count = generate_symbols(elf_path, out_dir / "symbols.txt", repo_root)
    write_index(out_dir, progress_text)
    print(f"Generated {out_dir}/ with {symbol_count} symbol lines from {elf_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"gen_pages.py: error: {exc}", file=sys.stderr)
        raise SystemExit(1)
