#!/usr/bin/env python3
"""Generate the carve glue from the layout manifests.

Reads:
  layout/carved_rom.tsv   - ROM-resident decompiled sections
  layout/carved_ram.tsv   - RAM-resident (NOLOAD) sections
  layout/baseline_syms.tsv- symbols still living in the raw-ROM baseline
  ldscript.template.txt   - linker-script skeleton (@ROM_BODY@ / @RAM_BODY@)

Writes:
  asm/baserom.s   - incbin chunks covering the gaps between carved ROM sections
  ldscript.txt    - the linker script with carved sections spliced in order
  asm/jp_syms.s   - typed symbols for baseline-resident references

This keeps the byte-perfect baseline build correct as carves accumulate: the
incbin gaps are computed automatically, so adding a translation unit is just a
few manifest rows + `make layout`.
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

ROM = "baserom.gba"
ROM_SIZE = os.path.getsize(ROM) if os.path.exists(ROM) else 0x1000000


def read_rows(path):
    rows = []
    with open(path) as f:
        for ln in f:
            ln = ln.rstrip("\n")
            if not ln or ln.lstrip().startswith("#"):
                continue
            rows.append(ln.split("\t"))
    return rows


def read_manifest(base):
    """Read a layout manifest as the union of the legacy monolith ``<base>.tsv``
    and any per-task fragments under ``<base>.d/*.tsv`` (globbed in sorted order),
    with byte-identical duplicate rows removed (two parallel tasks may re-derive
    the same row). The resulting **ROM** is order-invariant: carved_rom is
    address-sorted below, and carved_ram / baseline_syms place every section and
    symbol at its explicit address. Fragment *file* order is itself fixed (a
    deterministic sorted glob); for carved_ram / baseline_syms it affects only the
    generated ldscript's internal section *numbering/order*, never the ROM bytes.
    So many carves can run in parallel, each writing only its own fragment, and
    the integrator can merge them in any order with no shared-file conflict and a
    byte-identical ROM.
    """
    rows = []
    mono = base + ".tsv"
    if os.path.exists(mono):
        rows += read_rows(mono)
    frag_dir = base + ".d"
    if os.path.isdir(frag_dir):
        for fn in sorted(os.listdir(frag_dir)):
            if fn.endswith(".tsv"):
                rows += read_rows(os.path.join(frag_dir, fn))
    seen, out = set(), []
    for r in rows:
        key = tuple(r)
        if key not in seen:
            seen.add(key)
            out.append(r)
    return out


def write_if_changed(path, content):
    """Write only when the content differs, so an unchanged generated file keeps
    its mtime and the build does not needlessly rebuild downstream objects (the
    Makefile re-runs gen_layout whenever any manifest/fragment dir changes; this
    keeps that incremental)."""
    try:
        if open(path).read() == content:
            return
    except OSError:
        pass
    with open(path, "w") as f:
        f.write(content)


# --- ROM sections + gaps ---
rom = []
for r in read_manifest("layout/carved_rom"):
    start, end, sec = int(r[0], 16), int(r[1], 16), r[2]
    rom.append((start, end, sec))
rom.sort()
prev = 0
for start, end, sec in rom:
    if start < prev:
        sys.exit(f"overlap/order error at {start:#x} (prev end {prev:#x}) in carved_rom.tsv")
    if end <= start:
        sys.exit(f"bad range {start:#x}..{end:#x}")
    prev = end
if prev > ROM_SIZE:
    sys.exit(f"carved past ROM end: {prev:#x} > {ROM_SIZE:#x}")

# Build ordered .rom body + the incbin chunks for the gaps.
rom_body, baserom_chunks = [], []
gap_i = 0
addr = 0
def add_gap(lo, hi):
    global gap_i
    if hi <= lo:
        return
    count = "" if hi == ROM_SIZE else f", 0x{hi - lo:X}"
    baserom_chunks.append(
        f"\t.section .gap_{gap_i}, \"ax\", %progbits\n"
        f"\t.incbin \"{ROM}\", 0x{lo:X}{count}\t@ 0x{lo:06X}..0x{hi:06X}\n")
    rom_body.append(f"        asm/baserom.o(.gap_{gap_i});")
    gap_i += 1

for start, end, sec in rom:
    add_gap(addr, start)
    rom_body.append(f"        {sec};")
    addr = end
add_gap(addr, ROM_SIZE)

# --- RAM (NOLOAD) sections ---
ram_body = []
for i, r in enumerate(read_manifest("layout/carved_ram")):
    a, region, secs = int(r[0], 16), r[1], r[2]
    note = r[3] if len(r) > 3 else ""
    inner = " ".join(f"{s}" for s in secs.split())
    ram_body.append(
        f"    .bss_{i} 0x{a:08X} (NOLOAD) : {{ {inner} }} > {region}"
        + (f"  /* {note} */" if note else ""))

# --- baseline symbols ---
syms = ["@ Generated by scripts/gen_layout.py from layout/baseline_syms.tsv.",
        "@ Typed symbols for baseline-resident code/data referenced by decompiled",
        "@ source, so the linker resolves them at their JP address (Thumb BL gets",
        "@ no interwork veneer). Do not edit by hand.\n", "\t.thumb\n"]
baseline_rows = read_manifest("layout/baseline_syms")
# Parallel-safe suppression: a sym aliased in baseline_syms (added by some carved
# object that CALLS it) becomes a multiple-definition once another carve provides
# its REAL object definition. Rather than EDIT the shared baseline_syms monolith
# (not parallel-safe), a carve drops the now-redundant name into its own additive
# drop-fragment layout/baseline_syms_drop.d/<task>.tsv (one name per line); we
# exclude those names here. Order-/source-independent: dropping a name absent here
# is a no-op, and the carved object's .text is the real definition regardless.
drop = set()
drop_dir = "layout/baseline_syms_drop.d"
if os.path.isdir(drop_dir):
    for fn in sorted(os.listdir(drop_dir)):
        if fn.endswith(".tsv"):
            for ln in open(os.path.join(drop_dir, fn)):
                ln = ln.strip()
                if ln and not ln.startswith("#"):
                    drop.add(ln.split("\t")[0])
baseline_rows = [r for r in baseline_rows if r[0] not in drop]
for r in baseline_rows:
    name, addr_s, typ = r[0], r[1], r[2]
    a = int(addr_s, 16)
    syms.append(f"\t.global {name}")
    if typ == "thumb":
        syms.append(f"\t.type   {name}, %function")
        syms.append(f"\t.thumb_func")
        syms.append(f"\t.set    {name}, 0x{a:08X} + 1\n")
    elif typ == "arm":
        syms.append(f"\t.type   {name}, %function")
        syms.append(f"\t.set    {name}, 0x{a:08X}\n")
    else:  # data
        syms.append(f"\t.set    {name}, 0x{a:08X}\n")

# --- emit (write-if-changed: keeps an unchanged rebuild from touching mtimes) ---
tmpl = open("ldscript.template.txt").read()
ld = tmpl.replace("@ROM_BODY@", "\n".join(rom_body)).replace("@RAM_BODY@", "\n".join(ram_body) + ("\n" if ram_body else ""))
write_if_changed("ldscript.txt", "/* GENERATED by scripts/gen_layout.py - edit layout/*.tsv + template instead. */\n" + ld)

hdr = ("@ Raw-ROM decompilation baseline (GENERATED by scripts/gen_layout.py).\n"
       "@ The original ROM is incbinned in the gaps between carved sections so the\n"
       "@ build stays byte-perfect. Edit layout/carved_rom.tsv, not this file.\n\n")
write_if_changed("asm/baserom.s", hdr + "\n".join(baserom_chunks) + "\n")
write_if_changed("asm/jp_syms.s", "\n".join(syms) + "\n")

decoded = sum(e - s for s, e, _ in rom)
print(f"layout: {len(rom)} ROM sections, {gap_i} baseline gaps, "
      f"{len(ram_body)} RAM sections, {len(baseline_rows)} baseline syms")
print(f"decompiled ROM bytes: 0x{decoded:X} / 0x{ROM_SIZE:X} ({100*decoded/ROM_SIZE:.4f}%)")
