#!/usr/bin/env python3
"""Ingest laqieer/FE_GBA_Function_Library as a REFERENCE-ONLY US<->JP hint map.

Implements decision D25 (see ``docs/decisions.md`` and
``docs/bindiff-investigation.md``). The library is a years-old, bindiff-merged
cross-region FE correspondence DB with an FE8J column. It is **not guaranteed
correct** (owner's own warning): it is a HINT source for the asm->C porting step,
NEVER a build input. Nothing reads the emitted TSV from the build, so it cannot
affect ``make compare``; every downstream use is gated by the sha1 oracle.

What it does
------------
1. Locate the library. Prefer ``/tmp/FE_GBA_Function_Library`` if present, else
   clone ``https://github.com/laqieer/FE_GBA_Function_Library`` into a cache dir.
2. Parse ``functions.md`` (the rich table: ``|FE6|FE7J|FE7U|FE8J|FE8U|Name|...``)
   for the FE8J address, FE8U address, and the stored (stale) name. ``functions.ls``
   is used only as a corroborating name<->FE8U-address source.
3. Normalize every address to ``0x`` + 8 hex digits (the library stores bare,
   leading-zero-stripped values like ``8003608``).
4. Filter to ROM ``0x08`` JP functions only (drop the ~7 RAM ``0x03`` entries and
   the ``0`` no-JP-address rows -- they are not JP ROM functions).
5. Tier each entry by cross-checking its ``jp_addr`` against
   ``layout/us_jp_funcmap.tsv`` (the byte-match ground truth):
     - in funcmap AND us_addr agrees -> ``funcmap-agree``
     - in funcmap AND us_addr disagrees -> ``funcmap-disagree`` (quarantine)
     - not in funcmap -> ``new-hint`` (the region-different carve queue)
6. Resolve ``us_name_current`` LIVE from ``../fireemblem8u`` (``nm`` on the ELF;
   ``.map`` as a fallback) at ``us_addr`` -- do NOT import the stored name; keep
   it only in ``lib_name_stale`` for provenance.
7. Emit ``reference/maps/funclib_us_jp.tsv`` with a "HINT, NOT TRUTH" banner.

Output columns (tab-separated):
    jp_addr  us_addr  us_name_current  lib_name_stale  confidence  source

Deterministic: re-running over the same inputs regenerates an identical TSV.
"""

import os
import re
import subprocess
import sys

# --- Paths (absolute). ---------------------------------------------------------
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
US_DIR = "/home/laqieer/fireemblem8u"
US_ELF = os.path.join(US_DIR, "fireemblem8.elf")
US_MAP = os.path.join(US_DIR, "fireemblem8.map")
FUNCMAP = os.path.join(REPO_ROOT, "layout", "us_jp_funcmap.tsv")
OUT_TSV = os.path.join(REPO_ROOT, "reference", "maps", "funclib_us_jp.tsv")

LIB_URL = "https://github.com/laqieer/FE_GBA_Function_Library"
LIB_TMP = "/tmp/FE_GBA_Function_Library"
LIB_CACHE = os.path.join(REPO_ROOT, ".cache", "FE_GBA_Function_Library")

NM = os.environ.get("NM", "arm-none-eabi-nm")

ROM_LO = 0x08000000
ROM_HI = 0x0A000000  # 0x08000000..0x09FFFFFF is cartridge ROM space

# The verbatim "HINT, NOT TRUTH" banner from docs/bindiff-investigation.md
# (ingestion-format section). Emitted as leading ``#`` comment lines.
BANNER = """\
# HINT, NOT TRUTH. Built ~2018 by a 0.8-threshold BinDiff+diaphora merge;
# owner states it is not guaranteed correct. ~99.4% agreement with the byte-match
# funcmap on the overlap, but the ~0.6% errors are non-random (transitive-stitch
# / bindiff row-shift) and stored NAMES are stale. Use the US ADDRESS as the key,
# resolve the current name from fireemblem8u, and let `make compare` validate.
# NEVER a build input.
#
# Source: laqieer/FE_GBA_Function_Library (functions.md FE8J/FE8U columns).
# Generated by scripts/ingest_funclib.py (D25). Reference-only; not read by the
# build. Columns:
#   jp_addr           JP ROM function address (0x + 8 hex), the lookup key.
#   us_addr           FE8U ROM address from the library (the trustworthy link key);
#                     `-` when the library has no US address for this JP function.
#   us_name_current   US-decomp symbol resolved LIVE from ../fireemblem8u at us_addr
#                     (nm/.map); empty if no symbol resolves there. USE THIS NAME.
#   lib_name_stale    The library's stored ~2018 name, provenance only -- DO NOT use.
#   confidence        funcmap-agree | funcmap-disagree | new-hint  (see banner).
#   source            provenance tag.
# Usage: look up a JP addr -> get the US source function to port; oracle-gated by
# `make compare`; QUARANTINE/deprioritize `funcmap-disagree` rows.
"""


def log(msg):
    print(f"[ingest_funclib] {msg}", file=sys.stderr)


# --- Library location ----------------------------------------------------------
def locate_library():
    """Return the path to a checkout of FE_GBA_Function_Library.

    Prefer /tmp/FE_GBA_Function_Library if it already contains functions.md;
    otherwise clone the upstream repo into a repo-local cache dir (idempotent).
    """
    for cand in (LIB_TMP, LIB_CACHE):
        if os.path.isfile(os.path.join(cand, "functions.md")):
            log(f"using existing library at {cand}")
            return cand
    os.makedirs(os.path.dirname(LIB_CACHE), exist_ok=True)
    log(f"cloning {LIB_URL} -> {LIB_CACHE}")
    subprocess.run(
        ["git", "clone", "--depth", "1", LIB_URL, LIB_CACHE],
        check=True,
    )
    if not os.path.isfile(os.path.join(LIB_CACHE, "functions.md")):
        raise SystemExit(f"clone succeeded but {LIB_CACHE}/functions.md missing")
    return LIB_CACHE


# --- Address normalization -----------------------------------------------------
def norm_addr(raw):
    """Normalize a bare library address to (int, '0x' + 8 hex), or None.

    The library stores leading-zero-stripped hex without a 0x prefix
    (e.g. '8003608'). '0' means "no address in this game". Returns None for
    those and for anything unparseable.
    """
    raw = (raw or "").strip()
    if not raw or raw == "0":
        return None
    try:
        val = int(raw, 16)
    except ValueError:
        return None
    if val == 0:
        return None
    return val, f"0x{val:08X}"


# --- functions.md parsing ------------------------------------------------------
def parse_functions_md(path):
    """Parse functions.md -> list of (jp_int, jp_str, us_int|None, us_str|'-', name).

    Columns (pipe-delimited): | FE6 | FE7J | FE7U | FE8J | FE8U | Name | Decl | Comment |
    Only rows with a ROM (0x08) FE8J address are kept; RAM (0x03) and no-address
    (0) JP rows are dropped.
    """
    rows = []
    n_total = n_ram = n_noaddr = 0
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line.startswith("|"):
                continue
            cells = line.split("|")
            # Leading '|' yields an empty cells[0]; real columns start at index 1.
            if len(cells) < 8:
                continue
            fe8j_raw = cells[4].strip()
            fe8u_raw = cells[5].strip()
            name = cells[6].strip()
            # Skip the table header / separator rows.
            if fe8j_raw in ("FE8J", "----", ""):
                continue
            n_total += 1
            jp = norm_addr(fe8j_raw)
            if jp is None:
                n_noaddr += 1
                continue
            jp_int, jp_str = jp
            if not (ROM_LO <= jp_int < ROM_HI):
                # RAM (0x03...) or other non-ROM JP function -> drop per D25.
                n_ram += 1
                continue
            us = norm_addr(fe8u_raw)
            if us is None or not (ROM_LO <= us[0] < ROM_HI):
                us_int, us_str = None, "-"
            else:
                us_int, us_str = us
            rows.append((jp_int, jp_str, us_int, us_str, name))
    log(
        f"functions.md: {n_total} FE8J data rows, kept {len(rows)} ROM funcs, "
        f"dropped {n_ram} non-ROM(RAM) + {n_noaddr} no-JP-address"
    )
    return rows


# --- funcmap (byte-match ground truth) -----------------------------------------
def load_funcmap(path):
    """Return {jp_addr_int: set(us_addr_int)} from layout/us_jp_funcmap.tsv.

    A JP addr can carry several US candidates (masked tier), so the value is a
    set; tier determination treats agreement with ANY candidate as agreement.
    """
    jp_to_us = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            try:
                jp = int(parts[0], 16)
                us = int(parts[1], 16)
            except ValueError:
                continue
            jp_to_us.setdefault(jp, set()).add(us)
    log(f"funcmap: {len(jp_to_us)} unique JP addresses (byte-match ground truth)")
    return jp_to_us


# --- US name resolution (live) -------------------------------------------------
_BOUNDARY_RE = re.compile(r"(_End|_Start|End|Start)$")


def _pick_name(names):
    """Deterministically pick the best function name among collisions.

    Prefer a non-boundary symbol (not a *_End/_Start marker), then the shortest
    name, then lexicographically smallest -- fully deterministic.
    """
    if len(names) == 1:
        return next(iter(names))
    ranked = sorted(
        names,
        key=lambda s: (1 if _BOUNDARY_RE.search(s) else 0, len(s), s),
    )
    return ranked[0]


def load_us_names():
    """Build {us_addr_int: name} from the US ELF (nm), falling back to the .map.

    nm gives function symbols (type t/T, mapping symbols excluded). The
    toolchain nm emits even Thumb entry addresses (matching the library). The
    .map fills any address nm did not name. Returns the merged dict.
    """
    addr_names = {}

    # Primary: nm function symbols.
    if os.path.isfile(US_ELF):
        out = subprocess.run(
            [NM, US_ELF], check=True, capture_output=True, text=True
        ).stdout
        per_addr = {}
        for line in out.splitlines():
            parts = line.split()
            if len(parts) != 3:
                continue
            addr_s, typ, name = parts
            if typ not in ("t", "T"):
                continue
            if name.startswith("$"):  # ARM/Thumb mapping symbol
                continue
            try:
                addr = int(addr_s, 16)
            except ValueError:
                continue
            per_addr.setdefault(addr, set()).add(name)
        for addr, names in per_addr.items():
            addr_names[addr] = _pick_name(names)
        log(f"nm: resolved {len(addr_names)} function addresses from {US_ELF}")
    else:
        log(f"WARNING: {US_ELF} not found; nm name resolution skipped")

    # Fallback: .map symbol definitions ('  0x<addr>  <symbol>') for any addr nm
    # did not cover. Skip assignment lines (containing '=').
    if os.path.isfile(US_MAP):
        map_re = re.compile(
            r"^\s+0x(0[89A-Fa-f][0-9A-Fa-f]{6})\s+([A-Za-z_][A-Za-z0-9_]*)\s*$"
        )
        map_per_addr = {}
        with open(US_MAP, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                if "=" in line:
                    continue
                m = map_re.match(line)
                if not m:
                    continue
                addr = int(m.group(1), 16)
                map_per_addr.setdefault(addr, set()).add(m.group(2))
        added = 0
        for addr, names in map_per_addr.items():
            if addr not in addr_names:
                addr_names[addr] = _pick_name(names)
                added += 1
        log(f".map: added {added} fallback names from {US_MAP}")
    else:
        log(f"WARNING: {US_MAP} not found; .map fallback skipped")

    return addr_names


# --- main ----------------------------------------------------------------------
def main():
    lib_dir = locate_library()
    md_path = os.path.join(lib_dir, "functions.md")
    if not os.path.isfile(md_path):
        raise SystemExit(f"missing {md_path}")

    rows = parse_functions_md(md_path)
    funcmap = load_funcmap(FUNCMAP)
    us_names = load_us_names()

    out_rows = []
    tiers = {"funcmap-agree": 0, "funcmap-disagree": 0, "new-hint": 0}
    for jp_int, jp_str, us_int, us_str, stale in rows:
        # Tier by cross-checking jp_addr against the byte-match funcmap.
        if jp_int in funcmap:
            if us_int is not None and us_int in funcmap[jp_int]:
                tier = "funcmap-agree"
            else:
                tier = "funcmap-disagree"
        else:
            tier = "new-hint"
        tiers[tier] += 1

        # Resolve the CURRENT US name live (never import the stale stored name).
        cur = us_names.get(us_int, "") if us_int is not None else ""

        out_rows.append(
            (jp_str, us_str, cur, stale, tier, "FE_GBA_Function_Library")
        )

    # Deterministic order: by JP address.
    out_rows.sort(key=lambda r: int(r[0], 16))

    os.makedirs(os.path.dirname(OUT_TSV), exist_ok=True)
    with open(OUT_TSV, "w", encoding="utf-8") as fh:
        fh.write(BANNER)
        fh.write(
            "jp_addr\tus_addr\tus_name_current\tlib_name_stale\tconfidence\tsource\n"
        )
        for r in out_rows:
            fh.write("\t".join(r) + "\n")

    log(f"wrote {len(out_rows)} rows -> {OUT_TSV}")
    log(
        "tier histogram: "
        f"new-hint={tiers['new-hint']} "
        f"funcmap-agree={tiers['funcmap-agree']} "
        f"funcmap-disagree={tiers['funcmap-disagree']}"
    )
    # Report how many new-hints carry a usable US address (the real carve queue).
    new_with_us = sum(1 for r in out_rows if r[4] == "new-hint" and r[1] != "-")
    log(f"new-hint with US address (carve queue): {new_with_us}")


if __name__ == "__main__":
    main()
