/* NON_MATCHING (m2c first-pass seed): byte source is asm/sub_8001208.s @ JP 0x08001208
 * (region-different, gbadisasm descriptive asm; the carved_rom row places those
 * bytes). This C DOCUMENTS / stages the function and is NOT in the make-compare
 * oracle -- it is compiled only by `make nonmatching` (prove-builds), never
 * linked, never sha1'd.
 *
 * Generated by scripts/m2c_firstpass.py (m2c --target gba, arch arm) and named
 * from the funclib US correspondence (SetInterrupt_LCDVBlank @ new-hint). It is a SEED: m2c cannot
 * resolve PC-relative literal pools (D24), so `_08xxxxxx` symbols appear as
 * `extern` placeholders -- readable, compilable, but NOT yet byte-matching.
 * Graduate via the permuter -> matching C; `make compare` is the sole oracle.
 * No #ifdef, no asm in this file. */
#include "global.h"

/* m2c --valid-syntax prelude: macros m2c emits for unknown types / untyped
 * field access (from tools/m2c/m2c_macros.h). They keep the SEED compilable
 * before hand-cleaning; graduating to matching C replaces them with real types.
 */
#ifndef M2C_FIELD
typedef s32 M2C_UNK;
typedef s8  M2C_UNK8;
typedef s16 M2C_UNK16;
typedef s32 M2C_UNK32;
#define M2C_FIELD(expr, type_ptr, offset) (*(type_ptr)((s8 *)(expr) + (offset)))
#define M2C_BITWISE(type, expr) ((type)(expr))
#define M2C_ERROR(desc) (0)
#define M2C_CARRY 0
#define M2C_OVERFLOW(a) (0)
#define CLZ(x) (0)
#define ROTATE_RIGHT(x, shift) (0)
#define ARM_RRX(x, carry) (0)
#define M2C_MEMCPY_ALIGNED memcpy
#define M2C_MEMCPY_UNALIGNED memcpy
#define M2C_STRUCT_COPY memcpy
#endif

extern void *_0800122C;
extern u16 *_08001230;
extern void *_08001250;
extern u16 *_08001254;
extern s32 _08001258;

void SetInterrupt_LCDVBlank(void *arg0)
{
    u16 *var_r2;
    u16 var_r0;

    if (arg0 != NULL)
    {
        M2C_FIELD(_0800122C, u8 *, 4) = (u8) (M2C_FIELD(_0800122C, u8 *, 4) | 8);
        SetIRQHandler(0, arg0);
        var_r2 = _08001230;
        var_r0 = *var_r2 | 1;
    }
    else
    {
        M2C_FIELD(_08001250, u8 *, 4) = (u8) (-9 & M2C_FIELD(_08001250, u8 *, 4));
        var_r2 = _08001254;
        var_r0 = _08001258 & *var_r2;
    }
    *var_r2 = var_r0;
}
