/* NON_MATCHING (m2c first-pass seed): byte source is asm/sub_8000D68.s @ JP 0x08000d68
 * (region-different, gbadisasm descriptive asm; the carved_rom row places those
 * bytes). This C DOCUMENTS / stages the function and is NOT in the make-compare
 * oracle -- it is compiled only by `make nonmatching` (prove-builds), never
 * linked, never sha1'd.
 *
 * Generated by scripts/m2c_firstpass.py (m2c --target gba, arch arm) and named
 * from the funclib US correspondence (CopyToPaletteBuffer @ new-hint). It is a SEED: m2c cannot
 * resolve PC-relative literal pools (D24), so `_08xxxxxx` symbols appear as
 * `extern` placeholders -- readable, compilable, but NOT yet byte-matching.
 * Graduate via the permuter -> matching C; `make compare` is the sole oracle.
 * No #ifdef, no asm in this file. */
#include "global.h"

/* m2c --valid-syntax prelude: macros m2c emits for unknown types / untyped
 * field access (from tools/m2c/m2c_macros.h). They keep the SEED compilable
 * before hand-cleaning; graduating to matching C replaces them with real types.
 */
#ifndef M2C_FIELD
typedef s32 M2C_UNK;
typedef s8  M2C_UNK8;
typedef s16 M2C_UNK16;
typedef s32 M2C_UNK32;
#define M2C_FIELD(expr, type_ptr, offset) (*(type_ptr)((s8 *)(expr) + (offset)))
#define M2C_BITWISE(type, expr) ((type)(expr))
#define M2C_ERROR(desc) (0)
#define M2C_CARRY 0
#define M2C_OVERFLOW(a) (0)
#define CLZ(x) (0)
#define ROTATE_RIGHT(x, shift) (0)
#define ARM_RRX(x, carry) (0)
#define M2C_MEMCPY_ALIGNED memcpy
#define M2C_MEMCPY_UNALIGNED memcpy
#define M2C_STRUCT_COPY memcpy
#endif

M2C_UNK sub_80D636C(s32, s32, u32);                 /* extern */
M2C_UNK sub_80D6370(s32, s32, u32);                 /* extern */
extern s32 _08000D90;
extern s32 _08000DBC;
extern s8 *_08000DC0;

void CopyToPaletteBuffer(s32 arg0, s32 arg1, u32 arg2)
{
    u32 var_r2;

    if (0x1F & arg2)
    {
        sub_80D6370(arg0, ((arg1 >> 1) * 2) + _08000D90, (u32) ((arg2 + (arg2 >> 0x1F)) << 0xA) >> 0xB);
    }
    else
    {
        var_r2 = arg2;
        if ((s32) var_r2 < 0)
        {
            var_r2 += 3;
        }
        sub_80D636C(arg0, ((arg1 >> 1) * 2) + _08000DBC, (u32) (var_r2 << 9) >> 0xB);
    }
    *_08000DC0 = 1;
}
