/* NON_MATCHING (m2c first-pass seed): byte source is asm/sub_80010FC.s @ JP 0x080010fc
 * (region-different, gbadisasm descriptive asm; the carved_rom row places those
 * bytes). This C DOCUMENTS / stages the function and is NOT in the make-compare
 * oracle -- it is compiled only by `make nonmatching` (prove-builds), never
 * linked, never sha1'd.
 *
 * Generated by scripts/m2c_firstpass.py (m2c --target gba, arch arm) and named
 * from the funclib US correspondence (FlushBackgrounds @ new-hint). It is a SEED: m2c cannot
 * resolve PC-relative literal pools (D24), so `_08xxxxxx` symbols appear as
 * `extern` placeholders -- readable, compilable, but NOT yet byte-matching.
 * Graduate via the permuter -> matching C; `make compare` is the sole oracle.
 * No #ifdef, no asm in this file. */
#include "global.h"

/* m2c --valid-syntax prelude: macros m2c emits for unknown types / untyped
 * field access (from tools/m2c/m2c_macros.h). They keep the SEED compilable
 * before hand-cleaning; graduating to matching C replaces them with real types.
 */
#ifndef M2C_FIELD
typedef s32 M2C_UNK;
typedef s8  M2C_UNK8;
typedef s16 M2C_UNK16;
typedef s32 M2C_UNK32;
#define M2C_FIELD(expr, type_ptr, offset) (*(type_ptr)((s8 *)(expr) + (offset)))
#define M2C_BITWISE(type, expr) ((type)(expr))
#define M2C_ERROR(desc) (0)
#define M2C_CARRY 0
#define M2C_OVERFLOW(a) (0)
#define CLZ(x) (0)
#define ROTATE_RIGHT(x, shift) (0)
#define ARM_RRX(x, carry) (0)
#define M2C_MEMCPY_ALIGNED memcpy
#define M2C_MEMCPY_UNALIGNED memcpy
#define M2C_STRUCT_COPY memcpy
#endif

M2C_UNK ApplyColorAddition_ClampMax(s8);            /* extern */
M2C_UNK ApplyColorAddition_ClampMin(s8);            /* extern */
M2C_UNK sub_80D636C(s32, s32, s32);                 /* extern */
extern u8 *_0800118C;
extern s32 _08001190;
extern void *_08001194;
extern s32 _08001198;
extern s32 _0800119C;
extern s32 _080011A0;
extern s8 *_080011A4;
extern void *_080011A8;
extern s32 _080011AC;

void FlushBackgrounds(void)
{
    s8 temp_r1;
    u8 *temp_r4;

    temp_r4 = _0800118C;
    if (1 & *temp_r4)
    {
        sub_80D636C(_08001190, M2C_FIELD(_08001194, s32 *, 0), 0x200);
    }
    if (2 & *temp_r4)
    {
        sub_80D636C(_08001198, M2C_FIELD(_08001194, s32 *, 4), 0x200);
    }
    if (4 & *temp_r4)
    {
        sub_80D636C(_0800119C, M2C_FIELD(_08001194, s32 *, 8), 0x200);
    }
    if (8 & *temp_r4)
    {
        sub_80D636C(_080011A0, M2C_FIELD(_08001194, s32 *, 0xC), 0x200);
    }
    *temp_r4 = 0;
    if (*_080011A4 == 1)
    {
        *_080011A4 = 0;
        temp_r1 = M2C_FIELD(_080011A8, s8 *, 0x68);
        if (temp_r1 == 0)
        {
            sub_80D636C(_080011AC, 0x05000000, 0x100);
            return;
        }
        if ((s32) temp_r1 > 0)
        {
            ApplyColorAddition_ClampMax((s8) (u8) M2C_FIELD(_080011A8, s8 *, 0x68));
            return;
        }
        ApplyColorAddition_ClampMin((s8) (u8) M2C_FIELD(_080011A8, s8 *, 0x68));
    }
}
