#!/usr/bin/env python3
"""misc_gfx3 -- final long-tail graphics blobs from mixed dat_*.s files (Phase-1).

Third/cleanup batch: the last mixed `dat_*.s` files that still had unextracted
graphics symbols (map-anim silence FX, world-map highlight maps, stone-shatter
anim, op-subtitle 00/01, IntelligentSystems logo, tri-pegasus BG). Carves ONLY
the graphics-prefixed symbols and leaves non-graphics symbols as incbin (honest).

Extracted FRESH from the JP ROM, byte-verified (LZ77 -> DECOMPRESSED .bin;
palette -> .pal -> .gbapal; bit-15-set / verbatim -> .bin direct).

NOTE: gGfx_OpSubtitle_05 is deliberately NOT included -- it is a region-different
feimg2 FETSATOOL graphic that gbagfx cannot reproduce (left as incbin, honest).

Usage:
  graphics/misc_gfx3/extract_misc_gfx3.py            # dry-run / verify
  graphics/misc_gfx3/extract_misc_gfx3.py --apply    # commit + rewrite + .mk
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "_lib"))
import extract_mixed_gfx as m  # noqa: E402

GLOBS = [
    "asm/dat_anim_mapanim_berserk_silence.s", "asm/dat_anim_worldmap_highlight.s",
    "asm/dat_const_data_1C0AFC.s", "asm/dat_data_opanim_gfx_p27.s",
    "asm/dat_data_opanim_gfx_p26.s", "asm/dat_gGfx_OpSubtitle_00_ref.s",
    "asm/dat_gGfx_OpSubtitle_01_ref.s", "asm/dat_Img_WmHightLightMap7_ref.s",
    "asm/dat_anim_worldmap_highlight_p5.s", "asm/dat_anim_worldmap_highlight_p7.s",
    "asm/dat_const_data_E162A_p0.s",
]

HEADER = (
    "graphics/misc_gfx3 -- final long-tail graphics blobs carved out of mixed\n"
    "dat_*.s files (map-anim silence FX, worldmap highlight maps, stone-shatter\n"
    "anim, op-subtitle 00/01, IntelligentSystems logo, tri-pegasus BG). Non-graphics\n"
    "symbols stay as incbin. LZ77 -> .bin (%.lz: %); palette -> .pal (-> .gbapal);\n"
    "verbatim -> .bin direct. Auto-generated by graphics/misc_gfx3/extract_misc_gfx3.py."
)


if __name__ == "__main__":
    apply = "--apply" in sys.argv
    m.run(out_dir="graphics/misc_gfx3", mk_name="misc_gfx3.mk",
          globs=GLOBS, header=HEADER, apply=apply)
