# graphics/misc_gfx3 -- final long-tail graphics blobs carved out of mixed
# dat_*.s files (map-anim silence FX, worldmap highlight maps, stone-shatter
# anim, op-subtitle 00/01, IntelligentSystems logo, tri-pegasus BG). Non-graphics
# symbols stay as incbin. LZ77 -> .bin (%.lz: %); palette -> .pal (-> .gbapal);
# verbatim -> .bin direct. Auto-generated by graphics/misc_gfx3/extract_misc_gfx3.py.

asm/dat_Img_WmHightLightMap7_ref.o: \
  graphics/misc_gfx3/Img_WmHightLightMap7.bin.lz

asm/dat_anim_mapanim_berserk_silence.o: \
  graphics/misc_gfx3/Img_ManimSilenceBgfx.bin.lz \
  graphics/misc_gfx3/Img_ManimSilenceObjfx.bin.lz \
  graphics/misc_gfx3/Pal_ManimSilencefx.gbapal

asm/dat_anim_worldmap_highlight.o: \
  graphics/misc_gfx3/Img_WmHightLightMap2.bin.lz \
  graphics/misc_gfx3/Img_WmHightLightMapFrecia.bin.lz \
  graphics/misc_gfx3/Pal_WmHighLightNationMap.gbapal

asm/dat_anim_worldmap_highlight_p5.o: \
  graphics/misc_gfx3/Img_WmHightLightMap4.bin.lz

asm/dat_anim_worldmap_highlight_p7.o: \
  graphics/misc_gfx3/Img_WmHightLightMap5.bin.lz

asm/dat_const_data_1C0AFC.o: \
  graphics/misc_gfx3/gImg_StoneShatterAnim.bin.lz \
  graphics/misc_gfx3/gPal_StoneShatterAnim.gbapal

asm/dat_const_data_E162A_p0.o: \
  graphics/misc_gfx3/Img_TriPegasusKnightBG.bin.lz

asm/dat_data_opanim_gfx_p26.o: \
  graphics/misc_gfx3/Tsa_IntelligentSystems.bin.lz

asm/dat_data_opanim_gfx_p27.o: \
  graphics/misc_gfx3/Img_IntelligentSystems.bin.lz

src/data/op_subtitle/op_subtitle_gfx.o: \
  graphics/misc_gfx3/gGfx_OpSubtitle_00.bin.lz

src/data/op_subtitle/op_subtitle_gfx.o: \
  graphics/misc_gfx3/gGfx_OpSubtitle_01.bin.lz

