#include "gbafe.h"

void AutoGenerateUnitdef(u8 idx, int jid, s8 x_from, s8 y_from, s8 x_to, s8 y_to)
{
    struct REDA * reda;

    reda = gUdefREDAs;
    reda[idx].x = x_to;
    reda[idx].y = y_to;
    reda[idx].flags = 0;
    reda[idx].a = 0;
    reda[idx].b = 0xFFFF;
    reda[idx].delayFrames = 30;


    gUdefs[idx].charIndex = CHARACTER_EIRIKA;
    gUdefs[idx].classIndex = jid;
    gUdefs[idx].leaderCharIndex = 0;
    gUdefs[idx].autolevel = false;
    gUdefs[idx].allegiance = FACTION_ID_RED;
    gUdefs[idx].level = 1;
    gUdefs[idx].xPosition = x_from;
    gUdefs[idx].yPosition = y_from;
    gUdefs[idx].genMonster = false;
    gUdefs[idx].itemDrop = true;
    gUdefs[idx].unk_05_7 = false;
    gUdefs[idx].extraData = 0;
    gUdefs[idx].redaCount = 1;
    gUdefs[idx].redas = &reda[idx];

    gUdefs[idx].items[0] = 0;
    gUdefs[idx].items[1] = 0;
    gUdefs[idx].items[2] = 0;
    gUdefs[idx].items[3] = 0;

    gUdefs[idx].ai[0] = 0;
    gUdefs[idx].ai[1] = 0;
    gUdefs[idx].ai[2] = 0;
    gUdefs[idx].ai[3] = 0;
}

void SetupAutoGeneratedUnitdefs(void)
{
    AutoGenerateUnitdef(0, gAutoUdefJids[gUdefCnt][0], 0, 2, 14, 2);
    AutoGenerateUnitdef(1, gAutoUdefJids[gUdefCnt][1], 0, 3, 14, 3);
    AutoGenerateUnitdef(2, gAutoUdefJids[gUdefCnt][2], 0, 4, 14, 4);
    AutoGenerateUnitdef(3, gAutoUdefJids[gUdefCnt][3], 0, 5, 14, 5);

    /* Terminator */
    gUdefs[4].charIndex = 0;

    gUdefCnt++;
    if (gAutoUdefJids[gUdefCnt][0] == 0)
        gUdefCnt = 0;
}
