#include "global.h"
#include "bmunit.h"
#include "player_interface.h"
#include "bmitem.h"
#include "fontgrp.h"
#include "hardware.h"
#include "m4a.h"
#include "soundwrapper.h"
#include "statscreen.h"
#include "uiutils.h"
#include "bmcontainer.h"
#include "mu.h"
#include "icon.h"
#include "ctc.h"
#include "bmio.h"
#include "face.h"
#include "bm.h"
#include "bmmind.h"
#include "scene.h"
#include "prepscreen.h"
#include "bmshop.h"
#include "bmlib.h"
#include "mapanim.h"
#include "helpbox.h"
#include "worldmap.h"
#include "gba_sprites.h"
#include "constants/faces.h"
#include "constants/items.h"
#include "constants/songs.h"

void Shop_AnythingElseContinueDialogue(struct ProcShop * proc)
{
    StartShopDialogue(0x840, proc);
    // SHOP_TYPE_ARMORY: "Do you need anything else?[NL][ShopContinue]"
    // SHOP_TYPE_VENDOR: "Can I do anything else for you?[.][NL][ShopContinue]"
    // SHOP_TYPE_SECRET_SHOP: "Is there anything else you need?[NL][ShopContinue]"
}
