#include "global.h"

#include "ctc.h"
#include "worldmap.h"

// gWMNodeIconData is region-identical to US (pointers resolve to the JP gObject_* sprite frames).
// The sibling table gWMNodeData is region-different (JP nameTextId / ItemList_WM_* layout) and stays as a carved incbin.

const struct NodeIcon gWMNodeIconData[] =
{
    {
        .sheetTileId = 0x0080,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 19,
        .yFlagOrigin = 1,
    },
    {
        .sheetTileId = 0x0084,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0088,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0088,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0088,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0092,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 8,
        .yFlagOrigin = 1,
    },
    {
        .sheetTileId = 0x009A,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 5,
    },
    {
        .sheetTileId = 0x0014,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 4,
    },
    {
        .sheetTileId = 0x0018,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 4,
    },
    {
        .sheetTileId = 0x0098,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 8,
        .yFlagOrigin = 3,
    },
    {
        .sheetTileId = 0x00D2,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 6,
        .yFlagOrigin = 2,
    },
    {
        .sheetTileId = 0x0094,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 10,
        .yFlagOrigin = 2,
    },
    {
        .sheetTileId = 0x001C,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 11,
    },
    {
        .sheetTileId = 0x0090,
        .pSpriteData = gObject_16x32,
        .xCenter = 8,
        .yCenter = 24,
        .width = 16,
        .height = 32,
        .xFlagOrigin = 8,
        .yFlagOrigin = 24,
    },
    {
        .sheetTileId = 0x008C,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 24,
    },
    {
        .sheetTileId = 0x00D4,
        .pSpriteData = gObject_8x8,
        .xCenter = 4,
        .yCenter = 4,
        .width = 8,
        .height = 8,
        .xFlagOrigin = 4,
        .yFlagOrigin = 4,
    },
    {
        .sheetTileId = 0x0092,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 8,
        .yFlagOrigin = 8,
    },
};
