# graphics/unit_icon -- per-subsystem asset wiring (parallel-safe pin mechanism).
# Auto-included by the root Makefile via `-include $(GRAPHICS_MK)`. See
# graphics/misc/misc.mk for the convention.
#
# asm/dat_const_data_unit_icon_wait.s .incbins 107 REBUILT
# graphics/unit_icon/wait/*.4bpp.lz map-sprite sheets (each PNG -> 4bpp -> LZ77 via
# the generic %.4bpp:%.png and %.lz:% rules). Region-SAME with US (JP 0x081a71e0 ==
# US 0x081b7828). These are LZ-COMPRESSED, so -mindist must byte-match the original
# FE8 compressor PER ASSET: 95 sheets use gbagfx's default (mindist 2); the 12 below
# need mindist 1 (discovered by scripts/extract_graphics.py's 1/2/3 sweep).
UNIT_ICON_WAIT_LZ := $(patsubst %.png,%.4bpp.lz,$(wildcard graphics/unit_icon/wait/*.png))
asm/dat_const_data_unit_icon_wait.o: $(UNIT_ICON_WAIT_LZ)

graphics/unit_icon/wait/unit_icon_wait_Archer_sheet.4bpp.lz:      LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Archer_F_sheet.4bpp.lz:    LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Sage_sheet.4bpp.lz:        LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Pirate_sheet.4bpp.lz:      LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Monk_sheet.4bpp.lz:        LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Necromancer_sheet.4bpp.lz: LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Bonewalker_sheet.4bpp.lz:  LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Wight_sheet.4bpp.lz:       LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Wight_Bow_sheet.4bpp.lz:   LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Peer_sheet.4bpp.lz:        LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Prince_sheet.4bpp.lz:      LZ_FLAGS := -mindist 1
graphics/unit_icon/wait/unit_icon_wait_Unk77_sheet.4bpp.lz:       LZ_FLAGS := -mindist 1

# --- unit_icon/move map-sprite sheets (Phase 1, batch 2) ---------------------
# 82 region-SAME MOVE sheets across 80 dat_const_data_unit_icon_move_p*.o objects
# (each PNG -> 4bpp -> LZ77, gbagfx DEFAULT mindist 2 -> NO per-asset pins). The
# 14 region-DIFFERENT sheets and 2 (Bard/Dancer)_motion symbols without a
# matching US asset are LEFT as `.incbin "baserom.gba"` (honest). Generated by
# scripts/extract_graphics.py; per-object deps so each .4bpp.lz is rebuilt from
# its committed PNG before the .s that .incbins it is assembled.
asm/dat_const_data_unit_icon_move_p0.o: graphics/unit_icon/move/unit_icon_move_Ephraim_Lord_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p1.o: graphics/unit_icon/move/unit_icon_move_Eirika_Lord_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p4.o: graphics/unit_icon/move/unit_icon_move_Cavalier_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p5.o: graphics/unit_icon/move/unit_icon_move_Paladin_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p6.o: graphics/unit_icon/move/unit_icon_move_Armor_Knight_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p9.o: graphics/unit_icon/move/unit_icon_move_Thief_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p10.o: graphics/unit_icon/move/unit_icon_move_Manakete_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p11.o: graphics/unit_icon/move/unit_icon_move_Mercenary_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p12.o: graphics/unit_icon/move/unit_icon_move_Mercenary_F_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p15.o: graphics/unit_icon/move/unit_icon_move_Myrmidon_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p16.o: graphics/unit_icon/move/unit_icon_move_Myrmidon_F_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p19.o: graphics/unit_icon/move/unit_icon_move_Assassin_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p20.o: graphics/unit_icon/move/unit_icon_move_Assassin_F_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p21.o: graphics/unit_icon/move/unit_icon_move_Archer_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p22.o: graphics/unit_icon/move/unit_icon_move_Archer_F_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p23.o: graphics/unit_icon/move/unit_icon_move_Ranger_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p28.o: graphics/unit_icon/move/unit_icon_move_Wyvern_Knight_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p30.o: graphics/unit_icon/move/unit_icon_move_Mage_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p31.o: graphics/unit_icon/move/unit_icon_move_Mage_F_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p32.o: graphics/unit_icon/move/unit_icon_move_Sage_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p33.o: graphics/unit_icon/move/unit_icon_move_Sage_F_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p34.o: graphics/unit_icon/move/unit_icon_move_Mage_Knight_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p35.o: graphics/unit_icon/move/unit_icon_move_Mage_Knight_F_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p38.o: graphics/unit_icon/move/unit_icon_move_Shaman_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p39.o: graphics/unit_icon/move/unit_icon_move_Druid_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p40.o: graphics/unit_icon/move/unit_icon_move_Summoner_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p41.o: graphics/unit_icon/move/unit_icon_move_Rogue_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p42.o: graphics/unit_icon/move/unit_icon_move_Gorgonegg2_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p43.o: graphics/unit_icon/move/unit_icon_move_Great_Knight_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p44.o: graphics/unit_icon/move/unit_icon_move_Recruit_T1_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p48.o: graphics/unit_icon/move/unit_icon_move_Pupil_T2_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p49.o: graphics/unit_icon/move/unit_icon_move_Manakete_2_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p50.o: graphics/unit_icon/move/unit_icon_move_Manakete_Myrrh_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p51.o: graphics/unit_icon/move/unit_icon_move_Fighter_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p52.o: graphics/unit_icon/move/unit_icon_move_Warrior_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p53.o: graphics/unit_icon/move/unit_icon_move_Brigand_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p54.o: graphics/unit_icon/move/unit_icon_move_Pirate_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p55.o: graphics/unit_icon/move/unit_icon_move_Berserker_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p56.o: graphics/unit_icon/move/unit_icon_move_Monk_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p57.o: graphics/unit_icon/move/unit_icon_move_Priest_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p58.o: graphics/unit_icon/move/unit_icon_move_Bard_sheet.4bpp.lz graphics/unit_icon/move/unit_icon_move_Pegasus_Knight_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p59.o: graphics/unit_icon/move/unit_icon_move_Falcon_Knight_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p60.o: graphics/unit_icon/move/unit_icon_move_Cleric_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p61.o: graphics/unit_icon/move/unit_icon_move_Troubadour_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p62.o: graphics/unit_icon/move/unit_icon_move_Valkyrie_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p63.o: graphics/unit_icon/move/unit_icon_move_Dancer_sheet.4bpp.lz graphics/unit_icon/move/unit_icon_move_Soldier_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p64.o: graphics/unit_icon/move/unit_icon_move_Necromancer_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p65.o: graphics/unit_icon/move/unit_icon_move_Fleet_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p66.o: graphics/unit_icon/move/unit_icon_move_Phantom_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p67.o: graphics/unit_icon/move/unit_icon_move_Bonewalker_Bow_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p68.o: graphics/unit_icon/move/unit_icon_move_Wight_Bow_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p69.o: graphics/unit_icon/move/unit_icon_move_Bael_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p70.o: graphics/unit_icon/move/unit_icon_move_Elder_Bael_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p73.o: graphics/unit_icon/move/unit_icon_move_Mauthedoog_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p74.o: graphics/unit_icon/move/unit_icon_move_Gwyllgi_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p75.o: graphics/unit_icon/move/unit_icon_move_Tarvos_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p76.o: graphics/unit_icon/move/unit_icon_move_Maelduin_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p77.o: graphics/unit_icon/move/unit_icon_move_Mogall_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p78.o: graphics/unit_icon/move/unit_icon_move_Arch_Mogall_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p79.o: graphics/unit_icon/move/unit_icon_move_Gorgon_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p80.o: graphics/unit_icon/move/unit_icon_move_Gorgonegg_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p81.o: graphics/unit_icon/move/unit_icon_move_Gargoyle_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p82.o: graphics/unit_icon/move/unit_icon_move_Deathgoyle_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p85.o: graphics/unit_icon/move/unit_icon_move_Demon_King_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p87.o: graphics/unit_icon/move/unit_icon_move_Blst_Long_Empty_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p88.o: graphics/unit_icon/move/unit_icon_move_Blst_Used_Empty_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p89.o: graphics/unit_icon/move/unit_icon_move_Blst_Killer_Empty_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p90.o: graphics/unit_icon/move/unit_icon_move_Civilian_M1_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p91.o: graphics/unit_icon/move/unit_icon_move_Civilian_F1_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p92.o: graphics/unit_icon/move/unit_icon_move_Civilian_M2_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p93.o: graphics/unit_icon/move/unit_icon_move_Civilian_F2_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p94.o: graphics/unit_icon/move/unit_icon_move_Peer_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p95.o: graphics/unit_icon/move/unit_icon_move_Queen_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p96.o: graphics/unit_icon/move/unit_icon_move_Prince_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p97.o: graphics/unit_icon/move/unit_icon_move_Queen_2_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p98.o: graphics/unit_icon/move/unit_icon_move_Unk77_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p99.o: graphics/unit_icon/move/unit_icon_move_Fallen_Prince_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p100.o: graphics/unit_icon/move/unit_icon_move_Tent_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p101.o: graphics/unit_icon/move/unit_icon_move_Pontifex_sheet.4bpp.lz
asm/dat_const_data_unit_icon_move_p102.o: graphics/unit_icon/move/unit_icon_move_Fallen_Peer_sheet.4bpp.lz
